### ISSUE TITLE
wordvector features  shape(491,300),but lables shape(13,1)

### ISSUE THREAD

**Issue by kingdsz** [A2Zadeh/CMU-MultimodalSDK#102]
Hi!Amir,I am a novice.Please forgive my ignorance!
wordvector feature  : <HDF5 dataset "features": shape (491, 300), type "<f8">
Opinion_lables: <HDF5 dataset "features": shape (13, 1), type "<f4">
Obviously, the video was divided into 13 segments with 13 tags. But I'm confused about 491 words and which ones belong to a segment. How do I put data into the model.
I'm very much looking forward to your help.

**Comment by kingdsz** [comment]
thanks，I already know.

**Comment by A2Zadeh** [comment]
Hello @kingdsz. Thanks for your question. Yes, the word vectors are for the entire video. Labels only exist for 13 segments of the video. Where the word vector falls into a segment, it belongs to that annotations. So for example, segment 0 can start from word 10 to word 16. To get what words belong to what segments you need to align based on segments. An example code is available here: https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/examples/mmdatasdk_examples/word_level_align.py

Don't hesitate to ask any questions. Happy to help!

**Comment by kingdsz** [comment]
@A2Zadeh Thank you from the bottom of my heart. I didn't know  word_level_align of function at first, but now I know it.

**Comment by A2Zadeh** [comment]
@kingdsz You are very welcome. Please be aware that there is an upcoming update to the text of CMU-MOSI. Be sure to redownload by March 10th for the latest feature sets.
