### ISSUE TITLE
Download ops seems to show wrong file sizes

### ISSUE THREAD

**Issue by Justin1904** [A2Zadeh/CMU-MultimodalSDK#104]
Currently, the downloading ops show the total sizes as well as the download speed, yet it seems it is off by a magnitude (i.e. Gb is shown as Mb). An example of this would be the MOSEI GloVe vectors are 2.5G in total yet the download ops show it is 2.56M, and while my downloading speed is actually 100+ Mb/s the download ops show that it is 100+ Kb/s. Not a big problem but could mislead people to have wrong estimates of the space required.

**Comment by A2Zadeh** [comment]
Oops. I will fix that :)! If you do happen to fix it for your own code, please pull so I can update the SDK as well. Otherwise I will fix it later today or tomorrow.
