### ISSUE TITLE
MOSEI citing raw data and labels

### ISSUE THREAD

**Issue by rhoposit** [A2Zadeh/CMU-MultimodalSDK#105]
Hi Amir, I'm wanting to cite the dataset generally. Is the SDK the only way to obtain the relevant bib-text? Or is there a general paper that I could cite? I'm just using the MOSEI raw data (videos) and the emotion intensity labels.

**Comment by A2Zadeh** [comment]
Hello Jennifer (@rhoposit). Sorry this fell through cracks. The citations are as follows:

`@inproceedings{cmumoseiacl2018, title={Multimodal Language Analysis in the Wild: {CMU-MOSEI} Dataset and Interpretable Dynamic Fusion Graph}, author={Zadeh, Amir and Liang, Paul Pu and Vanbriesen, Jon and Poria, Soujanya and Cambria, Erik and Chen, Minghai and Morency, Louis-Philippe},booktitle={Association for Computational Linguistics (ACL)},year={2018}}`

`@inproceedings{zadeh2018multi,
  title={Multi-attention recurrent network for human communication comprehension},
  author={Zadeh, Amir and Liang, Paul Pu and Poria, Soujanya and Vij, Prateek and Cambria, Erik and Morency, Louis-Philippe},
  booktitle={Thirty-Second AAAI Conference on Artificial Intelligence},
  year={2018}
}`

Also don't forget the citations for the features you use ;). If you can tell me what you are using, I can let you know the citations.
