### ISSUE TITLE
How to open and process the feature file with (.csd)？

### ISSUE THREAD

**Issue by hugddygff** [A2Zadeh/CMU-MultimodalSDK#106]
How to open and process the feature file with (.csd) in python？

**Comment by A2Zadeh** [comment]
Hello @hugddygff. Thanks for your interest in the SDK. You can find a good example here: https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/examples/mmdatasdk_examples/word_level_align.py

Please don't hesitate to ask other questions.

**Comment by hemnf** [comment]
Dear @A2Zadeh,
I used the above link to deploy the features, but I got the same .csd files with larger size. How can we read the deployed files and get the features?
Regards

**Comment by A2Zadeh** [comment]
Hello @hemnf. I will add an example of how to read the CSD files soon. It's hard to describe it in text, but much easier in code :)! Will try to do it today.

**Comment by hugddygff** [comment]
Further, when I run the feature file whose name has ".p" in matlab, there is a error message "Invalid pfile. The file header is corrupt".

**Comment by PrinsDragon** [comment]
Hi, I have a similar problem. I load the deployed file, but its content is hdf5 file. So how can I get the exact data in the format of dict or list from the dataset? Could you please give us a demo to show how to load the data? 
Thank you very much for your help!

**Comment by A2Zadeh** [comment]
Hello @PrinsDragon @hugddygff @hemnf 

I updated the https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/examples/mmdatasdk_examples/word_level_align.py with some commented lines. Make sure to uncomment all the lines outlined by ==> together. That shows how to use the information in the computational sequence. Let me know if you have further questions.

**Comment by SG-lab** [comment]
up please, I find errors whil opening csd file using tqdm notebook : 
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

**Comment by SG-lab** [comment]
I get an error trying to open a csd file with tqdm notebook :+1: 
---> for line in tqdm.notebook.tqdm(f, total=embedding_vocab):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

**Comment by A2Zadeh** [comment]
@SG-lab interesting. Can you give me some info on what python version are you using? Is your hdf5 updated? Which dataset are you getting?

Seems the error is not from the SDK but from tqdm. I will try to help, but most likely tqdm github is the best place to start a thread.

**Comment by SG-lab** [comment]
I use python 3.8.2; h5py should be up to date.

I am trying tu run @Justin1904 's [jupyter notebook tutorial](https://github.com/Justin1904/CMU-MultimodalSDK-Tutorials/blob/master/tutorial_interactive.ipynb) and find errors trying to load pretrained word embeddings. Please find below, a capture showing the error I get when I run the load_emb function
![image](https://user-images.githubusercontent.com/52422890/87652144-229b3a00-c754-11ea-9c1c-826e2635f9da.png)

No need to specify that because of it, I can't even train a model.

Thank you so much !

**Comment by schoobani** [comment]
Hi! 
I follow [this tutoria](https://github.com/Justin1904/CMU-MultimodalSDK-Tutorials/blob/master/tutorial_interactive.ipynb)l but I get the error that says: `CMU_MOSI_ModifiedTimestampedWords.csd file not found, please check the path`

**Comment by shivangpatel** [comment]
@schoobani What's the solution for the above issue you mentioned before? `CMU_MOSI_ModifiedTimestampedWords.csd` 
I hope on you that, you found the solution!!!!

**Comment by George-Drg** [comment]
Hello everyone, I just got my hands on the Multimodal SDK (I cloned the rep and added a PYTHONPATH) but as soon as I try to run the following lines I get an **IndexError: list index out of range** error. 

**lines:**
   _from_ mmsdk import mmdatasdk
   cmumosi_highlevel=mmdatasdk.mmdataset(mmdatasdk.cmu_mosi.highlevel,'cmumosi/')_

Any advice on how I could go past this issue?

Thanks in advance!
