### ISSUE TITLE
How to understand the features' meanings?

### ISSUE THREAD

**Issue by EdwardSLi** [A2Zadeh/CMU-MultimodalSDK#107]
Hi, @A2Zadeh 
  I have used your SDK to download and align all the dataset in MOSI.(It is really fast and cool!)

When I look into the data in the 'BERT', I find all of the segments will have 9216 features.
When it goes to 'GLOVE', it is 300 for each.

But what most confuses me is the meaning for 'COVAVREP' and 'FACET 4.1', they only have 74 and 47 features for each segment.

I have also downloaded the raw data for three modals in MOSI. And I found every segment is not identical even in length.
Since I only know little about images, I understands videoes as continous images at the rate of maybe 30 per frame. And they should be like (20,300,400) way. 
So I'd like to know how many frames in a segment are turned into only 47 dims and what they represent.(Since the audio and visual modal are not as efficient in judging sentiment as text, especially BERT, it is really strong)

Maybe it is just a strange question, hope you can explain it or provide some references.

**Comment by A2Zadeh** [comment]
Hello @EdwardSLi. The COVAREP and FACET are acoustic and visual features. So basically their input dimensions is 74 and 47. They are considered high level features (such as action units, NAQ, etc.) and therefore not the frames directly. I am in the process of updating SDK with the feature names. So you will be able to easily get the feature names from the SDK. Hope this helps. Feel free to ask any questions.

**Comment by EdwardSLi** [comment]
Thank you!
I have read the WIKI after I posed the question. I found it hopeful to read the Wiki, maybe you can make it a remainder.

And what confused me was about the alignment function. When I used the collapse_functions as the example, it will take the average of every segment. So I cannot correlate each word with its word embedding vectors...

Thank you again for your patience.

**Comment by A2Zadeh** [comment]
@EdwardSLi, You should be able to get the actual words from the raw data here: https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/mmsdk/mmdatasdk/dataset/standard_datasets/CMU_MOSI/cmu_mosi.py
