### ISSUE TITLE
error of the p-code of the provided old processed features on matlab, 

### ISSUE THREAD

**Issue by hugddygff** [A2Zadeh/CMU-MultimodalSDK#108]
when i run the p-code of the provided old processed features on matlab, it reports " Invalid pfile. The file header is corrupt".

How to solve this problem?

**Comment by A2Zadeh** [comment]
Hello @hugddygff, what dataset is this?

**Comment by hugddygff** [comment]
@A2Zadeh For example, in the link http://immortal.multicomp.cs.cmu.edu/raw_datasets/old_processed_data/pom/data/, the format of the old processed features are ".p" file. How to load these files to get the real features?

Thanks a lot

**Comment by hugddygff** [comment]
@A2Zadeh For example, in the link http://immortal.multicomp.cs.cmu.edu/raw_datasets/old_processed_data/pom/data/, the format of the old processed features are ".p" file. How to load these files to get the real features?

Thanks a lot

**Comment by A2Zadeh** [comment]
@hugddygff, those are pickle files.
