### ISSUE TITLE
about the label dimension of pom and iemocap?

### ISSUE THREAD

**Issue by hugddygff** [A2Zadeh/CMU-MultimodalSDK#111]
1. The label dimension of old processed pom dataset if 17, which is different from the dimension 16 on SDK, so can you illustrate the difference.

2. since the features of iemocap can not be obtained on SDK, I want to use the old processed features, However, I can not understand the label of old processed features, the label dimension is 11, can you illustrate the meaning of each dimension?

**Comment by A2Zadeh** [comment]
@hugddygff, we are adding a field to the SDK which demonstrates the meaning of the dimensions in computational sequences, the addition will be done by end of this week. Afterwards the metadata will have the feature dimension names. 

For the old data, I am adding @Justin1904 for the IEMOCAP feature descriptions. It's been a long time so hopefully we will remember things about old processed data :)

**Comment by A2Zadeh** [comment]
@hugddygff just to give a heartbeat on this thread, we are still working on putting dimension names in csd files. Backward compatibility is what is taking most of our time right now. We should have updates by the end of the week.

**Comment by A2Zadeh** [comment]
@hugddygff we have added a field for "dimension names" in metadata of the csd files. Around 50% of the csd files are updated now, mostly mosei and mosi. We will update the rest in the next 2 weeks.
