### ISSUE TITLE
Testing application for a model trained on MOSI dataset

### ISSUE THREAD

**Issue by Thani011** [A2Zadeh/CMU-MultimodalSDK#112]
Hi,
Great work in developing this multimodal SDK , its quite interesting to work using this . 

I have trained a bidirectional LSTM model on MOSI dataset .
Training complete fine (although there is scope for accuracy improvement that i will do later).
But my main target for now is to develop a testing application that will take a video file as input and after analysis from the model , give me the sentiment as response for that particular video segment .

Please guide me how can i proceed .
I am having troubles understanding how i will convert the video into the csd files that i can call upon later in form of dictionary ?

**Comment by A2Zadeh** [comment]
@Thani011, to create a computational sequence, you can have a look at the example:

https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/examples/mmdatasdk_examples/create_toy_computational_sequence.py

What you are planning for requires substantial amounts of engineering. First you need to process the video using OpenFace, COVAREP, OpenSmile or any other feature extraction method. Afterwards you will need to pass those as CSD to the SDK to align the audio and video (you need to also set up P2FA for forced alignment). Afterwards, the SDK can give you what you need for your application. Doable, but definitely substantial engineering needed. Keep me in the loop on how it goes :)

**Comment by Thani011** [comment]
@A2Zadeh Thank You for a quick response.

I am now able to create the CSD using the timestamp of each frame of video as interval and assigning feature vector with random values (using numpy random function) as suggested by you in the create_toy_computational_sequence.py 

If i am getting it right ?
For testing the model with my own data i need to convert the input video into the similar visual and audio features having the same dimensions as the data with which i have trained the model .

I can proceed in this direction if you could please provide the explanation of how you have extracted these features and preprocessed those features (if any required).

Thanks
