### ISSUE TITLE
How to divide the dataset into train and test?

### ISSUE THREAD

**Issue by PrinsDragon** [A2Zadeh/CMU-MultimodalSDK#113]
Is the official test dataset available? Or we are free to divide it?

**Comment by A2Zadeh** [comment]
@PrinsDragon The folds are available here: https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/mmsdk/mmdatasdk/dataset/standard_datasets/CMU_MOSI/cmu_mosi_std_folds.py
