### ISSUE TITLE
MOSI Processed data missing visual and acoustic features

### ISSUE THREAD

**Issue by sverma88** [A2Zadeh/CMU-MultimodalSDK#116]
Hi AMir,

The processed data for MOSI utilized in your earlier papers available at http://immortal.multicomp.cs.cmu.edu/raw_datasets/old_processed_data/cmu-mosi/ is missing acoustic and visual features. 
Moreover, the dimension of word embeddings is 325 whereas in the paper you've utilized 300-dimensional embeddings, right?

**Comment by A2Zadeh** [comment]
Hello @sverma88. The 325 is including the acoustic and visual. We have 5 features for acoustic and 20 features for visual (after feature selection according to our paper: https://dl.acm.org/citation.cfm?id=3136801)

**Comment by sverma88** [comment]
Hi Amir,

Thanks for clarification.
