### ISSUE TITLE
Missing WAV files in raw data (MOSEI)

### ISSUE THREAD

**Issue by MichaelGrundie** [A2Zadeh/CMU-MultimodalSDK#117]
I was running the MOSEI raw wav files through OpenSMILE and once it finished I noticed there were 522 unique file not found errors (attached). I did a little investigation (image) and seen the following:

- 522 of the video ids contained in CMU_MOSEI_LabelsSentiment.csd have no wav file with the same id.
- 532 of the wav files have no associated data in CMU_MOSEI_LabelsSentiment.csd

![Ubuntu 64-bit-2019-03-28-00-10-26](https://user-images.githubusercontent.com/16101792/55121319-e6247480-50f1-11e9-8939-e336ab7017ea.png)

[MissingFileErrors.txt](https://github.com/A2Zadeh/CMU-MultimodalSDK/files/3015806/MissingFileErrors.txt)

**Comment by A2Zadeh** [comment]
@MichaelGrundie Oops. Yeah we have 3303 when it should be 3837. I will update the compressed but it will take a full day to zip. You might find it faster if you extract the audio from videos. Or you can wait and I will update you when it is updated.

**Comment by A2Zadeh** [comment]
@MichaelGrundie The file is not being uploaded to the raw_datasets folder. I guess you can keep refreshing until the size doesn't increase. I will also notify you here once done.

**Comment by MichaelGrundie** [comment]
@A2Zadeh Thanks for that! 

Once I have extracted the OpenSMILE data for the intervals (I've done it for the files I have already), do you want me to send them your way? I've tried to do it in the same format as MOSI opensmile data. I used config file IS10_paraling for feature extraction, but I think you may have used emobase10 for MOSI. I don't know which is better. (Doing this for my final(3rd) year project so i'm pretty amateur at this stuff)

![image](https://user-images.githubusercontent.com/16101792/55195788-84254700-51a5-11e9-8173-4d2eabbaf94d.png)

**Comment by A2Zadeh** [comment]
@MichaelGrundie Absolutely! Please feel free to send it to me. I can fill the metadata and give proper credit to you for creation of the csd file. Can you email me with the dimension names? Simple strings would suffice for each dimension in the features. Thank you very much for your contribution!

**Comment by A2Zadeh** [comment]
@MichaelGrundie It is now copied. I replaced the original CMU_MOSEI.zip file.

**Comment by MichaelGrundie** [comment]
@A2Zadeh Great! thanks for the update.
