### ISSUE TITLE
can you share the old_processed feature of cmu-mosi  whose format is smilar to other dataset?

### ISSUE THREAD

**Issue by hugddygff** [A2Zadeh/CMU-MultimodalSDK#118]
since the other datset like pom, ict-mmmo, their old processed features have the same format and dimension of three modalities. However, for cmu-mosi, the format and dimension of visual and audio modality are a little different. Thus can you share the features of cmumosi like pom? And for the 325 dimensional features, which dimension represents audio, the same for visual and text?

**Comment by A2Zadeh** [comment]
Yes, please have a look at the: http://immortal.multicomp.cs.cmu.edu/raw_datasets/old_processed_data/cmu-mosi/readme.MD

**Comment by hugddygff** [comment]
@A2Zadeh can you share the features of cmumosi before selection?

**Comment by A2Zadeh** [comment]
@hugddygff that would be in the sdk through computational sequences. Also, the raw files include them.

**Comment by hugddygff** [comment]
@A2Zadeh Thanks for the quick reply! since I got much worse scores with the features of computational sequences of cmumosi than that of the old processed features of selecetion, I have not realized the results. Therefore, are there some mistakes in the computational sequences features?
