### ISSUE TITLE
Problem while training with my own created openFace.csd

### ISSUE THREAD

**Issue by Thani011** [A2Zadeh/CMU-MultimodalSDK#120]
Hi @Justin1904 @A2Zadeh 

Thank You for the great tutorial for the CMU-MultimodalSDK. Its very well explained.

I was successful in training the LSTM defined in this tutorial code with the CMU provided .csd files.

I created my own csd for visual feature from openface. But when instead of facet visual features csd file i used this csd . Rest features are unchanged.
The function of alignment with labels is throwing error this below error :-

```
<Status>: Unify was called ....
<Warning>: 9qR7uwkblbs entry is not shared among all sequences, removing it ...
<Warning>: POKffnXeBds entry is not shared among all sequences, removing it ...
<Warning>: BioHAh1qJAQ entry is not shared among all sequences, removing it ...

.....**same warning followed for other 88 videos**

Traceback (most recent call last):
  File "tutorial_interactive_demo.py", line 255, in <module>
    _visual = dataset[visual_field].data[segment]['features']
KeyError: ['2WGyTLYerpo[51]'[]
```

**Please guide me for the resolution for this
[log_train.txt](https://github.com/A2Zadeh/CMU-MultimodalSDK/files/3107405/log_train.txt)
** ? (I have also attached a log file of the training)
I have used features for 91 videos in the CMU-MOSI raw dataset instead of 23 available .
I aim to train the model on my own videos.
[log_train.txt](https://github.com/Justin1904/CMU-MultimodalSDK-Tutorials/files/3107379/log_train.txt)

**Comment by A2Zadeh** [comment]
Hi @Thani011,

Thanks for your interest in the SDK. The key in the recipe should be exactly similar to the key in the csd. Therefore, I think the key for OpenFace should be OpenFace. You can easily change the key in the csd by changing the "root name" field in metadata, if that works easier for you.

**Comment by Thani011** [comment]
@A2Zadeh 

Thank You. I will try this and then update you of the progress.

**Comment by Thani011** [comment]
@A2Zadeh 
No its still throwing the same error.
Can it be because i am using the older .CSDs into the latest sdk version ?

**Comment by A2Zadeh** [comment]
@Thani011 can you print out the ids in the computational sequence? Seems like the ids are not similar since unify is putting out warnings.

**Comment by Thani011** [comment]
@A2Zadeh 
Thanks.
I got where is the problem.
Before alignment when i print the video ids all the keys are present except two video keys for which i was not able to extract features. So i omited them in my OpenFace.csd which consists of 91 videos ids instead of 93 present in text and acoustic field .
Before alignment i got these warnings ->
```
<Warning>: c5xsKMxpXnc entry is not shared among all sequences, removing it ...
<Warning>: VbQk4H8hgr0 entry is not shared among all sequences, removing it ...
```
 
After alignment with text when i print the video ids in the visual field , there is only one video segment present(i.e visual keys :- ['2WGyTLYerpo[581]']) but for audio and text there is a large number of video segments present.

Similarly next after alignment with labels again for visual field only 1 segment is printed (i.e visual keys : ['2WGyTLYerpo[55]'])

This is the reason its throwing a key error at the end while accessing the unavailable video key ->
  ```
File "tutorial_interactive_demo.py", line 265, in <module>
    _visual = dataset[visual_field].data[segment]['features']
KeyError: '2WGyTLYerpo[52]'
```

Please help identify the resolution for this error .
Thank You.
[log_error2.txt](https://github.com/A2Zadeh/CMU-MultimodalSDK/files/3115600/log_error2.txt)

**Comment by A2Zadeh** [comment]
@Thani011, this is very strange. Can you check if your visual features actually have a length? For example if a frame happens at 0, we call that 0-0.033 (30fps).

**Comment by Thani011** [comment]
@A2Zadeh, Thanks You .
I by mistake pushed the wrong intervals of the frames into the CSD thats why this error is coming.
I will update my code and then come back to you with results.

Once again thanks a lot.

**Comment by A2Zadeh** [comment]
Awesome! Keep us in the loop :)
