### ISSUE TITLE
How to get password for IEMOCAP zip file?

### ISSUE THREAD

**Issue by DushyantChauhan** [A2Zadeh/CMU-MultimodalSDK#123]
Please provide me zip password for IEMOCAP. I have already taken permission from IEMOCAP (https://sail.usc.edu/iemocap/iemocap_release.htm) and then provide me a username and password. But this password is not working for the zip file. So please provide me the password to use this dataset.

**Comment by A2Zadeh** [comment]
@DushyantChauhan please contact me for the password on abagherz@andrew.cmu.edu
