### ISSUE TITLE
Emotion name for IEMOCAP dataset

### ISSUE THREAD

**Issue by DushyantChauhan** [A2Zadeh/CMU-MultimodalSDK#124]
IEMOCAP dataset has 11 emotion classes but in the original paper of IEMOCAP, only 10 classes are there. So will you provide me the emotion name corresponding to each column?

**Comment by convman** [comment]
Same issue, What do these 11 columns represent?

**Comment by A2Zadeh** [comment]
Hello and sorry for the late reply. Took us some time to figure it out. 

if pom has 17 dimensions they are:
Confidence Passionate Voice pleasant Dominant Credible Vivid Expertise Entertaining Reserved Trusting Relaxed Outgoing Thorough Nervous Sentiment Persuasive Humorous

if pom has 16 dimensions they are:
Confidence Passionate Voice pleasant Dominant Credible Vivid Expertise Entertaining Reserved Trusting Relaxed Outgoing Thorough Nervous Persuasive Humorous

if iemocap has 11 dimensions they are:
Other Anger Excited Fear Sad Surprised Frustrated Happy Neutral Disgust (unknown)

if iemocap has 9 dimensions they are:
Anger Excited Fear Sad Surprised Frustrated Happy Neutral Disgust

if iemocap has separate label files like angry_train.h5, angry_test.h5 then it’s just 2 dimensional one-hot indicating presence/absence of each emotion

mosei y_train, y_valid, y_test are 1 dimensional for sentiment

mosei ey_train, ey_valid, ey_test are 6 dimensional for emotions:
Anger Disgust Fear Happy Sad Surprise

**Comment by DushyantChauhan** [comment]
Thank you so much. This will be very helpful for me.

**Comment by convman** [comment]
Thanks!

**Comment by A2Zadeh** [comment]
@DushyantChauhan @convman Of course, any time.
