### ISSUE TITLE
Regarding to IEMOCAP dataset labels

### ISSUE THREAD

**Issue by hemnf** [A2Zadeh/CMU-MultimodalSDK#125]
Dear @A2Zadeh,
Thank you for your great work.
I would like to work on IEMOCAP dataset, when I checked the labels, I found that there are 10 different labels that not balanced. For example in train part:
('1=', 735)
('2=', 686)
**('3=', 19)**
('4=', 690)
**('5=', 65)**
('6=', 1235)
('7=', 338)
('8=', 954)
**('9=', 1)**
('10=', 1649)

I am kindly asking you if you have the emotion labels based emotions like Happy, anger,.. I will appreciate if I have it. If now how can we use these labels?

Thanks a lot for your help and support.

Regards

**Comment by A2Zadeh** [comment]
Hi @hemnf. There is the computational sequences for IEMOCAP on our server. You can browse and download from there. Those have label names associated with them in the metadata of the csd file. Let me know if you needed any help finding and extracting label names.
