### ISSUE TITLE
About speech pauses in glove_vectors

### ISSUE THREAD

**Issue by tungnt55** [A2Zadeh/CMU-MultimodalSDK#126]
Hi, I am trying to replicate the example in the tutorial. In this tutorial, there is a part about removing speech pauses to make sure the modalities are properly aligned. I understand that for text_field as raw string in the example, we can identify speech pauses by comparison with b'sp'. 
 
    # remove speech pause tokens - this is in general helpful
    # we should remove speech pauses and corresponding visual/acoustic features together
    # otherwise modalities would no longer be aligned
    words = []
    visual = []
    acoustic = []
    for i, word in enumerate(_words):
        if word[0] != b'sp':
            words.append(word2id[word[0].decode('utf-8')]) # SDK stores strings as bytes, decode into strings here
            visual.append(_visual[i, :])
            acoustic.append(_acoustic[i, :])

However, for glove_vectors this is not possible. So how do we remove the speech pauses in glove_vectors modality? Or we don't need to do that at all?

**Comment by A2Zadeh** [comment]
@tungnt55, two choices here: you can re-run the glove on the words or you can remove cases where glove embeddings were zero (if you used the actual glove)

**Comment by tungnt55** [comment]
> @tungnt55, two choices here: you can re-run the glove on the words or you can remove cases where glove embeddings were zero (if you used the actual glove)

Thank you for the answer. Just one more question for confirmation. By "actual glove", do you mean the glove_vectors computational sequence provided in the datasets?

**Comment by A2Zadeh** [comment]
Yeah that's the one :).

**Comment by hyang428** [comment]
@tungnt55  are you able to get the same testing result as the tutorial?
