### ISSUE TITLE
About the F1-score on Youtube?

### ISSUE THREAD

**Issue by hugddygff** [A2Zadeh/CMU-MultimodalSDK#127]
Hi,
Since Youtube has three labels, how to compute the f1-score?

**Comment by A2Zadeh** [comment]
@hugddygff, the calculation is done based on multi-class f1. It is from the scikit-learn package.

**Comment by hugddygff** [comment]
@A2Zadeh Hi, which average method do you use? micro or macro or weighted? Thanks
