### ISSUE TITLE
Data missing in cmu_mosei_std_folds.py

### ISSUE THREAD

**Issue by Jzmo** [A2Zadeh/CMU-MultimodalSDK#128]
I downloaded the RAW data of MOSEI and used cmu_mosei_std_folds.py to split the train, valid and test. I found there are some .wav file that are not included in the cmu_mosei_std_folds.py:

missing_files:
['-9YyBTjo1zo', '-Alixo7euuU', '-Eqdz5y4pEY', '-HvKLjmsO5U', '-IUUR2yyNbw', '-IqSFQePnpU', '-KCahx2qBOI', '-LnuDPiuuZw', '-RpZEe4w4fY', '-SYSVSQnTnA', '-VmheDA92mM', '-bl5PfNIYrk', '-cmk6cfUeMs', '-dZ1TCboxcQ', '-hPfPhUIzfA', '-l_53IwQoj0', '-m9KtvCk_L8', '-o_667Ny7RM', '-qMhGeJkp5o', '-wdUIwjDMfg', '1S4p-Lfhbp4', '1knHBRVPoYQ', '4Y8ROYezksQ', '5OUcvUDMMWE', '6ywl-j2-e-s', '7BFhRPlSOf0', '8vpoQ5UVpXE', '9OY3NU2ycVw', '9kLNVTm3Z90', 'AHXwnFvqYDk', 'AcoRjVPIVmQ', 'BgXqrxum5G4', 'CXvUdCdKTJY', 'EWYivXUavOY', 'EuSp1pkX9i8', 'FzxmeVRTjwU', 'JNt1k3ohkbs', 'MIqL9OXszRw', 'NVlxq3jxlAk', 'PEBwwe0PLZ8', 'TdCfpMRiA1c', 'TwFl4epL244', 'UcINGGuysBE', 'XnPnlRQXSkM', 'ZXQkyX6prBQ', 'aa2MEQ6FL7k', 'bDwAuRFciJM', 'cuR-l2qCxBc', 'dYgmvmFegkQ', 'fMUmdlzuc94', 'fiXZqpbRYKk', 'flv4by3RYVk', 'foXArPhK0xY', 'hytnfm-AVaA', 'mLZZ174bqws', 'nMCCLB9gOag', 'o5OsO6Aq9pA', 'o6Cd9RmqdBc', 'oNnoN0bxVnA', 'ptp-kfn4vWY', 'qYC3gN1AkOA', 'rKyXU0ls5aQ', 'slz8pd0Wzxs', 'tkzdanzsA0A', 'vn0CFvUK5D0', 'x-oexIBWwR4', 'zShw-E-yBqU']

Do you have any idea of which split these belong to?

**Comment by A2Zadeh** [comment]
@Jzmo Yeah those are just unsupervised data. CMU-MOSEI is technically a semi-supervised dataset. We decided to delay the release of most of the semi-supervised data for the second version of CMU-MOSEI. It will probably be released by the end of the Summer 2019, hopefully beginning of September.

**Comment by A2Zadeh** [comment]
@Jzmo just in case any of those videos has labels, then you can disregard them. Few videos got removed from the folds due to some issues; their annotations however are available still for use (since we give the full output of AMT).
