### ISSUE TITLE
FACET missing features during Sentiment level Alignment

### ISSUE THREAD

**Issue by amanshenoy** [A2Zadeh/CMU-MultimodalSDK#129]
The number of FACET features are lesser than the number of Sentiment Labels available. Since FACET features are missing for particular sentences and not clips, the whole clip needs to be removed because of which more information is lost.

Is this discrepancy taken care of, or is there a specific way to deal with this best?

![MOSEIFACETIssue](https://user-images.githubusercontent.com/40861444/59658871-80142e80-91c2-11e9-942d-c09e8f5b9c2f.png)

**Comment by A2Zadeh** [comment]
@amanshenoy there is two ways to deal with this: 1) unify which removes the videos without a particular computational sequence (this is what we do ourselves) 2) impute: which adds imputed values to that computational sequences based on a reference sequence (this is a bit more advanced and we don't use this). Feel free to choose yours!

**Comment by amanshenoy** [comment]
@A2Zadeh Would unify remove that sequence or the whole clip itself?

**Comment by A2Zadeh** [comment]
@amanshenoy it will remove any keys that don't exist among all computational sequences. So if you call unify on the code you sent up top, then it will remove all the VIDEOS which don't have all the computational sequences. In any case, even if you don't call it yourself, then when you do any form of alignment, SDK calls align and removes any ids that are not shared among sequences. Let me know if you want me to get into more details for you :). Happy to help.

**Comment by A2Zadeh** [comment]
@amanshenoy is this resolved?

**Comment by amanshenoy** [comment]
The image was taken after aligning on Sentiment Labels. FACET still stays exactly 8 behind. Thought of aligning wrt FACET itself but that turned out to be too inefficient. Any explicit way to unify after alignment?

**Comment by A2Zadeh** [comment]
@amanshenoy Oh yeah you shouldn't align to FACET if you want word alignments. My suggestion right now is to call imputate (w.r.t words computational sequence) on your aligned data to make sure those words without any FACET data are getting all 0s for FACET. In reality, FACET likely failed for those word and therefore we don't have any information for them. This is because other modalities are the correct shape, except FACET.

**Comment by amanshenoy** [comment]
I am using Sentiment label alignments. What is imputate called on? I am unable to find it in the SDK

**Comment by A2Zadeh** [comment]
@amanshenoy Ah ok. Then you can either call dataset.unify() or dataset.impute(ref_seq) to imputate the missing FACET features with zeros. If you call unify, all the keys that don't exist in all csds will be removed, i.e. you will end up with 23240 sentences. If you call impute you will end up with 23248 with 8 of the FACETs just being zero (for the sentences where FACET failed).
