### ISSUE TITLE
CMU-MOSEI word level alignment dont match in number for most computational sequences.

### ISSUE THREAD

**Issue by amanshenoy** [A2Zadeh/CMU-MultimodalSDK#130]
The number of Labels and features do not match the number of words for almost all computational sequences.

Is this discrepancy taken care of, or is there a specific way to deal with this best?

**Comment by A2Zadeh** [comment]
@amanshenoy they shouldn't. The segments or better yet sentences is MOSEI have only one label. For example:

I loved this video it was so good => 1 label for each emotion and 1 sentiment label.
