### ISSUE TITLE
MOSI missing glove and BERT embeddings?

### ISSUE THREAD

**Issue by amanshenoy** [A2Zadeh/CMU-MultimodalSDK#131]
SDK does not have any textual features (BERT or Glove or word2vec) for CMU-MOSI. The script for downloading computational sequences shows that functionality existed and now has been commented out.

Any updates soon? or any particular way to deal with this?

**Comment by A2Zadeh** [comment]
@amanshenoy, unfortunately not yet. I am currently busy releasing the codes for Social-IQ. I can update things maybe around this weekend. Can you ping me here again or shoot me an email in case I forget? :)

**Comment by tidd99** [comment]
is it possible just to turn on an older version of the embeddings? In particular, the glove embeddings would be very useful.

**Comment by A2Zadeh** [comment]
@amanshenoy @tidd99 I just uploaded the old ones here: http://immortal.multicomp.cs.cmu.edu/cache/CMU_MOSI_TimestampedWordVectors.csd

But again, I will upload the one with the newest alignments soon.

**Comment by A2Zadeh** [comment]
@amanshenoy @tidd99 I just updated the glove vectors to version 1.1. You can pull the SDK again. BERT will take a bit longer for running. Will be in touch.

**Comment by A2Zadeh** [comment]
@amanshenoy @tidd99 You might wanna get the glove vectors again. Some modifications happened to it.
