### ISSUE TITLE
Order of Emotions in computational sequence 'Emotion Labels'

### ISSUE THREAD

**Issue by amanshenoy** [A2Zadeh/CMU-MultimodalSDK#134]
Was wondering if the order of the emotions in the computational sequence 'Emotion Labels' is the same as mentioned in the paper {happiness, sadness, anger, fear, disgust, surprise}? If not what is the order.

**Comment by amanshenoy** [comment]
@A2Zadeh Also the WA and F1 mentioned in the paper for each emotion label - are they metrics on {0,1} classification? If so was there a threshold used? Or were all non zero values taken to be 1?

**Comment by A2Zadeh** [comment]
@amanshenoy The SDK is in this order: happy,sad,anger,surprise,disgust,fear
The old processed data, I will need to dive into the code and find that. 

0->0
anything else goes to 1.

**Comment by FelixFox** [comment]
Hello, @amanshenoy ! It seems you succeed in extracting emotion labels from data using repo. I've created an issue ( https://github.com/A2Zadeh/CMU-MultimodalSDK/issues/144 ) and it's still unresolved. How did you get these emotion labels?

Thank you!
