### ISSUE TITLE
How do you extract starting time and end time corresponding to each word? 

### ISSUE THREAD

**Issue by DushyantChauhan** [A2Zadeh/CMU-MultimodalSDK#139]
I was woking on raw MOSEI dataset and i want to get starting and end time for each word. Can you tell me how did you extract?

**Comment by A2Zadeh** [comment]
Hello @DushyantChauhan. You can just do the following:

`words=cmumosi["words"]`
`for videoid in words.keys():`
`    numwords=words["videoid"].shape[0]`
`    for i in numwords:`
`        print words[videoid]["features"][i],words[videoid]["intervals"][i]`

**Comment by DushyantChauhan** [comment]
Thank you for your reply.
Yes, i have done work with this dataset.

I just want to know the genric method to extract starting time and end time
from any random video.

**Comment by A2Zadeh** [comment]
@DushyantChauhan great. Did that solve the problem or did I miss a part of your question?

**Comment by DushyantChauhan** [comment]
Let suppose you download a random video from YouTube or any other site.
Then you can convert this video to mp3 and mp3 to text. I want to break
this video into small clips based on the words.
For example, if a video has 15 words then I need 15 small clips
corresponding to each word.

In MOSEI dataset, you have done this type of work. So I just wanted to know
how did you do?

Am I clear now?


*Regards,*
Dushyant Chauhan

**Comment by A2Zadeh** [comment]
@DushyantChauhan Ah ok. Yes, we use forced alignment methods including P2FA (https://github.com/A2Zadeh/AZP2FA) and the newest one we use is MFA (https://github.com/ASchneidman/Multilingual-Packaged-MFA-Aligner).
