### ISSUE TITLE
Getting only Covarep Features

### ISSUE THREAD

**Issue by FrancoisLem** [A2Zadeh/CMU-MultimodalSDK#140]
Hello, 

I wanted to know if it is possible to download only the covarep features with the labels since the visual features are so heavy and long to download. 
Maybe something like 
cmumosei_highlevel = mmdatasdk.mmdataset(mmdatasdk.cmu_mosei.highlevel.covarep,'cmumosei/')
cmumosei_highlevel.add_computational_sequences(mmdatasdk.cmu_mosei.labels, 'cmumosei/')
cmumosei_highlevel.align('Emotion Labels')
? 

Thank you

**Comment by A2Zadeh** [comment]
@FrancoisLem mmdatasdk.cmu_mosei.highlevel is actually just a dictionary. You can remove the keys you don't want and it will download the remaining ones ;).
