### ISSUE TITLE
CMU-MOSI dataset labels for raw data

### ISSUE THREAD

**Issue by Mikzinj** [A2Zadeh/CMU-MultimodalSDK#141]
Hi Amir, can you please help me with suggesting where I can find labels for the raw data of the MOSI dataset. I want to extract the acoustic features on the raw files, I am basically doing multimodal sentiment analysis (Audio+Text)  but I'm struggling with finding the ground truth labels

**Comment by A2Zadeh** [comment]
@Mikzinj of course, happy to help. There are two ways to do this: 1) you can get the sentiment labels computational sequence 2) you can download the CSV file that contains the same. Which one do you prefer and I can point you in the right direction.

**Comment by Mikzinj** [comment]
CSV file option seems convinient

**Comment by A2Zadeh** [comment]
@Mikzinj Perfect. That data should be on the raw files, where the labels are. You can download the raw from here: http://immortal.multicomp.cs.cmu.edu/raw_datasets/

**Comment by Mikzinj** [comment]
Hi Amir, I can't seem to find labels other the MOSI dataset.

**Comment by A2Zadeh** [comment]
@Mikzinj If you download the raw file, then after unzipping you can have a look at Labels/OpinionLevelSentiment.csv. Please let me know if you found it.

**Comment by Mikzinj** [comment]
No, it's not there. Please send me the file separately if you have it. Basically, I am doing multimodal(audio+text) sentiment analysis and my supervisor didn't want me to use the preprocessed data from the sdk but I believe I can if I can add the additional acoustic features to the features that the sdk already has, so I wanted to know what your opinion is on the matter.

**Comment by A2Zadeh** [comment]
@Mikzinj Of course. Here is the file: http://immortal.multicomp.cs.cmu.edu/cache/

Format is start,end,videoid (identical to youtube id),segment# (starts at 1),sentiment score in range [-3,3]

**Comment by Mikzinj** [comment]
Thanks Amir, much appreciated..

**Comment by kavya-45** [comment]
@A2Zadeh 
       Hi Amir,
              Your download link doesn't work http://immortal.multicomp.cs.cmu.edu/cache/ how can I get raw labels for CMU-MOSI please help me. Thanks in advance.

**Comment by pavanreddy0829** [comment]
> No, it's not there. Please send me the file separately if you have it. Basically, I am doing multimodal(audio+text) sentiment analysis and my supervisor didn't want me to use the preprocessed data from the sdk but I believe I can if I can add the additional acoustic features to the features that the sdk already has, so I wanted to know what your opinion is on the matter.
