### ISSUE TITLE
MOSI audio features.

### ISSUE THREAD

**Issue by convman** [A2Zadeh/CMU-MultimodalSDK#143]
I downloaded MOSI features from [old_processed_data](http://immortal.multicomp.cs.cmu.edu/raw_datasets/old_processed_data/).
for example, X_train has the shape (1284, 20, 325), I want to know the index which represents only audio features from these features.

**Comment by A2Zadeh** [comment]
Hello @convman, the dimensions are 0-300 for words, 300-305 for audio, 305-325 for videos. These are the results after feature selection (on FACET and COVAREP). For other features you can refer to SDK, for example I am being told that OpenFace and OpenSmile are working better than FACET and COVAREP.
