### ISSUE TITLE
Issue about Emotion labels

### ISSUE THREAD

**Issue by FelixFox** [A2Zadeh/CMU-MultimodalSDK#144]
Thanks for your repo! I've a question about labels.

How to get Emotion labels from CMU_MOSEI_LabelsEmotions.csd?
I've written the next code:

`dataset=mmdatasdk.mmdataset(mmdatasdk.cmu_mosei.labels,'./cmumosei')`

In debug mode I see the next picture:
![image](https://user-images.githubusercontent.com/10499696/61777675-00533280-ae06-11e9-8c81-0201b166b3ad.png)

When we look into data, we get something like this:
![image](https://user-images.githubusercontent.com/10499696/61777695-0812d700-ae06-11e9-98a9-34541e96882c.png)

I can not see emotion labels here (like sadness, neutral etc. in encoded state or not)

What have I to do to get them for each frame in videos?

**Comment by A2Zadeh** [comment]
@FelixFox Good question. You can get the data using dataset["Emotion Labels"][vidid]["features"] and the interval for the beginning and end of sentence (or segment) from dataset["Emotion Labels"][vidid]["features"]. The metadata (dataset["Emotion Labels"].metadata["dimension names"]) contains information on what the 6 dimensions correspond to, but here is the order [happy,sad,anger,surprise,disgust,fear]. Hope this helps.

**Comment by A2Zadeh** [comment]
@FelixFox Of course. You are very welcome. Please don't hesitate to ask any other questions. Good luck with your experiments.

**Comment by FelixFox** [comment]
@A2Zadeh  Thank you for your answer! I've tried to find this data using your tip and I could not find it :(  When I explicitly typed these variables in the watch list in the debugger, it showed me the next picture:
![image](https://user-images.githubusercontent.com/10499696/61881011-9bc7ce80-aefe-11e9-9f41-ed6997be1854.png)

What did I do wrong? Again, thank you for your answers!

**Comment by A2Zadeh** [comment]
@FelixFox Turns out I hadn't put the metadata ["dimension names"] in that file. I am fixing it now.

**Comment by FelixFox** [comment]
@A2Zadeh  Thank you a lot! :)

**Comment by liufh3** [comment]
First I used SDK to download label for MOSEI dataset:
`mydict={'Label':'./CMU_MOSEI_LabelsEmotions.csd'}`
`mydataset=md.mmdataset(mydict)`

And used this code to get the label for video with ID '-3g5yACwYnA':
`mydataset.computational_sequences['Label'].data['-3g5yACwYnA']['features'][:]`

And this one to get the interval for video with ID '-3g5yACwYnA':
`mydataset.computational_sequences['Label'].data['-3g5yACwYnA']['intervals'][:]`

Hope this can help you

**Comment by A2Zadeh** [comment]
@liufh3 Thanks a lot for your response. @FelixFox Sorry I didn't understand your question at first, my bad. When you get the emotions the way @liufh3 kindly mentioned, you will get a matrix of 1x6 with values in this order: [happy,sad,anger,surprise,disgust,fear]. Does this solve the problem?

**Comment by FelixFox** [comment]
@liufh3  Thank you a lot! That was really helpful!  Good luck in your experiments :)

@A2Zadeh  Yes, this problem is solved, thank you a lot again :)

**Comment by A2Zadeh** [comment]
@FelixFox Happy to help. Please don't hesitate to open an issue if something else arises. Good luck with your experiments.

**Comment by padisarala** [comment]
Can anyone let me know is there any other way to get the labels for MOSEI dataset with start and end timings rather than using SDK. I am trying to generate my own features from the raw dataset. I downloaded the dataset but not able to get the labels for the data

**Comment by A2Zadeh** [comment]
Hi @padisarala. The labels should be in the raw dataset that I put up for download. If you are not able to find it, they are here: http://immortal.multicomp.cs.cmu.edu/cache/Labels/

Good luck.

**Comment by padisarala** [comment]
I downloaded the label folder but it has following  csv files. I used extreme_sentiment_results.csv, mturk_exrtra_v2.csv files. But when checked the corresponding labels for video segmented files, I found labels for for very few files. I have not seen any label file which gives filenames, corresponding start, end timings, and labels.  Your help is highly appreciated. Thank you
5000_batch_raw.csv
Batch_2980374_batch_results.csv 
extreme_sentiment_results.csv 
mosi_pom_output.csv 
mturk_extra_v2.csv
pom_extra_sqa_mono_results.csv

**Comment by A2Zadeh** [comment]
@padisarala, all the csv files are for the labels (therefore, you have to combine them into one big one). The timings would be in the transcript/segmented folder in the raw zip file of the CMU-MOSEI: http://immortal.multicomp.cs.cmu.edu/raw_datasets/CMU_MOSEI.zip. That is where we have segment numbers (in the excel files), with their corresponding start and end.

**Comment by A2Zadeh** [comment]
@padisarala, interestingly, I think the easiest way for you would be to just use the computational sequences. Are you just looking for start and end of the sentences? This might be it: 

```
labels={}
labels["All Labels"]="http://immortal.multicomp.cs.cmu.edu/CMU-MOSEI/labels/CMU_MOSEI_All_Labels.csd"
```

**Comment by padisarala** [comment]
There are 6 csv files under label folder and can I combine them to get  get labels for all the files in the video segmented folder? 
I agree that start and end timings are included in the transcript. I need start and end timings to segment audio files and simultaneously assign labels to them.

**Comment by padisarala** [comment]
To process .csd files, I need to use SDK tool otherwise I don't know how to access then in python.
