### ISSUE TITLE
Add acoustic features to dataset

### ISSUE THREAD

**Issue by Mikzinj** [A2Zadeh/CMU-MultimodalSDK#145]
Hi Amir, please assist.. I'm trying to change my csv file with my features to a computational sequence but I had errors from the code in the examples. So I wanted to ask if there's a way that I can use to add my acoustic features to the ones of the sdk ? I have prosody,speech rate and loudness features additional to the ones that are already on the sdk

**Comment by A2Zadeh** [comment]
@Mikzinj Of course. This tutorial might help you on how to put your data in SDK format: https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/examples/mmdatasdk_examples/create_toy_computational_sequence.py

Underneath the SDK format, there is really a simple paradigm: every set of features have a beginning and an end in time. If you do that part, the rest is up the SDK. Let me know if the issue persists.

**Comment by A2Zadeh** [comment]
Hello @Mikzinj, just wanted to follow up and see if that tutorial helped. If you wanted to rate it between 1-5 how would you rate how useful it was. I wanna make sure it is easy to start working with SDK. Your feedback is greatly appreciated!

**Comment by Mikzinj** [comment]
Hi Amir, I had a problem with the shape of the data. i'm currently getting this error : 
Aligning Hello:   0%|          | 0/1 [00:00<?, ? Segments/s]Traceback (most recent call last):
  File "C:/Users/216011757/Music/Research/CMU-MultimodalSDK-Tutorials-master/untitled-5.py", line 54, in <module>
    mydataset.align("compseq_1")
  File "C:\Users\216011757\Music\Research\CMU-MultimodalSDK-Tutorials-master\mmsdk\mmdatasdk\dataset\dataset.py", line 123, in align
    intersects,intersects_features=self.__intersect_and_copy(ref_time,relevant_entries[otherseq_key][entry_key],epsilon)
  File "C:\Users\216011757\Music\Research\CMU-MultimodalSDK-Tutorials-master\mmsdk\mmdatasdk\dataset\dataset.py", line 259, in __intersect_and_copy
    where_intersect=(numpy.all((sub_copy-ref_copy)>(-epsilon),axis=1)==True)
builtins.ValueError: operands could not be broadcast together with shapes (1,134) (120,)

**Comment by A2Zadeh** [comment]
@Mikzinj So everything in the SDK requires you to have at least a 2D matrix, even if you have one entry. Say there is one video, with one word "hello". Then in that case the features and intervals are 1 x m (m being feature size, say 300 for glove) and 1 x 2 (for intervals).

**Comment by Mikzinj** [comment]
Oh thanks Amir, I can see it now. Is it possible to modify the dataset in the sdk and replace the CMU_MOSI_Opensmile.csd with my own opensmile features?

**Comment by A2Zadeh** [comment]
@Mikzinj Of course. Feel free to do so. The whole purpose of SDK is to democratize multimodal learning and encourage new features and new alignment techniques. Feel free to share the data with others as well.

**Comment by A2Zadeh** [comment]
@Mikzinj Feel free to reach out to me if you wanted to share the data with the community.
