### ISSUE TITLE
How is 4-class accuracy calculated?

### ISSUE THREAD

**Issue by tidd99** [A2Zadeh/CMU-MultimodalSDK#146]
I saw in the First Grand Challenge and Workshop
on Human Multimodal Language (Challenge-HML) that emotion recognition models were evaluated based on a "4-class accuracy". From what I understand this is calculated by binning the emotion intensity scores into 4 groups and measuring whether the model prediction was in the correct bin. I'm interested to evaluate my models by the same metric - would you be able to provide the equation for 4-class accuracy or (better yet!) the script you used to calculate it if that's still around somewhere?

Any help appreciated :-)

**Comment by A2Zadeh** [comment]
Hello @tidd99. Great question. The answer is the round function and when you get 4 just map to 3. This is by no means scientifically proven to be the correct way. CMU-MOSEI is purely baed on intensity, and we only use accuracy to show some understandable measures. My favorite measures are MAE, MSE and Correlation and all our trained models are based on MSE. Hope this help.

**Comment by A2Zadeh** [comment]
@tidd99 Let me know if you needed further help for this issue. I can reopen it.
