### ISSUE TITLE
Connection error in downloading mosei dataset

### ISSUE THREAD

**Issue by romass12** [A2Zadeh/CMU-MultimodalSDK#148]
`mosei = Dataloader('http://sorena.multicomp.cs.cmu.edu/downloads/MOSEI')
mosei_facet = mosei.facet()
mosei_emb = mosei.embeddings()`
I am getting this error:
URLError: <urlopen error [Errno 110] Connection timed out>

**Comment by A2Zadeh** [comment]
Hello @romass12, this is probably from an old code. What code are you using? Sorena server is no longer active.

**Comment by romass12** [comment]
Hello @A2Zadeh  thank you for informing. Do you have the link from where the raw dataset pkl files was created for MOSEI

**Comment by A2Zadeh** [comment]
@romass12, If you are working with pkl files, then it is the old version of the SDK. I don't have the exact files now since it has been around a year that version got deprecated for the new one. Are you looking for word aligned features ready for going into a model?

**Comment by romass12** [comment]
@A2Zadeh considering I have a video , I then want to extract audio,text,video features using the same methodology used in creating pkl feature vectors from MOSEI data.

**Comment by A2Zadeh** [comment]
@romass12 Hmm, let me ask a few more questions to make sure I can help the best way. You mean you have a video that is not from MOSEI videos? If then, yeah certainly I can help guide you through the process. 

If it is MOSEI, then we do have the raw files in case that helps. Please let me know.

**Comment by romass12** [comment]
Yes @A2Zadeh a video not from MOSEI

**Comment by A2Zadeh** [comment]
@romass12 Then you will have to run OpenFace and COVAREP on that video. Are you trying to apply a model trained on MOSEI to videos outside?

**Comment by A2Zadeh** [comment]
@romass12 I am going to close the issue due to inactivity. Let me know if there is any questions remaining.
