### ISSUE TITLE
GroundTruth for MOSI dataset

### ISSUE THREAD

**Issue by Mikzinj** [A2Zadeh/CMU-MultimodalSDK#150]
Hi Amir, while doing alignment I tried looking at the intervals given in OpinionLevelSentiment file for the video at index 0 and the intervals are not the same as that of the MOSI_dataset. Like the first interval in the file is [27.87913832, 32.9276644 ] but in the mosi dataset its [1.00022676, 1.10997732]. Wouldn't this affect the credebility of my results ?

**Comment by A2Zadeh** [comment]
Hello @Mikzinj, happy to help. Can you elaborate what the MOSI_dataset is? You mean the raw files?

**Comment by Mikzinj** [comment]
Yes

**Comment by A2Zadeh** [comment]
@Mikzinj Long story short, your question had me check some stuff. I realized that a small misalignment happened when I was reprorcessing MOSI in the last month or so. Now the issue should be fixed. Let me know if it persists.

**Comment by Mikzinj** [comment]
Ok thank you so much, I will re check.. If I may ask Amir, is the model output continious or categorical ? from the values i'm seeing it seems it can be any value between -3 to 3 so but I want to know if I can do thresholding or something coz I want to have 7 classes as integers not -2.8 or 1.5 maybe but either -3 or 2 ?

**Comment by A2Zadeh** [comment]
@Mikzinj great. Please let me know if you found anything else. Again, the issue should not have affected the preprocessed data and computational sequences before around a month ago. 

Our method of doing 7 class was based on rounding. So I think as long as you use the round function it should be fine. This however, is different for MOSEI. I just updated information in this link: https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/mmsdk/mmdatasdk/dataset/standard_datasets/CMU_MOSEI/README.md

**Comment by Mikzinj** [comment]
Thank you very much Amir.
