### ISSUE TITLE
cannot download pom's COVAREP and OpenFace 

### ISSUE THREAD

**Issue by zhaohuande** [A2Zadeh/CMU-MultimodalSDK#152]
I cannot download COVAREP from http: //immortal.multicomp.cs.cmu.edu/POM/acoustic/POM_COVAREP.csd and OpenFace from http: //immortal.multicomp.cs.cmu.edu/POM/acoustic/POM_OpenFace2.csd.The URLs cannot open.

**Comment by A2Zadeh** [comment]
Hello @zhaohuande. I just opened the URLs. There does seem to be a space between http: and //immortal... in your writing. Could that have caused it?
