### ISSUE TITLE
Question about MOSEI sentiment Annotations

### ISSUE THREAD

**Issue by stdoo** [A2Zadeh/CMU-MultimodalSDK#153]
Hi, the sentiment labels have some values like 1.3333... or 1.6666... , if 1 for weakly positive and 2 for positive, what's the meaning of 1.3333... and 1.6666... ?

**Comment by A2Zadeh** [comment]
Hello @stdoo. Those are average over 3 annotations. So a value like 1.3333 can come from 1,1,2.

**Comment by stdoo** [comment]
@A2Zadeh Get it, thanks.
