### ISSUE TITLE
Problem with transcriptions. Some text files are in the byte form.

### ISSUE THREAD

**Issue by shamanez** [A2Zadeh/CMU-MultimodalSDK#157]
@A2Zadeh  I went through the raw dataset. This time I found 22K + video segment examples. But when it comes to transcripts or the text description of videos, some transcription text files are in byte format. Also, some text files consist of only numbers. I have attached a sample of such file. Can you please explain is this data corruption problem? If you have a clean transcription folder can you please share with us?
[_aJghSQmxD8.txt](https://github.com/A2Zadeh/CMU-MultimodalSDK/files/3674872/_aJghSQmxD8.txt)
[_7HVhnSYX1Y.txt](https://github.com/A2Zadeh/CMU-MultimodalSDK/files/3674873/_7HVhnSYX1Y.txt)
[_4K620KW_Is.txt](https://github.com/A2Zadeh/CMU-MultimodalSDK/files/3674875/_4K620KW_Is.txt)

**Comment by A2Zadeh** [comment]
@shamanez That is super weird, at least for the byte one starting with _a and the _7 with just numbers. I gotta check what happened there. 

For _4 one, what seems to be the problem?

**Comment by A2Zadeh** [comment]
@shamanez Also, aren't VTT files also there in the zip file?

**Comment by shamanez** [comment]
sorry what are VTT files ?

**Comment by shamanez** [comment]
@A2Zadeh  in the 4th one there's no problem. I just uploaded it to show that most of the files are correct.  Yeah, numbers and bytes are kind of weird. I double-checked by downloading the dataset for two times.

**Comment by A2Zadeh** [comment]
@shamanez Thanks for raising this issue. Do you see the VTT files in the raw dataset folder? Is that file also binary/numbers?

**Comment by shamanez** [comment]
No I don't see such files.

**Comment by A2Zadeh** [comment]
@shamanez, sorry for the late reply. I think I need to rezip the CMU-MOSEI to get those files. In the meantime, are you just looking for the transcripts, or more, what caused the weird transcripts. Do you have any stats on how many of them are like that?

**Comment by shamanez** [comment]
@A2Zadeh  I check for the missing transcription files. There are more than 8000 missings.  It would be nice if you can publish the raw text. I even ran google speech to text on the missing. But then transcriptions are a bit messy and also hard to benchmark with existing work. So can you please zip **transcriptions only**? It would be really nice.

**Comment by A2Zadeh** [comment]
@shamanez I can certainly do that. Of course, there is ground-truth transcriptions. You should just try to use them. Are you planning on using the glove or BERT embeddings? Because I can release those to you as well (in fact some glove is already on the SDK, I need to process BERT and XLNet for release - things have been a bit slow due to workload).

**Comment by shamanez** [comment]
Hi Amir,

I need only raw text. I can generate Bert  embeddings from them. :) .
Thanks a lot.

**Comment by shamanez** [comment]
Actually if you can give me raw text. I will generate all the Bert
embeddings for them. Then I can share that folder with you. Just want to
help you :)

**Comment by A2Zadeh** [comment]
@shamanez Ok, so here is all the stuff: http://immortal.multicomp.cs.cmu.edu/cache/TRS_MOSEI.zip

Let me know if you needed anything else.

**Comment by A2Zadeh** [comment]
@shamanez I actually have the BERT and XLNet for both MOSEI and MOSI. However, it would be super cool if you could extract T5 (https://github.com/google-research/text-to-text-transfer-transformer) and RoBERTa. Please make sure to extract them at sentence (i.e. annotation) level (otherwise it becomes unfair to other methods since they don't use larger than once sentence context).

**Comment by shamanez** [comment]
Ok I will do that. So where can I find all raw text file?

**Comment by shamanez** [comment]
Thanks a lot. I will upload embeddings from Roberta and T5 soon as possible.

**Comment by A2Zadeh** [comment]
@shamanez That would be awesome. We will make sure to acknowledge you for the upcoming Challenge-HML in ACL'20! Please don't hesitate to contact me if there were any questions. 

Also, if you are just looking for annotated sentences of MOSEI, then you can use the sdk to align labels with raw words. That way your script can also run on MOSI and other dataset (e.g. POM) to generate their embeddings too. Please also consider sharing your forks for both models so others can learn how to process their datasets from your scripts. 

Thanks a lot for considering this!!

**Comment by anita-hu** [comment]
@A2Zadeh Thanks for providing the raw text zip, I noticed they were missing some txt files. 347 video ids for the train fold, 35 for the valid, and 103 for test (folds from cmu_mosei_std_folds.py). I was wondering if you can provide the missing files. Thank you!
 
Examples of video ids missing for the train fold: 
'hh04W3xXa5s', '72tXTrSXoMk',  'YVHJpAROBvQ', '-iRBcNs9oI8', 'gZF-YNQHqwI', 'Z3fcd1wdzr0', '6TKaGMkO69E', 'ogGweZUAVtU', '254298', 'RadU51t1kL0', 'iREkcXde5ds', 'k1ca_xbhohk', 'dqragS38hCk', 'PohW-isYMK0', '0vXaXWx7Rvo', 'kf3fZcx8nIo', 'Sir2QeCh4B0', 'UK_IXtJ2BqI'
