### ISSUE TITLE
Question for processed data

### ISSUE THREAD

**Issue by 16631140828** [A2Zadeh/CMU-MultimodalSDK#158]
@A2Zadeh Can you tell me what the 5 dimension audio data and 20 dimension video data mean in aligned MOSI dataset or how do you get them?  Is the 5-D audio data extracted from the corresponding audio clips of each word using COVAREP?

**Comment by A2Zadeh** [comment]
Hi @16631140828. I am very sorry I completely missed this issue. I will extract that information and sent them over to you. Will also update the readme to reflect that.

**Comment by 16631140828** [comment]
Hi @A2Zadeh, thank you very much for your reply. But you haven't given the information about the 5-D audio data in the aligned MOSI dataset. I want to know what this 5-dimensional data means. Can you give me some information about it?
