### ISSUE TITLE
CMU-MOSI alignment issue

### ISSUE THREAD

**Issue by iyamabhishek** [A2Zadeh/CMU-MultimodalSDK#159]
Hi @A2Zadeh,

I am getting the following error when I try to download the processed CMU-MOSI features and align them using the myavg function. Can you please help me out?

def myavg(intervals,features):
       return numpy.average(features,axis=0)
Steps:
1. cmumosi_highlevel=mmdatasdk.mmdataset(mmdatasdk.cmu_mosi.highlevel,'cmumosi/')
2. cmumosi_highlevel.align('glove_vectors',collapse_functions=[myavg])

Error (at step 2):
RuntimeError: <Error>: Cannot collapse given the set of function.

**Comment by A2Zadeh** [comment]
@iyamabhishek Check your average function. Most of the time the problem is from the average function throwing exceptions.

**Comment by iyamabhishek** [comment]
Figured out that I was importing 'numpy as np'. In the myavg function, I updated numpy to np and it fixed the problem.

I hope this helps anyone who stumbles upon a similar minor typo.

Thank you!

**Comment by A2Zadeh** [comment]
@iyamabhishek I am going to add a more descriptive error. I think this has happened a few times and I wanna make sure to hint at possible causes.

**Comment by iyamabhishek** [comment]
Sure, it'll be great!
