### ISSUE TITLE
Emotion and Sentiment Analysis labels for the CMU-MOSEI dataset

### ISSUE THREAD

**Issue by tapan1911** [A2Zadeh/CMU-MultimodalSDK#160]
@A2Zadeh , i downloaded the raw CMU-MOSEI dataset from here: http://immortal.multicomp.cs.cmu.edu/raw_datasets/ 
but couldn't find the labels inside the zipped file. The only files present in the labels folder were these:
![image](https://user-images.githubusercontent.com/2168208/68159964-a7685f80-ff07-11e9-9f8c-7389c01c18c8.png)

Could you please provide the associated labels (both emotion and sentiment labels) for the transcripts which are present inside: CMU_MOSEI\Raw\Transcript\Segmented\Combined

**Comment by tapan1911** [comment]
Also it would be great if you could provide the segmented audio files. When i unzipped the CMU_MOSEI folder, i could only see a folder for the full audio files (CMU_MOSEI\Raw\Audio\Full) but nothing for the segmented ones.

**Comment by A2Zadeh** [comment]
Hello @tapan1911. 

==> First post: The files you mentioned are outputs of AMT excatly as we got from AMT website. You can actually use those this way: there is a column for segment number, which is the same as the segment number for the file in the Combined directory. So each video has a unique youtube_id and then a segment #. 

The easiest and most reliable way however, is to simply go based on **using** the SDK and aligning the sentiment labels with the raw words. Let me know if you need an example for this. 

==>Second post: You want the segmented audio and video files. One easy way to do that would be to download the timestamps of annotations from the SDK (either sentiment or emotions - they have the same intervals), and then use ffmpeg to crop the videos. You can use the following command:

ffmpeg -i input_video .mp4-ss hh:mm:ss.ms -to hh:mm:ss.ms output_video.mp4

Alternatively, I can do this for you. However, it will take some time.

**Comment by A2Zadeh** [comment]
I am assuming this issue was solved. Please feel free to open it if otherwise.

**Comment by ajwaaslam** [comment]
@A2Zadeh how can I get the labels for each modality? as I have to make unimodals for every modality.
Kindly, do let me know

**Comment by shivangpatel** [comment]
> @A2Zadeh , i downloaded the raw CMU-MOSEI dataset from here: http://immortal.multicomp.cs.cmu.edu/raw_datasets/ but couldn't find the labels inside the zipped file. The only files present in the labels folder were these: ![image](https://user-images.githubusercontent.com/2168208/68159964-a7685f80-ff07-11e9-9f8c-7389c01c18c8.png)
> 
> Could you please provide the associated labels (both emotion and sentiment labels) for the transcripts which are present inside: CMU_MOSEI\Raw\Transcript\Segmented\Combined

Can you explain these labels - File name... What the meaning of 5000_batch_raw and all others. Thanks
