### ISSUE TITLE
Is there any way to convert raw data in to features by using given methods in your paper?

### ISSUE THREAD

**Issue by shamanez** [A2Zadeh/CMU-MultimodalSDK#161]

**Comment by A2Zadeh** [comment]
Hi @shamanez. I am a bit confused, so please help me out here. When you say "given methods in our paper", do you mean word-level/phone-level fusion? 

We also do share identical data as we had in our paper. It is here: http://immortal.multicomp.cs.cmu.edu/raw_datasets/processed_data/

**Comment by shamanez** [comment]
Well, I asked about, whether this repo has codes which used to convert raw data into features, for example covering video frames to features using Facet.

**Comment by A2Zadeh** [comment]
@shamanez Ah I see. No, we don't have that part. Do you want me to give you the github of OpenFace 2.0, COVAREP and OpenSmile? Unfortunately FACET is a commerical software.

**Comment by shamanez** [comment]
Yeah having those links would be great. Thanks a lot. Is there any
alternative to extract facial information ?

**Comment by A2Zadeh** [comment]
@shamanez 

Yes. Here is 

OpenFace: https://github.com/TadasBaltrusaitis/OpenFace
OpenSmile: https://www.audeering.com/opensmile/
COVAREP: https://covarep.github.io/covarep/
P2FA: https://github.com/A2Zadeh/AZP2FA

**Comment by shamanez** [comment]
Thanks a lot.

**Comment by VirtualMoon** [comment]
@A2Zadeh    Could you please tell me how to convert the text data into features?
