### ISSUE TITLE
Can we get the access to data set split details (like what video ID s belongs to test set) using CMU-MultimodalSDK ?

### ISSUE THREAD

**Issue by shamanez** [A2Zadeh/CMU-MultimodalSDK#162]

**Comment by A2Zadeh** [comment]
@shamanez here it is: https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/mmsdk/mmdatasdk/dataset/standard_datasets/CMU_MOSEI/cmu_mosei_std_folds.py

You can also access via the sdk.
