### ISSUE TITLE
how to find the labels of CMU-MOSI dataset?

### ISSUE THREAD

**Issue by shamanez** [A2Zadeh/CMU-MultimodalSDK#163]
I download the raw **CMU-MOSI** dataset from the given link. But I can't find any file describing the labels of each segmented examples.

**Comment by A2Zadeh** [comment]
They are in raw MTurk format. They are csv files in the labels directory.

**Comment by shamanez** [comment]
I am sorry, I downloaded CMU_MOSI from [this](http://immortal.multicomp.cs.cmu.edu/raw_datasets/) link. But couldn't find any CSVs which contain labels.

**Comment by shamanez** [comment]
Actually, I found [this](http://immortal.multicomp.cs.cmu.edu/CMU-MOSI/labels/) location. Thanks :)
