### ISSUE TITLE
some mp4 videos in the raw data are corrupted.

### ISSUE THREAD

**Issue by shamanez** [A2Zadeh/CMU-MultimodalSDK#165]
Hi, I found 2882 mp4 files are corrupted. So I wrote them it to a text file. If you have time:),
[missing.txt](https://github.com/A2Zadeh/CMU-MultimodalSDK/files/3867817/missing.txt)
 it would be amazing to get those missing mp4 files.

**Comment by A2Zadeh** [comment]
@shamanez, where are you getting the files you attached? Is it under segmented videos?

**Comment by shamanez** [comment]
Yeah. Under segmented video.

**Comment by shamanez** [comment]
I also found some mp4 files without any visual on it. I can give that list too.

**Comment by A2Zadeh** [comment]
@shamanez Hmm could be from the download. Let me check and see if ffmpeg processes those videos. 

Please do share that list. It would be most helpful. Do you mean there is no face or simply FACET had failed?

**Comment by shamanez** [comment]
No no I’m talking only about the raw data.. the videos are just set of
black frames

**Comment by A2Zadeh** [comment]
@shamanez I see. Yes that list would also be most helpful. Can you run this command for a few of the videos?

ffmpeg -i input.mp4 

And see if ffmpeg says the video is corrupted?

**Comment by shamanez** [comment]
Sure. Actually I went through the raw datasets and labels. To double check
I will download them again and run all my scripts. Then I will create a
report on what labeled data are there , what are missing and what needed to
be labeled? Can you give me one day ?

**Comment by shamanez** [comment]
> fmpeg -i input.mp4

Actually this is what I got, 

ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'j1m6ctAgjsM_9.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.40.101
  Duration: 00:00:02.93, start: 0.020000, bitrate: 149 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 145 kb/s (default)
    Metadata:
      handler_name    : SoundHandler

**Comment by shamanez** [comment]
I went through the raw dataset given and labels. To double-check,
I I will download the zipped one again and run all data extraction scripts (more like raw data extraction) scripts. Then I will create a
report on what labeled data are there, what is missing and what needed to
be labeled?  I can also send you the label preprocessing scripts.

Can you give me one day?

**Comment by A2Zadeh** [comment]
@shamanez It seems that ffmpeg is able to find a stream for the file. Is 1m6ctAgjsM_9.mp4 one of the corrupt or black frame videos?

Sounds good to me. Let me know if you find any issues with the labels. Please note, few of the labeled data from MTurk was subsequently removed from the dataset due to various reasons. Label creation for CMU-MOSEI is a bit more complex than what may look on the surface.

**Comment by shamanez** [comment]
Yeah true ... specially with the score mechanism.. I also removed 3000+
since their score  does not give a solid idea about which label to select.
But having a solid raw data set of this size would be super useful to
emotion recognition community:).

**Comment by shamanez** [comment]
This problem is solved. I trip the corrupted video chunks again from the available full videos.
