### ISSUE TITLE
The utterance number of MOSEI is not consistent in ACL2018

### ISSUE THREAD

**Issue by Imorton-zd** [A2Zadeh/CMU-MultimodalSDK#166]
Thanks for your great project! 
I read the MOSEI data as the example in README.md. After alignment, the number of training, validation and test sets is  8273, 1071 and 2531. But in the paper of ACL 2018, the total number is 23453. What's wrong?

Looking forward your reply.

ACL 2018: Multimodal Language Analysis in the Wild: CMU-MOSEI Dataset and Interpretable Dynamic Fusion Graph.

**Comment by A2Zadeh** [comment]
@Imorton-zd That is very odd. In fact, that number has increased since we were able to fix some of the issues with previous feature extraction failure. Therefore the current number should be higher than 23453. Can you share you alignment code?

If you are looking for the newest preprocessed data, please have a look at the preprocessed_data folder.

**Comment by Imorton-zd** [comment]
```
def myavg(intervals,features):
        return np.average(features,axis=0)

train_ids, valid_ids, test_ids, text_dict, visual_dict, audio_dict, label_dict = choose_dataset('CMU_MOSEI')
    mosei_dataset = mmdatasdk.mmdataset(mmdatasdk.cmu_mosei.highlevel,'cmumosei/')
    mosei_dataset.align('glove_vectors',collapse_functions=[myavg])
    mosei_dataset.add_computational_sequences(mmdatasdk.cmu_mosei.labels,'cmumosei/')
    mosei_dataset.align('Emotion Labels')
    deploy_files={x:x for x in mosei_dataset.computational_sequences.keys()}
    mosei_dataset.deploy("./mosei_deployed",deploy_files)
    
    aligned_cmumosei_highlevel=mmdatasdk.mmdataset('./mosei_deployed')
    
#    print ('fea name', aligned_cmumosei_highlevel.keys()) 
    #[u'FACET 4.2', u'OpenFace_2.0', u'Sentiment Label', u'COAVAREP', u'glove_vectors', u'OpenSMILE', u'Emotion Labels'
    mosei_embeddings = aligned_cmumosei_highlevel['glove_vectors'].data
#    print ('mosei_embeddings keys()',mosei_embeddings.keys()[:10])
    #[u'DiOw-w5LDJ0[3]', u'mLW-jn67gRE[6]', u'31474[2]', u'H_x5O9GdknI[0]', u'2vsgDSlJ9pU[2]', u'mmg_eTDHjkk[14]', u'UXvMaHD9kmA[0]', u'Oj3XwBBrzXc[0]', u'45676[8]', u'qCUg4ek1PPE[1]']

    mosei_facet = aligned_cmumosei_highlevel['FACET 4.2'].data
    mosei_covarep = aligned_cmumosei_highlevel['COAVAREP'].data
    mosei_emotion = aligned_cmumosei_highlevel['Emotion Labels'].data
```
@A2Zadeh

**Comment by A2Zadeh** [comment]
Hello @Imorton-zd and apologies for late response. Is this issue resolved or should I dive into it deeper? Let me know.

**Comment by A2Zadeh** [comment]
I did the alignment multiple times and was not able to recreate the issue you were having. Let me know if the issue persists. Closing it for now.
