### ISSUE TITLE
Question about the mosi word-aligned data 

### ISSUE THREAD

**Issue by 16631140828** [A2Zadeh/CMU-MultimodalSDK#172]
Hi @A2Zadeh , can you tell me why the dimension of the aligned audio data in the MOSI dataset is 5, but 74 in MOSIE？How is the 5 dimension audio data of MOSI obtained?

**Comment by A2Zadeh** [comment]
@16631140828 Ah sorry. Here are the indices that are picked:

Dimensions from acoustic [1, 3, 6, 25, 60] from the normal output of COVAREP (which has 74).

Visual (FACET 4.1) [0, 2, 5, 10, 11, 12, 14, 17, 20, 21, 22, 24, 25, 29, 30, 31, 32, 36, 37, 40]
from
[Frametime,Face X,Face Y,Face Width,Face Height,angerEvidence,contemptEvidence,disgustEvidence,joyEvidence,fearEvidence,negativeEvidence,neutralEvidence,positiveEvidence,sadnessEvidence,surpriseEvidence,confusionEvidence,frustrationEvidence,angerIntensity,contemptIntensity,disgustIntensity,joyIntensity,fearIntensity,negativeIntensity,neutralIntensity,positiveIntensity,sadnessIntensity,surpriseIntensity,confusionIntensity,frustrationIntensity,AU1Evidence,AU2Evidence,AU4Evidence,AU5Evidence,AU6Evidence,AU7Evidence,AU9Evidence,AU10Evidence,AU12Evidence,AU14Evidence,AU15Evidence,AU17Evidence,AU18Evidence,AU20Evidence,AU23Evidence,AU24Evidence,AU25Evidence,AU26Evidence,AU28Evidence]

The first 300 is the word vectors, the next 5 are acoustic and the rest is visual. Hope this helps.

**Comment by 16631140828** [comment]
Thank you very much!
