### ISSUE TITLE
Can you make a brief introduction for each features you extract?Such as Openface et.Each picture has 711 dimensions features but I don't know what it is .please give a link to understand it.Thank you

### ISSUE THREAD

**Issue by david6666666** [A2Zadeh/CMU-MultimodalSDK#173]

**Comment by nanopoteto** [comment]
I also want to know that.

**Comment by A2Zadeh** [comment]
@david6666666 @nanopoteto that information is in the metadata of the computational sequences now, as a list of dimensions. Essentially: `myseq.metadata["dimensional names"]` gives you what you need.
