### ISSUE TITLE
Questions about the alignment of the ICMOCAP dataset

### ISSUE THREAD

**Issue by 16631140828** [A2Zadeh/CMU-MultimodalSDK#175]
Hi @A2Zadeh, I downloaded your exposed alignment processed IEMOCAP feature pack from http://immortal.multicomp.cs.cmu.edu/raw_datasets/processed_data/iemocap/seq_length_50/, but I can't match it to the raw data, I wonder if you have a file where the features correspond to the raw data.

**Comment by A2Zadeh** [comment]
Hi @16631140828. Can you give more details about your matching process? Specifically what does not match. Thank you.

**Comment by 16631140828** [comment]
I want to match the features to the corresponding raw text data, The IEMOCAP processed data is different from MOSI or MOSEI, It does not contain the id corresponding to the data.

**Comment by 16631140828** [comment]
Hi @A2Zadeh, Thank you very much for your reply and I want to match the features to the corresponding raw text data, The IEMOCAP processed data is different from MOSI or MOSEI, It does not contain the id corresponding to the data.
