### ISSUE TITLE
Align the csd files in CMU-MOSEI dataset.

### ISSUE THREAD

**Issue by cm-xcju** [A2Zadeh/CMU-MultimodalSDK#176]
I use the following code to align the csd files in CMU-MOSEI 

def myavg(intervals,features):
	return np.average(features,axis=0)
# cmumosi_highlevel=mmdatasdk.mmdataset(mmdatasdk.cmu_mosei.highlevel,'cmumosei/')
print ('what',mmdatasdk.cmu_mosei.highlevel)
mosei_dataset = mmdatasdk.mmdataset(highlevel,'data2/')
mosei_dataset.align('glove_vectors',collapse_functions=[myavg])
mosei_dataset.add_computational_sequences(labels,'data2/')
mosei_dataset.align('Emotion Labels')

I use the following code to read the aligned data.

 aligned_cmumosei_highlevel=mmdatasdk.mmdataset('aligned_data')
 embeddings = aligned_cmumosei_highlevel['glove_vectors'].data
 facet = aligned_cmumosei_highlevel['FACET 4.2'].data
 covarep = aligned_cmumosei_highlevel['COAVAREP'].data
 emotion = aligned_cmumosei_highlevel['Emotion Labels'].data

Is there any errors in my code? when I read the aligned data which uses the code above,I get the problems that the lengths of the three modalities are not equal lengths.Text has 23248 keys,Visual has 23240 keys , COAVAREP has 23248 keys and Emotion labels is 23248. 

In the meantime ,I get the keyError in visual keys *** KeyError: 'HuIKyKkEL0Q[0]'.This key can be founded in Text,COAVAREP ,Emotion labels,but can not be founded in Visual. 

Also,could you tell me the true length of our dataset using the csd files in CMU-MOSEI? I observe that 23248 may be shorter the true length.

**Comment by A2Zadeh** [comment]
Hello @cm-xcju 

That can happen as detectors may fail for a particular period within video. Therefore, there will be no information fro say COVAREP for a few words. You can call hard_align on the dataset to remove those instances. 23248 seems correct. We removed around 50 videos that had low quality post submission time. In some earlier preprocessed versions you can find those as well, but not in the most recent version which is on the SDK.

**Comment by cm-xcju** [comment]
Thankyou for your suggestions

**Comment by cm-xcju** [comment]
I ignore the unaligned data (KeyError), but I get only 22856. what causes this ? As you had said ,it should be 22348

**Comment by A2Zadeh** [comment]
Yeah by ignoring them you essentially remove the data points, hence smaller number. 

This is the github of the ACL Challenge 2020 (upcoming): https://github.com/A2Zadeh/ACL_Challenge_HML_20/tree/master/start_here

If you run the download file and then process file, you should get 23438 for all computational sequences including labels.

**Comment by cm-xcju** [comment]
Thankyou for your assistance

**Comment by A2Zadeh** [comment]
Awesome. Let me know if you had other questions.

**Comment by cm-xcju** [comment]
I tried your method ,but I need more time .The data has not been downloaded completely. It  is so large.Thankyou for your kind.

**Comment by cm-xcju** [comment]
I use your method . First I  download cmumosei (I download handly) .Then I run the preprocess_cmumosei.py .But it breaks off.

<Status>: Unify was called ...
<Warning>: PEBwwe0PLZ8 entry is not shared among all sequences, removing it ...
<Success>: Unify completed ...
<Status>: Pre-alignment based on <glove_vectors> computational sequence started ...
<Status>: Pre-alignment done for <OpenSMILE> ...
<Status>: Pre-alignment done for <COAVAREP> ...
<Status>: Pre-alignment done for <OpenFace_2.0> ...
<Status>: Pre-alignment done for <FACET 4.2> ...
<Status>: Alignment starting ...
Overall Progress:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▊      | 3629/3836 [42:51<03:25,  1.01 Computational Sequence Entries/s]Killedng vR90Pdx9wxs:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌         | 299/322 [00:00<00:00, 369.95 Segments/s]
 
This is the log before the interrupt.  I don't get the word_aligned_highlevel and final_aligned files

**Comment by A2Zadeh** [comment]
@cm-xcju Currently, the SDK is built for maximum speed, so it preloads everything in the RAM. Normally the machines we run this have a lot of RAM, but you could also get the same using a large swap space. Can you increase your swap space to 512GB on a say NVME or SSD hard drive? 

I will update the SDK later with some further optimizations that eliminates big RAM requirements for the alignment of the MOSEI. During alignment keep track of the RAM using "free -m" command, and ensure your 512G swap is fully enabled.

**Comment by A2Zadeh** [comment]
@cm-xcju This will help you with increasing the swap space: https://askubuntu.com/questions/178712/how-to-increase-swap-space

**Comment by cm-xcju** [comment]
I have tried another method , I only preprocess the four file ,  CMU_MOSEI_COVAREP.csd  ,CMU_MOSEI_TimestampedGloveVectors.csd ,CMU_MOSEI_VisualFacet42.csd CMU_MOSEI_LabelsEmotions.csd. And I succeed, but I get about 22860 (it should be 23248).
Is it necessary to align all the csd files to get the CMU-MOSEI?  It is difficult for me to increase the swap space. With the free -m command  I found that I only have about 8G swap space.

**Comment by A2Zadeh** [comment]
@cm-xcju 23248 is the correct number. Did the webpage I sent you help with increasing the swap space?

**Comment by cm-xcju** [comment]
Sorry,I do not have the root privilege to increase the swap space. Now ,I can get about 64G swap space. Can I not align the sentiment labels ? I only need the Emotion alignment.  I want to align the five source files ,CMU_MOSEI_VisualOpenFace2.csd, CMU_MOSEI_TimestampedGloveVectors.csdCMU_MOSEI_VisualFacet42.csd, CMU_MOSEI_COVAREP.csd,  , CMU_MOSEI_openSMILE_IS09.csd  and the target file CMU_MOSEI_LabelsEmotions.csd.  
Is it feasible?

**Comment by A2Zadeh** [comment]
@cm-xcju Oh ok, then I can do it for you and upload it somewhere you can use. Give me a few days?

**Comment by cm-xcju** [comment]
OK, thanks for your help and kindness.

**Comment by cm-xcju** [comment]
May I ask  if 23248 sets of data have been uploaded ？

**Comment by A2Zadeh** [comment]
Oh yes, I totally forgot to tell you here. The data can be found in this place: http://immortal.multicomp.cs.cmu.edu/ACL20Challenge/final_aligned/

Currently, emotion data is there. I am uploading the sentiment also soon.

**Comment by cm-xcju** [comment]
Thank you for your help

**Comment by cm-xcju** [comment]
I use the latest mmsdk to read the aligned data you upload ,but I get 22860 samples less than 23248 .what's wrong with me?

**Comment by A2Zadeh** [comment]
@cm-xcju Nothing is wrong. The number you are getting is correct. We had some videos removed post-deadline, which led to the number you are seeing now. So you are good to go!

**Comment by cm-xcju** [comment]
Thanks for your help all the time.

**Comment by A2Zadeh** [comment]
@cm-xcju Happy to help.
