### ISSUE TITLE
Question about CMU-MOSEI aligned data 

### ISSUE THREAD

**Issue by j20963j2000** [A2Zadeh/CMU-MultimodalSDK#177]
Hi, I want to know what is the difference between seq_length_20 and seq_length_50 in the aligned data folder. The following is the picture from the link you provide.
![image](https://user-images.githubusercontent.com/24569006/72073291-96cece00-332a-11ea-986d-bdc06d890b4d.png)

**Comment by j20963j2000** [comment]
Another question, I found there are some files at this path, "Index of/raw_datasets/processed_data/cmu-mosei/seq_length_20/labels". so I downloaded the "mosi2uni_Train_label_7class.csv" file, and I thought the values should be [-3, 3], but the values in this file are [0, 8]. Do I choose the wrong sentiment label file? 

thanks !

**Comment by A2Zadeh** [comment]
@j20963j2000 Yes, you can map that range back to -3,3. Alternatively, you can use the one that is sequence length 50. It is more up to date.
