### ISSUE TITLE
negative infinity value in the CMU-MOSI dataset

### ISSUE THREAD

**Issue by hyang428** [A2Zadeh/CMU-MultimodalSDK#179]
Hi, 

As described in the title, I found several sequences from "CMU_MOSI_COVAREP" have the value of negative infinity, which will definitely affect the feature normalization step.
Any insight of the negative infinity value here? thanks

**Comment by A2Zadeh** [comment]
Hi @hyang428,

Thanks for your interest in CMU-MOSI dataset. Those values should be replaced with 0 if you want to do the same thing we did. I am not sure if a better imputation method would work better here, but we simply resorted to the zero imputation method.
