### ISSUE TITLE
Import Error: No module name mmsdk

### ISSUE THREAD

**Issue by ankita-kalra** [A2Zadeh/CMU-MultimodalSDK#181]
Hi,

I have tried installing the CMU Multimodal SDK using the instructions given in the README.md. I have set the PYTHONPATH in my ~/.bashrc file, importing the mmsdk module raises me an import error. Any help with this will be much appreciated, I am using this for ACL Grand Challenge 2020. 

Thanks in advance!

Best Regards,
Ankita Kalra

**Comment by A2Zadeh** [comment]
Hi Ankita. Can you let me know which python version you are using? Also where you have copied the SDK.

**Comment by ankita-kalra** [comment]
Thanks for the prompt response Amir!

Python 2.7.13

Screenshot Attached:

<img width="710" alt="Screen Shot 2020-02-14 at 12 46 03 AM" src="https://user-images.githubusercontent.com/2662871/74504883-a4e0b300-4ec3-11ea-88d4-452538985367.png">

I tried adding both the paths $CHALML_PATH and $MMSDK_PATH to $PYTHONPATH.
It seems to be working now.

**Comment by A2Zadeh** [comment]
@ankita-kalra Seems like the issue is solved. We also have the word aligned data on our server, in case you wanna avoid re-running that part.
