### ISSUE TITLE
Question about the POM dataset labels 

### ISSUE THREAD

**Issue by kyabaria** [A2Zadeh/CMU-MultimodalSDK#182]
Hi. I have question about the POM.
POM contains  5 types of personality dimensions (agreeableness, conscientiousness etc) and 11 types of High-Level Attributes (conﬁdent, credible etc) as 16 dimensional vectors.
 I would like to know in what order these 16 types of labels are aligned.

**Comment by A2Zadeh** [comment]
Hello @kyabaria 

The traits are as follows: confident,passionate,voice_pleasant, dominant,credible,vivid,expertise,entertaining,reserved,trusting,lazy,relaxed,outgoing,thorough,nervous,humorous

**Comment by kyabaria** [comment]
Thank you very much.
