### ISSUE TITLE
Question about IEMOCAP aligned data

### ISSUE THREAD

**Issue by Kaicheng-Yang0828** [A2Zadeh/CMU-MultimodalSDK#183]
Hi @A2Zadeh, I download the aligned IEMOCAP data from http://immortal.multicomp.cs.cmu.edu/raw_datasets/processed_data/iemocap/seq_length_50/, but it doesn't contain ID information, so I can't match the feature with the original data now. Can you send me the corresponding table of features and raw file names? This will be very important to me. Thank you very much

**Comment by A2Zadeh** [comment]
Hi @16631140828,

Please see [this](https://github.com/A2Zadeh/CMU-MultimodalSDK/issues/185)
