### ISSUE TITLE
What is the sampling frequency of audio features ?

### ISSUE THREAD

**Issue by shamanez** [A2Zadeh/CMU-MultimodalSDK#186]
In the SDK we can directly use the COVAREP features. I just want to know what is the frequency of the raw audio. In the Multimodal Transformer paper, they have mentioned that they sample Audio in a 20hz frequency?  Is this mean input to the COVAREP signal is sampled at 20Hz ??

**Comment by A2Zadeh** [comment]
@shamanez I am not sure about the MulT paper, you may wanna contact Hubert or Paul. In the SDK, sampling of COVAREP and OpenSmile is done at 100 Hz.
