### ISSUE TITLE
Questions about the sample and its corresponding utterance for IEMOCAP dataset

### ISSUE THREAD

**Issue by showgood163** [A2Zadeh/CMU-MultimodalSDK#189]
Hi, I'm using the multi-modal sequences from http://immortal.multicomp.cs.cmu.edu/raw_datasets/processed_data/iemocap/seq_length_50/.

However, I didn't find and didn't know how to find the corresponding relationship between samples and utterances.

Could you please share a file to explain that or share your preprocessing scripts? Thanks!

**Comment by A2Zadeh** [comment]
Hi @showgood163,

IEMOCAP is processed with SDK V0, which was an older version of SDK. Not to say anything is wrong with the data, the word alignment and labels are reliable; but sadly the process was non-invertible as we only cared about getting the splits correctly to run our experiments. I believe getting it in the new SDK would be worth the effort, say if you were interested in doing it for the rest of the community.
