### ISSUE TITLE
Example for using aligned CMU-MOSEI dataset.

### ISSUE THREAD

**Issue by gullalc** [A2Zadeh/CMU-MultimodalSDK#190]
Hi,
I have managed to train a model on CMU-MOSI dataset by following the processing steps in https://github.com/Justin1904/CMU-MultimodalSDK-Tutorials, but would like to train the same models on CMU-MOSEI. 
As the MOSEI dataset is really large, I am trying to use the final_aligned data provided here: http://immortal.multicomp.cs.cmu.edu/ACL20Challenge/final_aligned/
It looks like the sequences in different modalities are not the same length in these csd files, which they should be after alignment (I am not sure if this is intentional or not).

Could someone provide an example of loading the data by using MOSEI aligned csd files ?

**Comment by A2Zadeh** [comment]
Hello @gullalc.

It's great to hear that the tutorial has been helpful for you. Can you clarify further what sequence is not the same length? Usually, the sequence length for the labels is only 1, as opposed to the sentences which I believe when compiled, I put as 50. I am very happy to help in this regard to get the ball rolling for you.

**Comment by gullalc** [comment]
Thanks for your quick response @A2Zadeh.

I am using this example snippet to load dataset following the tutorial, but skipping the alignment at word-level and w.r.t labels, because its already done in final_aligned folder for CMU_MOSEI.

1. First thing, would this be the correct way to do for CMU_MOSEI?

```
DATASET = md.cmu_mosei
DATA_PATH='../../final_aligned/'

# define your different modalities - refer to the filenames of the CSD files
visual_field = 'FACET 4.2'
acoustic_field = 'OpenSMILE'
text_field = 'glove_vectors'
label_field = 'All Labels'

## To load dataset with SDK given aligned csd folder path
dataset = md.mmdataset(DATA_PATH)

# a sentinel epsilon for safe division, without it we will replace illegal values with a constant
EPS = 0

# construct a word2id mapping that automatically takes increment when new words are encountered
word2id = defaultdict(lambda: len(word2id))
UNK = word2id['<unk>']
PAD = word2id['<pad>']

# place holders for the final train/dev/test dataset
train = []
dev = []
test = []

# define a regular expression to extract the video ID out of the keys
pattern = re.compile('(.*)\[.*\]')
num_drop = 0  # a counter to count how many data points went into some processing issues

for segment in dataset[label_field].keys():

    # get the video ID and the features out of the aligned dataset
    vid = re.search(pattern, segment).group(1)
    label = dataset[label_field][segment]['features']
    _words = dataset[text_field][segment]['features']
    _visual = dataset[visual_field][segment]['features']
    _acoustic = dataset[acoustic_field][segment]['features']

    # if the sequences are not same length after alignment, there must be some problem with some modalities
    # we should drop it or inspect the data again
    if not _words.shape[0] == _visual.shape[0] == _acoustic.shape[0]:
        print(
            f"Encountered datapoint {vid} with text shape {_words.shape}, visual shape {_visual.shape}, acoustic shape {_acoustic.shape}")
        num_drop += 1
        continue
```

2. The output for every segment here is similar to:
"Encountered datapoint CPjbogfLHR4 with text shape (21, 300), visual shape (212, 35), acoustic shape (84, 384)"

While using CMU_MOSI and following the full tutorial, the sequences had the same length. My assumption was that, the final_aligned csd files should contain the sequences with similar preprocessing.

**Comment by gullalc** [comment]
@A2Zadeh Any clarification on this?

**Comment by A2Zadeh** [comment]
Hi @gullalc. Can you look at this code, which is for our ACL 2020 Grand-Challenge: https://github.com/A2Zadeh/ACL_Challenge_HML_20/blob/master/start_here/process_cmumosei.py

Replace line 47 with the tensors you have and tell what output you are getting?

**Comment by gullalc** [comment]
Ok, I get it. I should just use the get_tensors() with sequence length to get equal length for all modalities. It was probably not a good idea to use the above code then.
Now the output looks fine:

**Comment by A2Zadeh** [comment]
@gullalc Great! Good luck with the experiments.
