### ISSUE TITLE
What are the 7 columns in CMU_MOSEI_All_Labels.csd

### ISSUE THREAD

**Issue by shamanez** [A2Zadeh/CMU-MultimodalSDK#191]
There are 7 values, which I think scores for each emotion.

**Comment by A2Zadeh** [comment]
Hi @shamanez,

Those would be: [sentiment,happy,sad,anger,surprise,disgust,fear]. It is in the metadata of the CSD file, but I also added it to MOSEI readme.

**Comment by A2Zadeh** [comment]
@shamanez this seems to be resolved. I will close it for now.

**Comment by shamanez** [comment]
Thanks a lot.
