### ISSUE TITLE
POM Dataset labels

### ISSUE THREAD

**Issue by tudordascalu** [A2Zadeh/CMU-MultimodalSDK#192]
Hi

I plan on using the POM dataset for a school project but I am confused in regards to how I can download it and use it in python. I tried getting the raw data, but I couldn't find the labels. Will you be able to clarify that for me? 

Thanks!

**Comment by KuzmaNg** [comment]
Hi, there. I think the mmdataSDK maybe helpful. You may give it a try. It includes the data feature and labels. https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/mmsdk/mmdatasdk/dataset/standard_datasets/POM/pom.py
