### ISSUE TITLE
Permission denied for accessing SDK

### ISSUE THREAD

**Issue by fatirali** [A2Zadeh/CMU-MultimodalSDK#193]
Dear Amir,

I tried accessing the SDK from Git Bash but my access is being denied. Is this dataset not open to the public? 

I am currently a Data Science Student in Toronto. 

Regards,
Fatir

**Comment by A2Zadeh** [comment]
Hi @fatirali,

Thanks for your interest in the SDK. Did you try cloning it? I would just do `git clone https://github.com/A2Zadeh/CMU-MultimodalSDK`

**Comment by fatirali** [comment]
Worked, thanks!

**Comment by A2Zadeh** [comment]
@fatirali You're welcome.
