### ISSUE TITLE
Extracting Spectrograms from CMU-MOSEI for Speech Emotion Recognition

### ISSUE THREAD

**Issue by KJ-Waller** [A2Zadeh/CMU-MultimodalSDK#194]
I have been trying to figure out how to get spectrograms from the CMU-MOSEI dataset in order to perform speech emotion recognition. However, I am having issues understanding the SDK and how to extract Emotion Labels and Spectrograms from the SDK. I am not familiar with the features the SDK provides (such as OpenFace2 and glove embeddings).

Firstly, getting the spectrograms. I believe OpenSmile-IS09 could provide spectrograms based on the description, but I am not sure how to get them. I tried to instead get the raw data from CMU-MOSEI so I could potentially generate the spectrograms myself, but I just realised that raw meant raw transcripts, not raw audio files.

Furthermore, I don't know how to get emotion labels from the SDK. I tried .align('Emotion Labels') as shown below and referenced in other posts on this repo, but I get "Computational sequence <Emotion Labels> does not exist in dataset".

mosei = mmdatasdk.mmdataset(mmdatasdk.cmu_mosei.raw, 'cmumosei/')
mosei.add_computational_sequences(mmdatasdk.cmu_mosei.labels, 'cmumosei/')
mosei.align('Emotion Labels')

Would anyone mind nudging me in the right direction to get emotion labels and spectrograms from CMU-MOSEI?

**Comment by marisancans** [comment]
Same, I have spent hours for a stupidly simple task: get dataset labels. This SDK is an overkill in my opinion. It's good that there are raw data available, but there are no csv with the labels? To get the csv I have to spend all this time trying yo figure out how this SDK works. It's a mess.

**Comment by A2Zadeh** [comment]
Hello @KJ-Waller. You can find the information you are looking for in this link: https://github.com/A2Zadeh/CMU-MultimodalSDK/tree/master/mmsdk/mmdatasdk/dataset/standard_datasets/CMU_MOSEI

That is the readme for CMU-MOSEI and I hope it gives you a better picture of how to get the labels. You will have to extract your own spectrograms, put them in csd format, and then align accordingly (to the labels). There are examples on these steps in the examples folder.

**Comment by KJ-Waller** [comment]
Thanks for your reply. I have been trying to go through the examples, and I am able to better understand how to get the emotion labels. 

However, I am still confused as to how I could get the raw audio waveform in order to extract a spectrogram. The raw data that I get are the words, as the SDK states, rather than the raw audio waveforms that I am looking for. Do I have to download the raw data outside the SDK, align it according to the labels, and then extract them manually into a csd, and then use the SDK again? Or is there a way to get the audio waveforms from the SDK?

**Comment by A2Zadeh** [comment]
@KJ-Waller, yes, the raw data is mostly focused on NLP. For that you need to download the raw data from here: http://immortal.multicomp.cs.cmu.edu/raw_datasets/ more info on this is available in the readme of the SDK. 

There are really two options here: 1) go with SDK and process the CSDs. This is the easier choice if you want to do word alignment or anything of the sort. 2) go outside SDK, where both labels and raw data is available in the above link. Either way, best of luck with your experiments :)
