### ISSUE TITLE
Error with some modalities

### ISSUE THREAD

**Issue by slickster91** [A2Zadeh/CMU-MultimodalSDK#195]
Keeps saying found video not belonging to any split even after having aligned them and removed the segments not in common

![Screenshot (20)](https://user-images.githubusercontent.com/16203388/82601985-39af1880-9b65-11ea-9df0-92c531b6fc39.png)
![Screenshot (21)](https://user-images.githubusercontent.com/16203388/82602056-551a2380-9b65-11ea-9f41-b9d64e4d96cc.png)

**Comment by A2Zadeh** [comment]
@slickster91 SDK should take care of this for you. Did you manually do it? Can you link to your full code?

**Comment by slickster91** [comment]
https://github.com/Justin1904/CMU-MultimodalSDK-Tutorials 
This is basically the code I used and then tried to run it for MOSEI as well. It is made for MOSI originally.

**Comment by A2Zadeh** [comment]
Yeah some modalities have changed since that tutorial was made. Have a look at this code: https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/examples/mmdatasdk_examples/full_examples/process_mosei.py
I just uploaded it.

**Comment by A2Zadeh** [comment]
@slickster91, I am closing this issue for now. If you have any other questions, feel free to ask.
