### ISSUE TITLE
Examining data

### ISSUE THREAD

**Issue by fatirali** [A2Zadeh/CMU-MultimodalSDK#196]
Dear @A2Zadeh ,

I'm having trouble opening and examining the data in Python. Is there a way to view the data/features in a tabular format? 

I want to view, the text, audio and visual data separately. 

Regards,
Fatir.

**Comment by A2Zadeh** [comment]
Hi @fatirali,

Yes there is. I believe the easiest way for that would be through the raw data here: http://immortal.multicomp.cs.cmu.edu/raw_datasets/CMU_MOSI.zip. But as for the SDK usage, have you been able to follow some tutorials in the example folder? There is also a wiki that may be helpful to you.

**Comment by fatirali** [comment]
Thanks Amir.
In using the SDK, I could not understand how to look at the csd files like the OpenSmile data. I can get to the file names but I can't take a look at the feature data in tabular format. 

Does that make sense? 

Regards,
Fatir

**Comment by A2Zadeh** [comment]
@fatirali, the way you can look at them is one id (video) at a time. So you can traverse the csd file for its keys, which will give you all the ids. Then in those ids there are features and intervals. Features are the values you are looking for, and intervals are the intervals for each row of features. Say if sampling rate is 100 (OpenSmile) and then we are looking at a video with 300 seconds. then we are looking at 300 x 100 rows.
