### ISSUE TITLE
RunTimeError when downloading POM

### ISSUE THREAD

**Issue by weberkla** [A2Zadeh/CMU-MultimodalSDK#197]
Hey all, 

I got the following error when downloading the pom dataset: 
![image](https://user-images.githubusercontent.com/28390955/82899302-08ff2280-9f5b-11ea-8e80-9e4d542978eb.png)

I also wanted to ask, if the dataset contains images (or videos) of the respective annotated videos as well?

**Comment by A2Zadeh** [comment]
Hi @weberkla, good catch. I wrote the URL wrong. Pull it again and it should work.
