### ISSUE TITLE
IEMOCAP dataset mapping

### ISSUE THREAD

**Issue by wenliangdai** [A2Zadeh/CMU-MultimodalSDK#200]
Hi~

I download the aligned IEMOCAP dataset from this repo.

There are 2717 / 798 / 938 data samples in train / valid / test sets. The original IEMOCAP data contains 151 sessions of dialogue. 

Could you please explain more about how do you split those dialogue sessions into the processed data? Is it like, for each sequence of continuous utterances with the same emotion, you make them into one data sample? If so, can I assume I cannot get the relations of utterances in a dialogue?

Thanks!

**Comment by A2Zadeh** [comment]
Hi @wenliangdai,

Sadly, we don't provide that. In our experiments when we do the splits based off of sessions, we then discard the ids. Hope this helps.
