### ISSUE TITLE
old dataset

### ISSUE THREAD

**Issue by nanopoteto** [A2Zadeh/CMU-MultimodalSDK#201]
> --> Old preprocessed datasets used in our papers are available at: http://immortal.multicomp.cs.cmu.edu/raw_datasets/old_processed_data/. Still we highly recommend using SDK since you will have access to the latest updates for the datasets.

I want to use the old cmu-mosei dataset but I cannot find it in above link.

**Comment by A2Zadeh** [comment]
@nanopoteto. Ah good catch. The link is this now: http://immortal.multicomp.cs.cmu.edu/raw_datasets/processed_data/

**Comment by nanopoteto** [comment]
Thanks!
@A2Zadeh 

Do you have any links of data that was on http://sorena.multicomp.cs.cmu.edu/downloads/MOSEI?

**Comment by nanopoteto** [comment]
I'm looking for pickled/embeddings.pkl, pickled/facet.pkl, ...pickled/emotions.pkl now.
