### ISSUE TITLE
About Visual Feature

### ISSUE THREAD

**Issue by nanopoteto** [A2Zadeh/CMU-MultimodalSDK#202]
I have a question about cmu-mosei dataset.
How did you extract 35 dimensional visual features (CMU_MOSEI_VisualFacet42) ?

I want to know what are in this features.

Thanks,

**Comment by A2Zadeh** [comment]
Hi @nanopoteto, that information is in the metadata of the csd. Also, if you download the raw data you will be able to see the dimensions. Let me know if you wanted me to take a look also.
