### ISSUE TITLE
How to save the aligned data? 

### ISSUE THREAD

**Issue by yxxxxxxxx** [A2Zadeh/CMU-MultimodalSDK#204]
Hi, I'm using your SDK to process my own train data. Since my data is quite large, I want to align the data first and save the aligned data so I only need to read it next time, I'd like to know if your SDK support saving the aligned data as a file? Thank you for your reply!

**Comment by A2Zadeh** [comment]
Hi @yxxxxxxxx,

Yes, you can call the deploy to store it. Please refer to the example here: https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/examples/mmdatasdk_examples/full_examples/process_mosi.py

**Comment by yxxxxxxxx** [comment]
> Hi @yxxxxxxxx,
> 
> Yes, you can call the deploy to store it. Please refer to the example here: https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/examples/mmdatasdk_examples/full_examples/process_mosi.py

Thank you for your reply!

**Comment by A2Zadeh** [comment]
@yxxxxxxxx happy to help!
