### ISSUE TITLE
Using TFN without SDK

### ISSUE THREAD

**Issue by fatirali** [A2Zadeh/CMU-MultimodalSDK#205]
Dear @A2Zadeh (Amir),

Is there anyway to use the Tensor Fusion Network without the SDK? 

I used the raw dataset and run a bunch of experiments on it. Now I'm aiming to copy the results of the TFN models.

**Comment by A2Zadeh** [comment]
Hi @fatirali. Yeah, I think the TFN github can help with that: https://github.com/Justin1904/TensorFusionNetworks

Let me know if there was anything I missed.

**Comment by fatirali** [comment]
Thank @A2Zadeh ,

I was unable to crack it :( Is there any way I can read up on the inner working of the TFN so I can recreate it myself?

**Comment by A2Zadeh** [comment]
Hi @fatirali 

Sorry to hear that. Does the TFN in the mmmodelsdk in this github help you? It is a differentiable pytorch nnmodule.
