### ISSUE TITLE
fusion module

### ISSUE THREAD

**Issue by goktugyildirim** [A2Zadeh/CMU-MultimodalSDK#206]
When I try to **from mmsdk import mmdatasdk**, I faced with **No module named 'fusion'**. How can I find this package? I could not download with pip install fusion.

**Comment by A2Zadeh** [comment]
Hi @goktugyildirim,

Is this with the newest version of the sdk? Can you pull again and let me know if you are facing this issue. Thanks.

**Comment by simpleoier** [comment]
Hey, I met the same problem. Then I solved this by modifying the `import` statements in `mmmodelsdk` package.
For example, modifile the `import` statement in [mmmodelsdk](https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/fd18d71dc26b4d834480306c2ce1a903b8a8ff70/mmsdk/mmmodelsdk/__init__.py#L1) following [mmdatasdk](https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/fd18d71dc26b4d834480306c2ce1a903b8a8ff70/mmsdk/mmdatasdk/__init__.py#L1), as:
```python
import mmsdk.mmmodelsdk.fusion as fusion
```
