### ISSUE TITLE
Some questions about POM dataset

### ISSUE THREAD

**Issue by Subohao** [A2Zadeh/CMU-MultimodalSDK#207]
Hi, 
Dear @A2Zadeh 
Sorry to bother you, 
I'm doing some experiment and research on the POM dataset now.
After I reading the paper  "Computational Analysis of Persuasiveness in Social Multimedia: A Novel Dataset and Multimodal Prediction Approach", I know almost all the settings of POM.
However, I get a additional label of "video level sentiment" from sdk service, I want to know what is this sentiment score?
I can not find the description from the conference paper.
Is it the emotion of the movie reviewer or it's  the emotion feeling of the annotator?
Please help me with these questions in detail if possible.
If you have other reference paper mentioning about this part, please feel free to let me know.
Thank you very much and sorry to occupy your time.

**Comment by Subohao** [comment]
Could anyone help me with this problem?

**Comment by A2Zadeh** [comment]
Hello @Subohao. No worries, happy to help. The sentiment is a score which demonstrates an attitude towards a particular topic. Say someone says "I liked this movie" => positive sentiment. Or "I hated the ad" => negative. In POM, it is the sentiment expressed by the speaker, not the viewer. For example, you as the viewer may have hated a movie but the speaker loved it, then the sentiment is still positive. The main paper I would suggest is the CMU-MOSI dataset paper.
