### ISSUE TITLE
MOSI dataset

### ISSUE THREAD

**Issue by Hughheyu** [A2Zadeh/CMU-MultimodalSDK#209]
Hello, I'm really interest in your research. However I can't find the dataset, such as glove_300_mosi.pkl and so on. Could you please tell me how I can find them? Thanks a lot. Look forward to your reply.

**Comment by A2Zadeh** [comment]
Hi @Hughheyu. Thanks for your interest in my research. You can find the information you are looking for here: http://immortal.multicomp.cs.cmu.edu/raw_datasets/processed_data/cmu-mosi/

**Comment by Hughheyu** [comment]
Thank you very much for your reply. However, in the link you provided, I only find some h5 files and other pkl files, but still can't find the files I need to run py files, such as&nbsp;word2ix_300_mosi.pkl, glove_300_mosi.pkl and so on.&nbsp;The creator of the py file tells us that we can find the dataset in this link.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Amir Zadeh"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月1日(星期三) 上午10:52
收件人:&nbsp;"A2Zadeh/CMU-MultimodalSDK"<CMU-MultimodalSDK@noreply.github.com&gt;;
抄送:&nbsp;"郑和裕"<386722885@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [A2Zadeh/CMU-MultimodalSDK] MOSI dataset (#209)





 
Hi @Hughheyu. Thanks for your interest in my research. You can find the information you are looking for here: http://immortal.multicomp.cs.cmu.edu/raw_datasets/processed_data/cmu-mosi/

**Comment by A2Zadeh** [comment]
@Hughheyu Interesting. Where is the py file? Is it one of our projects?

**Comment by Hughheyu** [comment]
Yes. The py files are come from your projects, which the link is:&nbsp;https://github.com/pliang279/factorized.git. I tried to run the test_mosi.py and the data_loader.py but I failed. Could you please give me some advice on how to run these py files?
(By the way, the Scripts in the README said that "Please run python mfm_test_mosi.py", but I only found the test_mosi.py. Are they the same?)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Amir Zadeh"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月2日(星期四) 凌晨2:02
收件人:&nbsp;"A2Zadeh/CMU-MultimodalSDK"<CMU-MultimodalSDK@noreply.github.com&gt;;
抄送:&nbsp;"郑和裕"<386722885@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [A2Zadeh/CMU-MultimodalSDK] MOSI dataset (#209)





 
@Hughheyu Interesting. Where is the py file? Is it one of our projects?

**Comment by ky941122** [comment]
> http://immortal.multicomp.cs.cmu.edu/raw_datasets/processed_data/cmu-mosi/

@A2Zadeh Hi, in your [Factorized-Multimodal-Transformer](https://github.com/A2Zadeh/Factorized-Multimodal-Transformer) code, how to set the dim_l, dim_a, dim_v and padding_len for the seq_len_20 mosi data.
