### ISSUE TITLE
Labels for MOSEI dataset

### ISSUE THREAD

**Issue by padisarala** [A2Zadeh/CMU-MultimodalSDK#210]
HI,
           I am in a process of analysing the CMU-MOSEI dataset for multimodal emotion recognition task. Unfortunately, we were not able to process the labels for the files. could you please upload labels file in csv format.
THank you

**Comment by A2Zadeh** [comment]
@padisarala I responded to this thread in another one. I tagged you. Hope it helps. Let me know if your question persists.

**Comment by padisarala** [comment]
Yes. I downloaded the raw dataset and I do find mturk_extra_v2.csv file. But this file has only 10K entries whereas segmented video folder has 39K files. I have not found the corresponding labels for segmented video files. I also noticed that the mturk_extra_v2.csv file has a column with name Title which says MOSI2 video annotation. I wont think is this the right label file for MOSEI dataset. Could you point me the right file.Thank you so much
