### ISSUE TITLE
Missing raw text transcripts for uploaded MOSEI dataset

### ISSUE THREAD

**Issue by anita-hu** [A2Zadeh/CMU-MultimodalSDK#213]
@A2Zadeh Thanks for providing the raw text zip, I am trying to generate BERT features to match with the audio and visual features. I noticed they were missing some txt files. 347 video ids for the train fold, 35 for the valid, and 103 for test (folds from cmu_mosei_std_folds.py). I was wondering if you can provide the missing files. Thank you!
 
Examples of video ids missing for the train fold: 
'hh04W3xXa5s', '72tXTrSXoMk',  'YVHJpAROBvQ', '-iRBcNs9oI8', 'gZF-YNQHqwI', 'Z3fcd1wdzr0', '6TKaGMkO69E', 'ogGweZUAVtU', '254298', 'RadU51t1kL0', 'iREkcXde5ds', 'k1ca_xbhohk', 'dqragS38hCk', 'PohW-isYMK0', '0vXaXWx7Rvo', 'kf3fZcx8nIo', 'Sir2QeCh4B0', 'UK_IXtJ2BqI'

_Originally posted by @anita-hu in https://github.com/A2Zadeh/CMU-MultimodalSDK/issues/157#issuecomment-656451268_

**Comment by A2Zadeh** [comment]
Hi @anita-hu, this is interesting. Where are you getting the raw data from? From comp sequences or the raw file? I assume the latter. Can you tell me how many files in total you are seeing in the transcription folder? should be 3837.

**Comment by anita-hu** [comment]
I am getting the raw transcripts from http://immortal.multicomp.cs.cmu.edu/cache/TRS_MOSEI.zip

In the Segmented/Combined folder there are 3303 files

**Comment by A2Zadeh** [comment]
@anita-hu Ah ok. It seems you got it from the wrong place. Here is my suggestions:

1. Download the raw words computational sequence.
2. Align them to labels. Don't collapse them. 
3. Get the words in every sentence, pass them to BERT every epoch (if you are finetuning BERT). Otherwise, you can just get the embeddings. 

Otherwise, if you run BERT on the entire video, your results may not be comparable to others (since you use more context than other models).

**Comment by anita-hu** [comment]
Just for clarification, the raw words is referring to http://immortal.multicomp.cs.cmu.edu/CMU-MOSEI/language/CMU_MOSEI_TimestampedWords.csd

Thanks!

**Comment by anita-hu** [comment]
@A2Zadeh When looking at the transcripts, I noticed some have 'sp', should these be removed or just leave as is?

Example: ['writer', 'sp', 'i', 'see', 'that', 'a', 'writer', 'is',
       'somebody', 'who', 'has', 'an', 'incredible', 'command', 'of',
       'mechanics', 'sp', 'of', 'the', 'english', 'language', 'sp']

**Comment by A2Zadeh** [comment]
@anita-hu, correct that is the right csd. 

sp is "speech pause".
