### ISSUE TITLE
http://multicomp.cs.cmu.edu/acl2020multimodalworkshop/   Broadcasting link

### ISSUE THREAD

**Issue by AnilRahate** [A2Zadeh/CMU-MultimodalSDK#214]
Hi Amir,
Apologies for posting this query as an issue. It is mentioned that ACL2020 is on 10th July and remote broadcasting link will be  published. However it is yet not published and workshop is supposed to start in 2 hours.

Can you please help.

Regards,
Anil

**Comment by A2Zadeh** [comment]
Hello @AnilRahate,

ACL does not allow us to share the zoom link, sadly. You can access the ACL wroskhop via ACL live platform, if you are registered. If not, we plan to publish the proceedings on YouTube in week or so.

**Comment by A2Zadeh** [comment]
People seem to be in the zoom link also, so I don't see why you can't be either. The link is: https://zoom.us/j/93889043395?pwd=SWIxNWN4WElmakRFVFlpSG5EWlVYQT09
