### ISSUE TITLE
Help to create alignment between frames & audio samples

### ISSUE THREAD

**Issue by AnilRahate** [A2Zadeh/CMU-MultimodalSDK#215]
Hi Amir,
I have downloaded raw MOSI dataset, I see audio, video, text for each sequence based on OpinionLevelSentiment.csv file provided. I want to try basic model of with 3 unimode models and concatenate those at some layer before output. I want to use CNN by splitting video sequences into frames, use CNN by splitting audio files into chunks and LSTM/CNN on text. Can you please point me to any code example for this. I am not able to think relation between frame rate and audio sampling so that there is an alignment to have same labels across. Thanks a lot in advance.

**Comment by A2Zadeh** [comment]
Hi @AnilRahate. Sure, I can definitely help with that. Just to fully understand, are you planning to do word alignment? The code for aligning CMU-MOSI is here: https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/examples/mmdatasdk_examples/full_examples/process_mosi.py

This stores the aligned dataset for you, which you can directly use as input to say LSTM-CNN.

**Comment by 201528014227051** [comment]
hi, @AnilRahate i cannot find file OpinionLevelSentiment.csv for MOSI , and the corresponding from file names to ids in the processed data @A2Zadeh , could you help me ? GRATEFUL TO U
