### ISSUE TITLE
About co-learning

### ISSUE THREAD

**Issue by vandana-rajan** [A2Zadeh/CMU-MultimodalSDK#216]
Hi Amir Zhadeh,

This is not an issue with this repository, rather a query regarding your recent paper.

I read your recently published journal paper on multi-modal co-learning. I have a doubt regarding this paper.

In this paper, you have investigated the pros of mm co-learning compared to uni-modal learning by using language as the primary modality. I assume that in the datasets used for the experiments, language is the stronger modality compared to audio and vision. Did you try using audio and video as source modalities? My doubt is that, if a weaker modality is chosen as source modality, is there performance improvement with multi-modal training compared to the case when only the weaker modality is used for both training and testing?

Thanks,
VR

**Comment by A2Zadeh** [comment]
Hi @vandana-rajan. That is a great question. There are two faces with this paper, as with any other theoretical/empirical paper. The first face demonstrates that theoretically, it is possible for ANY modality to learn mappings to other modalities and do better downstream. Empirically, this is more challenging. I don't believe we tried other modalities, since the paper was mostly written from the standpoint of language acquisition. But certainly worth trying out, since the theory says such a mapping should be possible. Note, the final version of the paper is being uploaded soon, with small tweaks to the proofs to make them more understandable.

**Comment by vandana-rajan** [comment]
Thanks for the response. Looking forward to read the final version of the paper :)

**Comment by vandana-rajan** [comment]
Hi Amir,

Sorry. I have one more question about the paper.

You have used a language-only version of MFN to compare with the multimodal MFN. So, the language only version (unimodal training and unimodal testing) is a single LSTM model without the delta memory module and the gated multi-view memory? Also, in multimodal MFN during test time, what were the inputs to the other modalities? Were they zero? 

Apologies if I somehow missed this information from the paper.

Thanks,
VR

**Comment by A2Zadeh** [comment]
Hi @vandana-rajan. Glad my response helped.

Happy to answer your question. No, that would not be fair. What we do is multiply visual and acoustic with zeros and use the same network again. We realized MFN is better than just using LSTM, even if we only have language. Yes, they were zeros. One could argue that using zeros here is not the best thing to do. But even with suboptimal imputations, co-learning seemed to be working. 

Let me know if you had other questions.

**Comment by vandana-rajan** [comment]
So, just to make sure that my understanding is correct; 

1. For unimodal training and unimodal testing framework using MFN, you gave {language_features, zero_array, zero_array} for training, validation and testing.

2. For multimodal training and unimodal testing framework using MFN, you gave {language_features, audio_features, video_features} as input for training and {language_features, zero_array, zero_array} for validation and testing.

Could you kindly confirm if that is correct?

And a big thanks for the quick response :) 

Thanks,
VR

**Comment by A2Zadeh** [comment]
@vandana-rajan The zero was at input level, and your explanation is correct! Let me know if you had other questions.

**Comment by vandana-rajan** [comment]
I see. 

I took the code https://github.com/pliang279/MFN/blob/master/test_mosi.py and did a comparison between UTAT (Unimodal Training and Testing) and MTAT (Multimodal Training and Testing) using MFN with [300,5,20] features.

Out of the 323 different configurations tried, for language modality, MTAT fared better than UTAT 177 times. For video and audio, the corresponding numbers were 116 and 10 respectively.

Thus, MTAT is better than UTAT for language modality for 54.8 % (177/323) of configurations. Can the poor performance of video and audio in co-learning be attributed to their smaller feature dimensions? What were the features with which you did your experiments? Were they the same as the ones used in the code https://github.com/pliang279/MFN/blob/master/test_mosi.py ?

Thanks,
VR

**Comment by A2Zadeh** [comment]
@vandana-rajan Great experiment! Thanks for doing that.

My guess is 2 things: first one is a fundamental difference between the modalities and second is more empirical.

1. Let's consider the mapping between the language and vision. A smile may be mapped to many words, whereas a word like happy can be mapped to a smile. What I am trying to say here is the ambiguity of mapping is a natural parameter. This ambiguity will most likely cause an issue down the road for the success of co-learning (for that particular modality that suffers from this)

2. That the modalities of v and a are not strong enough to learn the mappings. The co-learning paper proves that co-learning can happen, but will it happen is up to empirical results. So let's say you have 100 runs of language and you get 50 of them having co-learned information from v and a. The other 50 may simply learn the UTAT. 

If you are interested in further studying this phenomena, you can get in touch with me over email and we can set up a zoom/skype talk.

**Comment by vandana-rajan** [comment]
That is very kind of you. 
Yes, I am interested in this topic and I have sent you an email (to your CMU email-id).
