### ISSUE TITLE
A problem in MOSI Raw data

### ISSUE THREAD

**Issue by stdoo** [A2Zadeh/CMU-MultimodalSDK#217]
Hi, I have downloaded the raw data of MOSI dataset, there is a problem in video 'c5xsKMxpXnc.mp4'. I can't open it with any video player, while the other videos can be opened normally. Could you check this video in the raw data? The path is :

_Raw/Video/Full/c5xsKMxpXnc.mp4_

Thanks a lot.

**Comment by A2Zadeh** [comment]
Hi @stdoo. Yeah, sadly that one has gotten corrupt. I will have a look at this to see if I can find an alternate anywhere else. In the meantime, someone has posted its sentence on YouTube: https://www.youtube.com/watch?v=cPji9b9AhMg&list=PLvpoSbR5h3yBcajzKwvS12gy3vlC1vv6B

**Comment by stdoo** [comment]
Thanks a lot.

**Comment by A2Zadeh** [comment]
Hi @stdoo. Of course.
