### ISSUE TITLE
raw text can not align the preprocessed text data

### ISSUE THREAD

**Issue by cm-xcju** [A2Zadeh/CMU-MultimodalSDK#219]
I use the the code you  provided to get the aligned data and want to get the raw text data simultaneously. However, I found that the aligned data can not correspond to the raw text data. The sequence length of  preprocessed text data in the aligned data is no t the same as the number of words in the raw text data.I do not understand why this is even though I have checked a lot about the data.

**Comment by A2Zadeh** [comment]
Hi @cm-xcju. This is due to the fact that we have paddings for the sequences. So if something is length 10, and our target is to have 25 words per sentence, then we simply pad with zeros. Does this answer your question?

**Comment by MANLP-suda** [comment]
I have founed the reason. Text information containes some our other words(such as 'SP'),increasing the length of the text dialogue. Thank you for your reply.

**Comment by A2Zadeh** [comment]
Yes, "Speech Pause" is usually the culprit I found :)
