### ISSUE TITLE
Weighted accuracy calculation for emotion labels on CMU-MOSEI

### ISSUE THREAD

**Issue by tungnt55** [A2Zadeh/CMU-MultimodalSDK#220]
Hi, I would like to know how did you calculate the weighted accuracy for emotion recognition on the MOSEI dataset?  
In the CMU-MOSEI paper, it is mentioned "we use weighted accuracy (Tong et al., 2017)". However, the paper by Tong et al. only gives formula for calculating 2-class weighted accuracy while the emotion labels in CMU-MOSEI is 4-class.

**Comment by A2Zadeh** [comment]
Hi @tungnt55. The dataset actually has 4 classes, but we do binary in the experiments with Graph-MFN. The criteria for the emotion is >0 being equal to present and =0 being equal to absent.

**Comment by tungnt55** [comment]
Hi @A2Zadeh , thank you very much for the answer.   
Could you by the way give me the exact script you used to calculate the scores?  
I'm trying to reproduce the results of your paper at ACL 2018 here: https://www.aclweb.org/anthology/P18-1208.pdf  
For the sentiment analysis task, I got the binary accuracy, MAE, and correlation similar as reported. However, my 5-class and 7-class score somehow are much lower.  
In my script, I use the binarization here:  
https://github.com/A2Zadeh/CMU-MultimodalSDK/tree/master/mmsdk/mmdatasdk/dataset/standard_datasets/CMU_MOSEI  
However, I feel something is not right.  According to the code in this link, the class 0 will almost never be predicted correctly since it requires the predicted sentiment value to be exactly 0.

**Comment by A2Zadeh** [comment]
Hi @tungnt55,

Hubert Tsai has created a beautiful script for the calculations here: https://github.com/yaohungt/Multimodal-Transformer

As for the measures, I only care about MAE and Correlation. Remember, these accuracy calculations are not scientifically studied (no one knows higher than what value is perceived as positive vs neutral). It just makes understanding the values easier. The sentiment does sometimes tend to be exactly 0, and that is what we use. Let me know if this issue persists.

**Comment by tungnt55** [comment]
Hi @A2Zadeh . Thank you again for giving me the link of the script and the explanation about the performance metrics.  
Everything is working as expected now. I will close this issue.

**Comment by A2Zadeh** [comment]
@tungnt55 Perfect! Good luck with your experiments.
