### ISSUE TITLE
Where is raw audio of CMU-MOSEI

### ISSUE THREAD

**Issue by yuzhms** [A2Zadeh/CMU-MultimodalSDK#221]
I would like to use the raw audio of CMU-MOSEI to do sentiment classification. However it seems the SDK only provide 'COVAREP' features.

I tried to find it in the `raw_data` (http://immortal.multicomp.cs.cmu.edu/raw_datasets/processed_data/cmu-mosei/seq_length_20/data/), but the file size seems to be too small. 

Also, I'm confused about the files in the label directory (http://immortal.multicomp.cs.cmu.edu/raw_datasets/processed_data/cmu-mosei/seq_length_20/labels/). Could you dscribe the format of these files?

Thank you for your help.

**Comment by A2Zadeh** [comment]
Hi @yuzhms. You should be able to download the full dataset here and get the audio files: http://immortal.multicomp.cs.cmu.edu/raw_datasets/CMU_MOSEI.zip

Let me know if this helps.
