### ISSUE TITLE
Aligned & unaligned sequences of CMU-MOSEI

### ISSUE THREAD

**Issue by showgood163** [A2Zadeh/CMU-MultimodalSDK#223]
Hi there!

I'm compiling compute sequences of CMU-MOSEI using the latest version of this SDK.

Using [process_mosei.py](https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/examples/mmdatasdk_examples/full_examples/process_mosei.py) in this repo, I got 22860 (16327+1871+4662) aligned sequences.
Then I removed line 29 and 31, I got 22852(16322+1871+4659) unaligned sequences.

The questions are:
1. Is this way of getting unaligned sequences recommanded?
2. Why do I get different number of sequences under different conditions?

Thanks!

**Comment by A2Zadeh** [comment]
Hi @showgood163 

Line 31 is particularly important in taking care of the cases where the word is present but other detectors have failed. For example, a whole part of a video may be missing in COVAREP, and hence imputation helps with getting those back. My suggestion is to keep the line 31, but impute to the labels. Then you should get 22860 for that as well.

**Comment by showgood163** [comment]
Thank you for the advice! I will report back after I try it.

**Comment by showgood163** [comment]
Yes. It works. Thanks!

**Comment by A2Zadeh** [comment]
@showgood163 Great. Good luck with your experiments.
