### ISSUE TITLE
Help to understand "CMU-MOSEI csv file"

### ISSUE THREAD

**Issue by HarukaNakase** [A2Zadeh/CMU-MultimodalSDK#224]
Dear Sir ZADEH,

I downloaded CMU-MOSEI csv file "mosi2uni_Test.csv" from http://immortal.multicomp.cs.cmu.edu/raw_datasets/processed_data/cmu-mosei/seq_length_20/labels/

I could not understand the contents of the csv file. 
Is this text vector data? , acoustic data? , facial data?, or all ?
And, what does it mean "409, 20" at the first line?

Thank you.

**Comment by e-remington-lee** [comment]
I am also curious about this!

**Comment by A2Zadeh** [comment]
Hi everyone,

That's the original features for the MOSEI dataset. To be more up to date on your papers, probably better to use the newest set of features from MulT @ ACL19. The set is here: http://immortal.multicomp.cs.cmu.edu/raw_datasets/processed_data/cmu-mosei/seq_length_50/

You can then cut the sequence to 20 if you are interested in the length 20.

**Comment by AnilRahate** [comment]
Hi @A2Zadeh,

I found that this set of seq_length_50 is not having emotions labels. Will seq_length_20 dataset have same size and order so that I can use data of seq_length_50 & emotion labels of  seq_length_20.
