### ISSUE TITLE
About CMU_MOSEI_Labels.csd

### ISSUE THREAD

**Issue by chayan-dhaddha** [A2Zadeh/CMU-MultimodalSDK#226]
What modifications are done in label file "CMU_MOSEI_Labels.csd" [http://immortal.multicomp.cs.cmu.edu/CMU-MOSEI/labels/] file compared to its older version(CMU_MOSEI_ALL_Labels.csd) since the earlier is 22MB and later is 6.5MB ?
because for both, I am getting 3293 dict keys and label vector for 23259 segmented files. And I am not able to figure the difference.
@A2Zadeh
Thanks in advance

**Comment by A2Zadeh** [comment]
@chayan-dhaddha We are doing compression to make the dataset smaller :). The values remain the same, just compressed for fast web transfer.
