### ISSUE TITLE
Feature extraction from MOSI RAW DATA

### ISSUE THREAD

**Issue by silentghoul-spec** [A2Zadeh/CMU-MultimodalSDK#228]
Hi, how can I use certain MOSI raw test videos segments and then preprocess them to convert each modality into vectors so that I can see what was the original video was and what is my final model predicted sentiment? I just want to analyse a few outputs. I know how to use already given vectors in .csd files, but struggling to get my own vectors for raw test video segments.

**Comment by silentghoul-spec** [comment]
I got it. Thanks for examples section :)

**Comment by taylor4712** [comment]
how did you do it?
