### ISSUE TITLE
YouTube raw text file aligned with extracted features.

### ISSUE THREAD

**Issue by DushyantChauhan** [A2Zadeh/CMU-MultimodalSDK#229]
Hello,

I was working on YouTube dataset and I used features as you given here. But there is a problem that I got only features not the aligned raw files. 

Can you please give the raw text file aligned with extracted features? That will be very helpful.

Thank you.

**Comment by DushyantChauhan** [comment]
You can provide any of your dataset's transcript aligned with extracted features i.e., MOSI or YouTube or POM or MMMO etc.

**Comment by A2Zadeh** [comment]
Hi there @DushyantChauhan,

I am not sure if I understood correctly, perhaps you could help. Are you looking for raw or processed features? And for YouTube dataset?

**Comment by DushyantChauhan** [comment]
Hello,

Actually, processed features are there on-site but no raw data sync with
these processed features. For error analysis, I need raw data so that I can
do some study about my proposed model.



Regards,
Dushyant Singh Chauhan
-------------------------------------------------------------
PhD Scholar, Dept. of CSE,
Indian Institute of Technology, Patna,
Ph: +91-9720162666
Work-email: 1821cs17@iitp.ac.in
Alternate-email: dushyantchauhan27@gmail.com
Skype: 9720162666

**Comment by A2Zadeh** [comment]
@DushyantChauhan the raw data is there on the server, it is called raw_datasets: http://immortal.multicomp.cs.cmu.edu/raw_datasets/
