### ISSUE TITLE
alignment word frames audio samples

### ISSUE THREAD

**Issue by AnilRahate** [A2Zadeh/CMU-MultimodalSDK#230]
Thanks a lot Amir. I would like to know what was sampling rate/frames for audio processing. 
I am still struggling understand how to find number of video frames/audio samples corresponding to each word in a sentence. Is interval of each word obtained using P2FA and then corresponding frames aligned. Once frames are aligned, audio (74) and video features (47) extracted and averaged for a word. I think, since there is word level alignment, it does not matter if padding is applied at the end of feature vector to obtain length of 40 as shown in tutorial.

Thanks a lot for your response, really appreciate your efforts which are helping us to grasp multimodal domain.

Again creating new issue as I am not sure if comment on closed issue comes to your notice. 

_Originally posted by @AnilRahate in https://github.com/A2Zadeh/CMU-MultimodalSDK/issues/225#issuecomment-687995219_

**Comment by A2Zadeh** [comment]
Hi @AnilRahate,

You are correct. The word alignment is usually done that way. However, it can also be done in other ways using the SDK. 

The padding is applied only if a sentence is say 10 words but the reference is say 50 words. Then we need to pad by 40 zeros.
