### ISSUE TITLE
Update MOSEI

### ISSUE THREAD

**Issue by PierreColombo** [A2Zadeh/CMU-MultimodalSDK#231]
Hello Thanks for your work,
Downloading the mosei label seems broken?

DATASET.labels = {'All Labels': 'http://immortal.multicomp.cs.cmu.edu/CMU-MOSEI/labels/CMU_MOSEI_Labels.csd'} 

Do you confirm those are the right labels?
Thanks for your work :)

**Comment by A2Zadeh** [comment]
Hi @PierreColombo. Of course, glad you find it useful. 

It seems the link is actually working. Would you be able to share the error message?

**Comment by PierreColombo** [comment]
CMU-MultimodalSDK/mmsdk/mmdatasdk/dataset/standard_datasets/CMU_MOSEI/cmu_mosei.py /
 I guess there is a missmatch in the url? what is the difference between All labels and labels ?

**Comment by A2Zadeh** [comment]
@PierreColombo You are right! The py file was linking to a previous edition of the labels. It has now been fixed. You can pull the SDK again and it should work.
