### ISSUE TITLE
MOSEI labels like MOSI

### ISSUE THREAD

**Issue by AnilRahate** [A2Zadeh/CMU-MultimodalSDK#232]
Hi Amir,
I have downloaded raw MOSEI dataset. It contains folder labels but those looks raw as each video segment have multiple emotion labels. Would like to know if you have final labels matching segmented videos & audios. The way, "OpinionLevelSentiment.csv" file is shared for MOSI dataset.

Thanks a lot for your team's work, it is huge dataset.

**Comment by A2Zadeh** [comment]
Hi @AnilRahate. That information is in the labels computational sequence. It has the timestamps as well as the labels themselves.
