### ISSUE TITLE
Details about the features

### ISSUE THREAD

**Issue by vandana-rajan** [A2Zadeh/CMU-MultimodalSDK#233]
Hi,

Could you please tell me where I can find more details about the features extracted? For example, what is the difference between FACET_4.1 and FACET_4.2 features? Should I concatenate them or how can I choose one out of these 2? Similarly for OpenFace_1 and OpenFace_2 features.

**Comment by AnilRahate** [comment]
Hi Amir,
Even I also same query. In the tutorial provided by Justin, he has included only MU_MOSI_VisualFacet_4.1 (41). Please let us know.

Thanks in advance.

**Comment by Alicegaz** [comment]
Hello,  @A2Zadeh! Could you please add either to Wiki, or README a detailed description of the provided acoustic features? Also, spectrogram visualizations would be helpful to understand the quality and get some insights about the data. 
I was trying to visualize features, however not knowing what are the features in each of the axes made it hard to succeed with this) 
Thank you!

**Comment by A2Zadeh** [comment]
Hello @vandana-rajan, @AnilRahate , @Alicegaz,

Apologies for the late reply, been a busy two weeks. 

We include old versions of the features for reproducibility reasons and new versions for keeping up with the newest detectors. Naturally, as time goes by, detectors like OpenFace get better and better. We don't wanna be outdated but we also want to give access to old features so reproduction of old papers is easy. If you are working on a new paper, my suggestion is you use the newest set of features, and rerun the baselines using the newest ones. Alternatively, you could use the old features and avoid running the baselines again.  

Alice, the information on feature dimensions is a part of the metadata for our datasets. You can easily get the information by getting the "dimension names" key of the computational sequence metadata. So say your dataset is x and your computational sequence is y, that would be `x.y.metadata["dimension names"]`. It is a json string with the dimension names.

**Comment by vandana-rajan** [comment]
Thanks for the clarification.

One more question. 

Some papers (old and recent) are using the CMU MOSI data from https://github.com/declare-lab/contextual-utterance-level-multimodal-sentiment-analysis instead of the SDK. The feature dimensions there are (100, 73, 100) for (text, audio, video). Do you know how this data is different from the one offered in the SDK?

**Comment by AnilRahate** [comment]
yes, Vandana, as per my reading of papers from Soujanya's group that is different. For visual, they used convolution techniques to extract.

**Comment by vandana-rajan** [comment]
Yes. I noticed that in their papers. However, what I am not sure is if the data partitioning is the same as in SDK and also if those features are aligned or not. I am not sure that it is fair to compare the results of 2 models that use different data partitions, even if the dataset is the same.

**Comment by A2Zadeh** [comment]
@vandana-rajan @AnilRahate,

Folks, that particular paper uses the exact same folds as the SDK. In fact the folds are done by Soujanya in a paper before that one at ACL17. There is no word alignment in the paper you linked. 

Anil is right about the visual features.

**Comment by vandana-rajan** [comment]
@A2Zadeh @AnilRahate Thanks for the useful info.

**Comment by A2Zadeh** [comment]
@vandana-rajan happy to help!
