### ISSUE TITLE
Error While trying run Align on MOSEI

### ISSUE THREAD

**Issue by abhinav777** [A2Zadeh/CMU-MultimodalSDK#234]
Hi, 

I encountered this error:

```
[1]    80690 killed     python3
/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

While trying to run the following command:

`cmumosei_highlevel.align('All Labels')`

Before I got that message, this is the log I had received:

```
[2020-09-26 19:03:28.004] | Success | Unify completed ...
[2020-09-26 19:03:28.004] | Status  | Pre-alignment based on <All Labels> computational sequence started ...
[2020-09-26 19:03:55.209] | Status  | Pre-alignment done for <glove_vectors> ...
[2020-09-26 19:10:06.725] | Status  | Pre-alignment done for <OpenFace_2> ...
```

And these are the previous commands I had run:

```
cmumosei_highlevel=mmdatasdk.mmdataset(mmdatasdk.cmu_mosei.highlevel,'cmumosei/')
cmumosei_highlevel.add_computational_sequences(mmdatasdk.cmu_mosei.labels,'cmumosei/')
```

Have you experienced something like this before? Or in case I might be going wrong somewhere setting this up?

Thank you very much

**Comment by A2Zadeh** [comment]
Hi @abhinav777,

This is most likely due to not enough RAM, though it's a very weird message for it. I suggest increasing your swap space to at least 128GB to accommodate this. Alternatively, you can use the pre-aligned version which has the outcome of the alignment stored: http://immortal.multicomp.cs.cmu.edu/ACL20Challenge/

**Comment by abhinav777** [comment]
Thank you so much for that :) I did not realize that I need that large swap memory.
