### ISSUE TITLE
MOSI Dataset- Tensor Fusion Network Paper - Sentiment Score Categorisation 

### ISSUE THREAD

**Issue by AnilRahate** [A2Zadeh/CMU-MultimodalSDK#236]
Hi Amir,

I want to clarify on below:
1. How sentiment values were categorised into 5 classes or 7 classes like - for example Neutral having range from -0.5 to 0.5 or just 0. If I take 0 as neutral I am not getting distribution on 2199 samples showed in figure 2 of a paper. I referred "OpinionLevelSentiment.csv" shared along with raw MOSI data for sentiment values. 

Thanks in advance for al your help.

**Comment by A2Zadeh** [comment]
Hi @AnilRahate,

They are done based on the round function. For 5 class, we clamp anything higher than 2 and lower than -2 to 2 and -2. 

The original paper does sentiment classification as positive vs non-positive. More recent works remove the 0s. Let me know if you have other questions.
