### ISSUE TITLE
Access to private Test set

### ISSUE THREAD

**Issue by PierreColombo** [A2Zadeh/CMU-MultimodalSDK#237]
Hello,
Thanks for your work :)
The private test set of the ACL challenge requires a password. Would it be possible to obtain it ?
Thanks

**Comment by A2Zadeh** [comment]
Hi @PierreColombo,

We will release that information on December 1st, so all the challenge participants can have access in a fair way. Are you working on this for the next challenge or for a different paper?

**Comment by PierreColombo** [comment]
Hi :),
It would be for a paper at NAACL or ACL. We are not working on the challenge ! :)
Thanks a lot

**Comment by A2Zadeh** [comment]
@PierreColombo would you consider using the original test set :)? I was hoping to use the same data for the new challenge. Alternatively, I can share with you but you cannot share with anyone else.

**Comment by PierreColombo** [comment]
Sure :) i did not see the length of 20 ^^. We will work on this one. However we have an issue with the classification labels.
