### ISSUE TITLE
Tensor Fusion Results 

### ISSUE THREAD

**Issue by AnilRahate** [A2Zadeh/CMU-MultimodalSDK#238]
Hi Amir,

I am trying to reproduce results of tensor fusion paper following yours as well as Justin's reference code. However I am not able to see improvement in MAE & other metrics using Tensor fusion on MOSI dataset. I used data by extracting as shown in tutorial (20 Sequence length, 300 dim embeddings, 74 covarep, 47 Facet). Even I tried with data provided in .h5 file format with 325 dimension. I tried trimodal as well as bimodal. My TFN results are always equal or higher than text modality but no improvement.  Any specific things, we need to take care based on your or Justin experience. 

Thanks  in advance for all your support.

Regards,
Anil Rahate

**Comment by A2Zadeh** [comment]
Hi @AnilRahate,

This is odd. Did you try Justin's code? Please note that TFN results are done with feature selection, at least the ones reported the in the paper. The original data is here: http://immortal.multicomp.cs.cmu.edu/raw_datasets/processed_data/cmu-mosi/seq_length_20/

**Comment by A2Zadeh** [comment]
You may wanna look at this too: http://immortal.multicomp.cs.cmu.edu/raw_datasets/processed_data/cmu-mosi/readme.MD

**Comment by A2Zadeh** [comment]
Closing for now, please let me know if there were other issues.
