### ISSUE TITLE
Raw data of ict-mmmo

### ISSUE THREAD

**Issue by wangdomg** [A2Zadeh/CMU-MultimodalSDK#240]
Hi, Amir
    I am trying to find the link of raw data of ict-mmmo, youtube, moud in readme, but only find the processed data, where can I get the raw data of above three datasets? If you could share the download link I will very appreciate it.

**Comment by A2Zadeh** [comment]
Hi @wangdomg,

Ah, yes that is impeccable timing. I was just zipping those datasets for release since others also asked. Give me about a week and I will share it on the server.

**Comment by wangdomg** [comment]
> Hi @wangdomg,
> 
> Ah, yes that is impeccable timing. I was just zipping those datasets for release since others also asked. Give me about a week and I will share it on the server.

Very appreciate it!

**Comment by taylor4712** [comment]
Hey, the raw dataset of ict-mmmo and youtube and moud are still not on  http://immortal.multicomp.cs.cmu.edu/raw_datasets/, is there any update regarding this?
