### ISSUE TITLE
MOSI Dataset- Tensor Fusion Network Paper - Sentiment Score Categorisation

### ISSUE THREAD

**Issue by wangdomg** [A2Zadeh/CMU-MultimodalSDK#245]
Hi Amir,
     I use the round funciton but I still can not get the distribution on 2199 samples showed in figure 2 of the paper "Tensor Fusion Network for Multimodal Sentiment Analysis.pdf". Thanks in advance for your help.

**Comment by A2Zadeh** [comment]
Hi @wangdomg.

Yeah we don't use the round function. Anything higer or equal than 0 is considered non-negative and anything lower is negative. 

In papers since 2019, we always remove the ==0 from the labels.
