### ISSUE TITLE
Some questions about the Scoreboard

### ISSUE THREAD

**Issue by wangdomg** [A2Zadeh/CMU-MultimodalSDK#246]
Hi Amir, 
        Did you run all the approaches on Scoreboard under CMU-MultimodalSDK/mmsdk/mmdatasdk/dataset/standard_datasets/CMU_MOSI/？I'm a little confused how you split the mosi data？What is the ratio of train data, test data, dev data(if exists)？I'll very appreciate it if you tell me the details.

**Comment by A2Zadeh** [comment]
Hi @wangdomg,

Majority, yes :). However, the other baselines are from colleagues who use the same folds as presented in this sdk. An example can be found here: https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/examples/mmdatasdk_examples/full_examples/process_mosi.py

If you have a baseline you would like to add, feel free to create a pull request.
