### ISSUE TITLE
CMU Mosei Data 

### ISSUE THREAD

**Issue by PierreColombo** [A2Zadeh/CMU-MultimodalSDK#250]
Hello,
Thanks again for your work. 
I am looking for aligned data for MOSEI with words availables as well (as we would like to work on BERT). Is it possible to get the words  associated with the embeddings from the data provided in http://immortal.multicomp.cs.cmu.edu/raw_datasets/processed_data/cmu-mosei/seq_length_20/data/ ?
Thanks for your time.

**Comment by A2Zadeh** [comment]
Hello @PierreColombo,

Yes, you can write a script to revert the word vectors. Just out of curiosity, if you are interested in BERT, probably the better repo for you would be our paper in this link:  https://github.com/WasifurRahman/BERT_multimodal_transformer

**Comment by PierreColombo** [comment]
Thanks :)
