### ISSUE TITLE
CMU-MOSI: Potential mismatch between raw audio and segmentation

### ISSUE THREAD

**Issue by ATriantafyllopoulos** [A2Zadeh/CMU-MultimodalSDK#255]
As I am interested in working with the raw audio (so I can use different features than they ones published), I downloaded the raw dataset from here: http://immortal.multicomp.cs.cmu.edu/raw_datasets/

This give me a list of already segmented audio files. But when I check the duration of those files, it doesn't match the `intervals` I get in the computational sequences.

As an example, there's the raw audio file: `03bSnISJMiM_1.wav`. This corresponds to `Mean Opinion Score`: `03bSnISJMiM | 51.904533 | 55.945350 | 2.40`

obtained via:

```python
data = mmdatasdk.mmdataset(mmdatasdk.cmu_mosi.labels, 'cmumosi/')
start = data.computational_sequences['Opinion Segment Labels'][file]['intervals'][index][0]
end = data.computational_sequences['Opinion Segment Labels'][file]['intervals'][index][1]
label = data.computational_sequences['Opinion Segment Labels'][file]['features'][index][0]
```

In this case, the intervals are giving me a total expected duration of `4.040817s`, but `soxi` is giving me:

```bash
Input File     : '03bSnISJMiM_1.wav'
Channels       : 2
Sample Rate    : 16000
Precision      : 16-bit
Duration       : 00:00:03.33 = 53290 samples ~ 249.797 CDDA sectors
File Size      : 213k
Bit Rate       : 512k
Sample Encoding: 16-bit Signed Integer PCM
````

So there is no way for me to match the features (e.g. words/phonemes) to the raw audio..Is there some other way this can be done?

**Comment by A2Zadeh** [comment]
Hi @ATriantafyllopoulos,

Yeah the pre-segmented clips have somehow been faulty due to the fact that we assumed 11025 but they were 16000. I suggest going with the intervals and re-extracting the audio. I will take care of this issue in January. I plan to do some dataset maintenance :)

**Comment by ATriantafyllopoulos** [comment]
@A2Zadeh thanks for the quick response! I think I might visit this sooner than you, as the deadline for ACL is end of January :) If so, I would offer to help by providing the re-extracted files.

I hope this does not mess up the alignment of phonemes and other acoustic features?

**Comment by A2Zadeh** [comment]
Hi @ATriantafyllopoulos,

Actually, there is a simple solution here. If the alignments end up being off due to the warp between the expected framerate and the actual supplied one, you can simply multiply the timestamps with the division of the two, e.g. 11025/16000 or vice versa. But yes, I do plan to solve this relatively soon :). Turns out maintenance of datasets is more work than I anticipated originally, but we have improved a lot of things along the way - so definitely worth it.

**Comment by ATriantafyllopoulos** [comment]
Thanks, I have switched to using the original intervals in the labels!
