### ISSUE TITLE
CMU-MOSEI dataset mapping

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [A2Zadeh/CMU-MultimodalSDK#256]
Hi there, 

Thank you for the great work!!

I explore CMU-MOSEI dataset and I find that some of the video ids on the CMU_MOSEI label file (http://immortal.multicomp.cs.cmu.edu/CMU-MOSEI/labels/CMU_MOSEI_Labels.csd) are not perfectly matched with the CMU_MOSEI standard folds specified in `cmu_mosei_std_folds.py`.

There are two ids in standard fold that are not in the label `7l3BNtSE0xc` and `dZFV0lyedX4` (from test fold), and 66 video ids that are in the label file but not int the standard fold as follow:

```-9YyBTjo1zo, -Alixo7euuU, -Eqdz5y4pEY, -HvKLjmsO5U, -IUUR2yyNbw, -IqSFQePnpU, -KCahx2qBOI, -LnuDPiuuZw, -NFrJFQijFE, -RpZEe4w4fY, -SYSVSQnTnA, -VmheDA92mM, -bl5PfNIYrk, -cmk6cfUeMs, -dZ1TCboxcQ, -hPfPhUIzfA, -l_53IwQoj0, -m9KtvCk_L8, -o_667Ny7RM, -qMhGeJkp5o, -wdUIwjDMfg, 1S4p-Lfhbp4, 1knHBRVPoYQ, 4Y8ROYezksQ, 5OUcvUDMMWE, 6ywl-j2-e-s, 7BFhRPlSOf0, 8vpoQ5UVpXE, 9OY3NU2ycVw, 9kLNVTm3Z90, AHXwnFvqYDk, AcoRjVPIVmQ, BgXqrxum5G4, CXvUdCdKTJY, EWYivXUavOY, EuSp1pkX9i8, FzxmeVRTjwU, JNt1k3ohkbs, MIqL9OXszRw, NVlxq3jxlAk, PEBwwe0PLZ8, TdCfpMRiA1c, TwFl4epL244, UcINGGuysBE, XnPnlRQXSkM, ZXQkyX6prBQ, aa2MEQ6FL7k, bDwAuRFciJM, cuR-l2qCxBc, dYgmvmFegkQ, fMUmdlzuc94, fiXZqpbRYKk, flv4by3RYVk, foXArPhK0xY, hytnfm-AVaA, mLZZ174bqws, nMCCLB9gOag, o5OsO6Aq9pA, o6Cd9RmqdBc, oNnoN0bxVnA, ptp-kfn4vWY, qYC3gN1AkOA, rKyXU0ls5aQ, slz8pd0Wzxs, tkzdanzsA0A, vn0CFvUK5D0, x-oexIBWwR4, zShw-E-yBqU```

I also checked that from the feature extracted in `http://immortal.multicomp.cs.cmu.edu/raw_datasets/processed_data/cmu-mosei/seq_length_20/data/`, there are 22413 data from `ey_train.h5 `,`ey_valid.h5 `,`ey_test.h5` in total. 

Do you mind to help solving this issue? Thank you!! :

**Comment by A2Zadeh** [comment]
Hi @SamuelCahyawijaya,

You can discard those videos. Post-publication, we have removed some of the videos from the dataset due to several reasons including bad alignments, bad audio/video quality or other concerns. Good luck with experiments.

Best,

Amir

**Comment by SamuelCahyawijaya** [comment]
Hi @A2Zadeh ,

Thank you for the quick response .
Ok, we will remove those ids in our experiments.

Regards,

Samuel
