### ISSUE TITLE
CMU-MOSEI: Accessing sentiment/emotion labels

### ISSUE THREAD

**Issue by ATriantafyllopoulos** [A2Zadeh/CMU-MultimodalSDK#258]
@A2Zadeh I am trying to gather all labels for `CMU-MOSEI` in a CSV:

I am using this script:

```python
import numpy as np
import pandas as pd
from mmsdk import mmdatasdk                                                             
data = mmdatasdk.mmdataset(mmdatasdk.cmu_mosei.labels, 'cmumosei/')

files = []
starts = []
ends = []
for file in data.computational_sequences['All Labels'].keys():
    for index in range(len(data.computational_sequences['All Labels'][file]['intervals'])):
        files += [file]
        starts += [data.computational_sequences['All Labels'][file]['intervals'][index][0]]
        ends += [data.computational_sequences['All Labels'][file]['intervals'][index][1]]
        # sentiment,happy,sad,anger,surprise,disgust,fear
df = pd.DataFrame(
    data=np.stack([
        files,
        starts,
        ends,
    ], axis=1),
    columns=[
        'file',
        'start',
        'end',
    ]
)
```

Unfortunately, this gives me `23,259` segments, from `3293` files.

However, in the paper where the dataset was introduced, it's mentioned that there is a total of `23,453` from `3228` files.
Any explanation for the discrepancy? Did I parse the computational sequence wrong, or where some labels/segments removed at a later date?

**Comment by A2Zadeh** [comment]
Hi @ATriantafyllopoulos,

Yes, the number of sentences may be different from one video to another. Perhaps you are interested in the final tensors for ML applications? That would definitely give you better and easier path to the csv. Let me know if you want me to give pointers for this direction.

**Comment by ATriantafyllopoulos** [comment]
> 
> 
> Hi @ATriantafyllopoulos,
> 
> Yes, the number of sentences may be different from one video to another. Perhaps you are interested in the final tensors for ML applications? That would definitely give you better and easier path to the csv. Let me know if you want me to give pointers for this direction.

@A2Zadeh yes, that would do, so long as I can tie back the labels to the original segments and files :)

What I am aiming for is to convert the dataset to the [audformat representation](https://github.com/audeering/audformat), which we open-sourced just last week.

For that I'll need a CSV that looks like this: 

```python
file, start, end, sentiment
A,         0,     1,          1
A,         2,     3,          2
B,         4,     8,          3
```

With `start,end` being the `intervals` in your computational sequences.
