### ISSUE TITLE
How to get Train/val/test_split of MOSEI?

### ISSUE THREAD

**Issue by sceliay** [A2Zadeh/CMU-MultimodalSDK#261]
![image](https://user-images.githubusercontent.com/2412726/102114817-a37e6f00-3e75-11eb-8b6d-3f553c5201bb.png)
when I use the code to split dataset,  why it seems belong to MOSI?
![image](https://user-images.githubusercontent.com/2412726/102115053-f6582680-3e75-11eb-821c-7c9937ea7d87.png)

**Comment by A2Zadeh** [comment]
Hi @sceliay,

Not sure what is happening in your code, but the splits are available here: 

https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/mmsdk/mmdatasdk/dataset/standard_datasets/CMU_MOSEI/cmu_mosei_std_folds.py

**Comment by sceliay** [comment]
Thank you very much!

**Comment by A2Zadeh** [comment]
@sceliay You are welcome!
