### ISSUE TITLE
Labels of POM dataset (18 attributes found)

### ISSUE THREAD

**Issue by xingbow** [A2Zadeh/CMU-MultimodalSDK#262]
Hi @A2Zadeh 

I find that the newest version of POM labels from this link: http://immortal.multicomp.cs.cmu.edu/POM/labels/ has **18** attributes instead of **16 or 17** in the original dataset (http://immortal.multicomp.cs.cmu.edu/raw_datasets/processed_data/pom/README.md)
Can you tell me what they mean? And what numbers mean? what is the range of labels (1 to 5 OR 1 to 7)?

Looking forward to your reply

**Comment by A2Zadeh** [comment]
Hello @xingbow,

The labels can be retrieved via "dimension names" key in the metadata of each computational sequence. Here is the one for POM labels:

`dimensions=["sentiment","confident","passionate","voice_pleasant", "dominant","credible","vivid","expertise","entertaining","reserved","trusting","lazy","relaxed","outgoing","thorough","nervous","humerous","persuasion"]`

Their range is identical to the original paper.

**Comment by xingbow** [comment]
Thanks for the swift response!

Which csd files you specifically refer to since I don't find metadata in `POM_Labels.csd`
