### ISSUE TITLE
CMU-MOSI: Duplicates/overlap in annotations

### ISSUE THREAD

**Issue by ATriantafyllopoulos** [A2Zadeh/CMU-MultimodalSDK#265]
I have discovered a few problems in the `Opinion Segment Labels` of `CMU-MOSI`. Specifically, some segments have been labelled twice, and there are cases with different annotations for overlapping segments.

Duplicate segments are:

```
d6hH302o4v8,94.417915,95.834694
bOL9jKpeJRs,88.24195,90.0678
```

In addition, there are some overlapping segments. I haven't yet been able to find all of them. I will try to provide a full list later.

Here is a MWE for reproducing the error for one of them:

```python

from mmsdk import mmdatasdk                                                             
data = mmdatasdk.mmdataset(mmdatasdk.cmu_mosi.labels, 'cmumosi/')

for file in data.computational_sequences['Opinion Segment Labels'].keys():
    if file != 'ZUXBRvtny7o':
        continue
    x = data.computational_sequences['Opinion Segment Labels'][file]['intervals']
    for index in range(len(x)):
        print((index, x[index][0], x[index][1]))
    exit()
```

This will show errors in the following segments:

```bash
[...]
(21, 117.5254, 119.31134)
(22, 117.94444, 119.31134)
[...]
(24, 124.07052, 128.93945)
(25, 124.07052, 137.35034)
[...]
```

This might also be true for CMU-MOSEI, as I came across the problem there too while trying to get the labels as described in #258.

@A2Zadeh do you think this is an error in accessing the labels on my side, or a bug in the CSDs?

**Comment by ATriantafyllopoulos** [comment]
So I have been able to detect all overlapping segments. Unfortunately, the problem seems also to appear in `CMU-MOSEI`, but thankfully I found no duplicates there.

I am uploading a ZIP file with 3 CSVs containing the detected files/segments where the problem appears for the two datasets.

@A2Zadeh it would be nice if you could take a look :)

[ProblematicSegments.zip](https://github.com/A2Zadeh/CMU-MultimodalSDK/files/5786999/ProblematicSegments.zip)

**Comment by A2Zadeh** [comment]
Hi @ATriantafyllopoulos,

This is a good find. The number of such datapoints are small enough to say let's neglect it. I think a good trend is also there since we got better and better from MOSI to MOSEI, where the number of such datapoints decreases. I will keep an eye out for this kind of stuff from now on. Thanks a lot!!

**Comment by ATriantafyllopoulos** [comment]
> 
> 
> Hi @ATriantafyllopoulos,
> 
> This is a good find. The number of such datapoints are small enough to say let's neglect it. I think a good trend is also there since we got better and better from MOSI to MOSEI, where the number of such datapoints decreases. I will keep an eye out for this kind of stuff from now on. Thanks a lot!!

Agreed the datapoints are too few to make any meaningful difference! I'll close now  :)
