### ISSUE TITLE
Is it possible to get raw audio and video files of CMU-MOSEI ?

### ISSUE THREAD

**Issue by Aria-K-Alethia** [A2Zadeh/CMU-MultimodalSDK#269]
Hi,
I want to use raw audio and video files of CMU-MOSEI to extract features by myself. 
Is it possible and how can I find them ?

Thank you

**Comment by A2Zadeh** [comment]
Hi @Aria-K-Alethia,

Yes, the data is here: http://immortal.multicomp.cs.cmu.edu/raw_datasets/CMU_MOSEI.zip

**Comment by Aria-K-Alethia** [comment]
Thank you for your help !
Since I've downloaded it I will close this issue.
