### ISSUE TITLE
Speeding up alignment

### ISSUE THREAD

**Issue by yiwang454** [A2Zadeh/CMU-MultimodalSDK#270]
Hi Amir, @A2Zadeh 

I'm wondering how you speed up the alignment for about 40 times? I'm trying to align word embeddings to acoustic features and I changed the python alignment function a bit to duplicate the word embeddings to keep it fitting the intervals of the COVAREP features. And with all 46468664 COVAREP frames, I've been running alignment for around two days and got only 34% aligned and the rest would probably take another 4-5 days. So I'm wondering how you made the code more efficient and did I change that essential part that leads to slow alignment. Or maybe I could learn from your method to speed up the code.

My code for method intersect_and_copy is shown as below
'''
    def intersect_and_copy_upsampling(self, ref_time,relevant_entry,epsilon, log_file, feature_info):
        
        sub=relevant_entry["intervals"]
        features=relevant_entry["features"]
        
        #finding where intersect happens
        where_intersect = -1
        for i, inter in enumerate(sub):
            if (ref_time[0] - inter[0]) > (-epsilon) and (inter[1] - ref_time[0]) > (-epsilon):
                where_intersect = i
        if where_intersect == -1:
            diff = list(map(lambda x: abs(ref_time[0] - x), sub[:, 0]))
            min_diff = min(diff)
            where_intersect = diff.index(min_diff)
            with open(log_file, 'w+') as fi:
                fi.write('no corresponding frame, find the closest one, {}, difference: {}\n'.format(feature_info, min_diff))
            
        intersectors=sub[where_intersect,:]
        intersectors_features=features[where_intersect,:]
        
        zero_idx = np.where(np.isinf(intersectors_features))
        intersectors_features[zero_idx] = 0

'''

**Comment by A2Zadeh** [comment]
Hi @yiwang454,

Currently I am running the alignment on CMU-MOSEI in around 2 hours. The code is heavily dependent on the underlying BLAS functions of numpy. What you are doing in:

`    for i, inter in enumerate(sub):
        if (ref_time[0] - inter[0]) > (-epsilon) and (inter[1] - ref_time[0]) > (-epsilon):
            where_intersect = i
`

Is hard to parallelize. Ideally, you want every for loop to always be an efficient (or sparse) matrix multiplication. Some CPU and GPU libraries have great support for this kind of operations, and will break down the multiplication over parallel for loops. Hope this helps!

**Comment by yiwang454** [comment]
Thank you for reply!
Now I got the difference between my code and your alignment code that make my code running slow. 
I had changed the methods to be aligning other features to the acoustic feature by multiplying the time interval by 100 to find the corresponding acoustic frame, and this works better for me now.
It's still very helpful to know what operations are hard to parallelize. Thanks!
