### ISSUE TITLE
IEMOCAP Password Request

### ISSUE THREAD

**Issue by vandana-rajan** [A2Zadeh/CMU-MultimodalSDK#273]
Hello @A2Zadeh,

I have sent you an email on your CMU email ID requesting the password for the processed IEMOCAP zip file. I have received approval from Sabyasachee Baruah, USC, which is also forwarded to you. Kindly send me the password to access the same.

Thanks,
VR

**Comment by stdoo** [comment]
@vandana-rajan Have you received the password?
