### ISSUE TITLE
About the IEMOCAP  dataset

### ISSUE THREAD

**Issue by KaetheFu** [A2Zadeh/CMU-MultimodalSDK#288]
IEMOCAP

I  got the permission from them, Would you like to share the password of this zip with me

**Comment by Linths** [comment]
Hi there, when I requested access to the IEMOCAP dataset, they emailed me a link to the zip and the password. Maybe it's in your spam folder?

**Comment by A2Zadeh** [comment]
Hi @KaetheFu,

Please email me for access.
