### ISSUE TITLE
The link to the raw dataset is not working

### ISSUE THREAD

**Issue by rihabhajlaoui** [A2Zadeh/CMU-MultimodalSDK#291]
Hello, 
This link (http://immortal.multicomp.cs.cmu.edu/raw_datasets/) to the raw dataset is not working for me. Is there a way to access the videos used in the CMU-MOSEI dataset?

**Comment by Linths** [comment]
I have the same issue, I would like to start working with the raw data on a short notice. It seems the whole website is down by the way. Maybe the CMU-MOSEI dataset can be uploaded to Kaggle too to ensure stability.

**Comment by A2Zadeh** [comment]
Hi folks. Yes, the website has gone down. I will bring it up again this Tuesday (tomorrow).

**Comment by arminarj** [comment]
Hi Dear Amir, @A2Zadeh 
It seems there is still a permission error (404) for accessing the link.

**Comment by eletap** [comment]
Hi, any updates on this? Thanks in advance :)

**Comment by A2Zadeh** [comment]
Hi all,

I was just able to bring the server back up. You should have access to all the files soon again :). Apologies for the downtime.

**Comment by eletap** [comment]
Hello, 

Sorry to bother you again, but it seems that the problem with permissions persists:

> 403 Forbidden
> 
> You don't have permission to access /raw_datasets/ on this server.
> Apache/2.4.7 (Ubuntu) Server at immortal.multicomp.cs.cmu.edu Port 80

Thanks for your effort!

**Comment by alexgt01** [comment]
Server is still down.

**Comment by svdcvt** [comment]
Server is still down, maybe move dataset to kaggle or smth, google disk at least...

**Comment by A2Zadeh** [comment]
Hi all,

This issue should be resolved now.

**Comment by dbaranchuk** [comment]
It seems the server is down again

**Comment by guoweizhong-zjut** [comment]
Hello,
I have a problem in downloading the MOSI dataset
`RuntimeError: URL: http://immortal.multicomp.cs.cmu.edu/CMU-MOSI/language/CMU_MOSI_TimestampedWordVectors.csd does not exist` when I used the following code
`cmumosi_highlevel=mmdatasdk.mmdataset(mmdatasdk.cmu_mosi.highlevel,'cmumosi/')`
and also, I can't access the website: http://immortal.multicomp.cs.cmu.edu/raw_datasets/
