### ISSUE TITLE
The server for data/label downloading is down

### ISSUE THREAD

**Issue by leo19941227** [A2Zadeh/CMU-MultimodalSDK#292]
Hi,

Thanks for the great project!
It seems the server is down and I can not get the labels following the steps on the README.
```
from mmsdk import mmdatasdk
cmumosi_highlevel=mmdatasdk.mmdataset(mmdatasdk.cmu_mosi.highlevel,'cmumosi/')
```
The code will stuck at connecting to the server.
Also, the link for the raw dataset is also dead: http://immortal.multicomp.cs.cmu.edu/raw_datasets/

Is there any schedule for the server to be online?
Thanks!

**Comment by A2Zadeh** [comment]
Hi all,

This issue should be resolved now.
