### ISSUE TITLE
.csd file are not accessible

### ISSUE THREAD

**Issue by Gautam-Goyal** [A2Zadeh/CMU-MultimodalSDK#294]
While running the code, I got the following issue
<img width="988" alt="Screenshot 2021-07-05 at 11 48 49 PM" src="https://user-images.githubusercontent.com/60264618/124507625-c8bfd400-ddeb-11eb-9f2a-ee5bdc2f56c2.png">

saying that access to **_CMU_MOSI_ModifiedTimestampedWords.csd_** has been forbidden.similar to other .csd files. Is there anything that i can do to override it?

**Comment by souravBhat** [comment]
Anyone else running into this issue? Can we please get an update on this?

**Comment by pi408637535** [comment]
I'm meeting the same issue
[2021-07-11 10:55:53.683] | Error   | URL: http://immortal.multicomp.cs.cmu.edu/CMU-MOSI/language/CMU_MOSI_TimestampedWordVectors.csd does not exist
have been downloaded

**Comment by A2Zadeh** [comment]
Hi all,

This issue should be resolved now.

**Comment by Gautam-Goyal** [comment]
thanks
