### ISSUE TITLE
About the MOSEAS dataset

### ISSUE THREAD

**Issue by mpc001** [A2Zadeh/CMU-MultimodalSDK#297]
Hey, there,

could someone please tell me where I can find the MOSEAS dataset?

Thanks in advance!

**Comment by A2Zadeh** [comment]
Hi @mpc001,

Until we finalize an official release, here is the simple release: http://immortal.multicomp.cs.cmu.edu/cache/multilingual/

Hope it help. You will need to extract features on your side.
