### ISSUE TITLE
MOSEI OpenFace2.0 .csd update

### ISSUE THREAD

**Issue by arminarj** [A2Zadeh/CMU-MultimodalSDK#299]
Hi @A2Zadeh, 

I have noticed the Openface2.0 preprocessed files(.csd) for the CMU-MOSEI dataset are changed from 16GB to 36GB, Are there any notes for this update?

**Comment by A2Zadeh** [comment]
Hi @arminarj 

Hope you're well. I accidentally restored an old backup. It's all good now.
