### ISSUE TITLE
Download Links not working for some of the Standard Datasets

### ISSUE THREAD

**Issue by jytan17** [A2Zadeh/CMU-MultimodalSDK#300]
Hi, the following CMU-MOSEI and CMU-MOSI download links are not working:

http://immortal.multicomp.cs.cmu.edu/CMU-MOSEI/language/CMU_MOSEI_TimestampedWordVectors.csd

http://immortal.multicomp.cs.cmu.edu/CMU-MOSEI/labels/CMU_MOSEI_Labels.csd

http://immortal.multicomp.cs.cmu.edu/CMU-MOSI/language/CMU_MOSI_TimestampedWordVectors.csd

Can you look into it please?

**Comment by A2Zadeh** [comment]
Hi @jytan17 

Old backup directory was accidentally restored :D. Now fixed ...

**Comment by ayesha-119** [comment]
Hi,
final_aligned/CMU_MOSI_ModifiedTimestampedWords.csd file not found, please check the path ...
I'm still getting this error

**Comment by ayesha-119** [comment]
Hi, 
The issue "You don't have permission to access /CMU-MOSEI/language/CMU_MOSEI_TimestampedWordVectors.csd on this server." persists. can you please look into it? thank you in advance
