### ISSUE TITLE
Question about processed IEMOCAP dataset seq_length_50

### ISSUE THREAD

**Issue by asolano** [A2Zadeh/CMU-MultimodalSDK#302]
Greetings!

I am trying to read the raw datasets processed data and the IEMOCAP `seq_length_50` folder's `ieomcap_data.pkl` file reports a second dimension of 20 instead of the expected 50:

```python
In [1]: import os

In [2]: root_dir='iemocap'

In [3]: path = os.path.join(root_dir, 'seq_length_50', 'iemocap_data.pkl')

In [4]: f = open(path, 'rb')

In [5]: import pickle

In [6]: d = pickle.load(f)

In [7]: d.keys()
Out[7]: dict_keys(['test', 'train', 'valid'])

In [8]: train = d['train']

In [9]: train.keys()
Out[9]: dict_keys(['labels', 'text', 'audio', 'vision'])

In [10]: train['text'].shape
Out[10]: (2717, 20, 300)
```

Could you please confirm if that is the proper file? (For comparison, both MOSI and MOSEI report the expected shape)

Thanks,

Alfredo

**Comment by A2Zadeh** [comment]
Hi @asolano,

Yes, this is correct. The file should be moved to the 20 sequence length. We may have misplaced it.

**Comment by asolano** [comment]
Understood, thanks for the confirmation.
