### ISSUE TITLE
Can not access MOSEI dataset

### ISSUE THREAD

**Issue by renj** [A2Zadeh/CMU-MultimodalSDK#304]
Hi, currently I can not access the MOSEI dataset via the download code because of this error:
RuntimeError: URL: http://immortal.multicomp.cs.cmu.edu/CMU-MOSEI/language/CMU_MOSEI_TimestampedWordVectors.csd does not exist

The download link http://immortal.multicomp.cs.cmu.edu/raw_datasets/CMU_MOSEI.zip does not work either. 

Does anyone know how to get the data?

Thanks!

**Comment by kniter1** [comment]
I have the same problem, did you solve it？

**Comment by renj** [comment]
No, I still don't have access to the data. Hi, @A2Zadeh, could you help us on accessing this data?

**Comment by A2Zadeh** [comment]
Hi folks,

This is an issue with the machine and the hard drive hosting things. I should be able to resolve it within the next week. Apologies, I am a bit busy with my thesis at the moment, but will solve this asap.

**Comment by renj** [comment]
Hi @A2Zadeh, can you provide any other way to access the data (e.g. Google Drive) if the hard drive issue is difficult to solve? We are targeting AAAI and this dataset will be a very important experiment in our current work. Thank you so much!

**Comment by souravBhat** [comment]
Hi @A2Zadeh , can we please get an estimate on when we can expect this to be resolved?

**Comment by A2Zadeh** [comment]
Hi all,

This issue is now solved. Server is up!
