### ISSUE TITLE
Regarding model selection and reporting results

### ISSUE THREAD

**Issue by vandana-rajan** [A2Zadeh/CMU-MultimodalSDK#305]
Hi @A2Zadeh and @pliang279,

I have a doubt regarding sentiment analysis using CMU-MOSEI.  Most papers report results on 5 evaluation metrics (MAE, corr, acc 7, f1, acc 2). When I ran a hyper-parameter grid search on my architecture, I found that different models give best results on each evaluation metric for CMU-MOSEI dataset. I mean, while one set of hyper-parameters gives the best result in terms of MAE, another set gives the best for Corr. I found that in your MFN repo, there are 2 different models for best MAE and best acc respectively (https://github.com/pliang279/MFN) as well.

So, while reporting the results, should one just report the best for each evaluation metric, or should one select one best model and report its all 5 metrics? In the second case, how should that model be selected? What is the method that you follow in your papers?

Thanks,
VR

**Comment by A2Zadeh** [comment]
Hi @vandana-rajan,

You should try to report the best for each metric. There is no one model that works for all the metrics.
