### ISSUE TITLE
CNN on VisualFacet computational sequence of MOSI dataset

### ISSUE THREAD

**Issue by Gautam-Goyal** [A2Zadeh/CMU-MultimodalSDK#307]
I was building a model on the MOSI dataset, where I have trained the model on a text dataset and now I am training it on an Image dataset. I am using the Visual_Facet_42 computational sequence. In it when I check the features of the video segment it had a shape like (5402,35). I got that 5402 must be for the no. of frames and 35 is the extracted feature vector. But my question is how I can apply CNN on this dataset where the features from the 2d frame (like (25*25)) have been extracted and converted into a 1d array (1,35) for each frame. Please help me with how to do it. 

Also, If that problem is solved, please also help me on how to merge features of text and video data, if I want to, my text data has been converted into 300 dimensions after using glove embedding. So, please tell me!!

**Comment by A2Zadeh** [comment]
Hi @Gautam-Goyal,

For this purpose, you will need to extract the frames from the raw videos of the MOSI dataset. I am fixing the download links so that should be up and running soon.
