### ISSUE TITLE
MOSEAS-WE1 

### ISSUE THREAD

**Issue by AnilRahate** [A2Zadeh/CMU-MultimodalSDK#308]
Hi Amir,
Can you please let me know how can we access MOSEAS-WE1 dataset. Is it available http://immortal.multicomp.cs.cmu.edu/raw_datasets/processed_data/. Looks like this link is down, hence I could not check.

Thanks a lot for all your trend setting contribution in multimodal.

**Comment by A2Zadeh** [comment]
Hi @AnilRahate,

For now, this is where you can access the data: http://immortal.multicomp.cs.cmu.edu/cache/multilingual/

Later we will incorporate computational sequences into the SDK.
