### ISSUE TITLE
Availability of MOSEAS-WE1

### ISSUE THREAD

**Issue by Sreeni1204** [A2Zadeh/CMU-MultimodalSDK#309]
Hello Amir,

Thank you for the CMU-MOSEI dataset,

I am working on the emotion recognition based on multi-lingual text data.

I am waiting for the MOSEAS-WE1 (German) dataset, could you please let me know by when will it be available.

Regards,
Sreeni...

**Comment by A2Zadeh** [comment]
Hi @Sreeni1204,

For now, this is where you can access the data: http://immortal.multicomp.cs.cmu.edu/cache/multilingual/

Later we will incorporate computational sequences into the SDK.

**Comment by atebbifakhr** [comment]
Hi Amir, 

I checked the link that you have shared, but I couldn't find the labels. Could you please point them out?
