### ISSUE TITLE
Can't download mosei highlevel data, URL is wrong

### ISSUE THREAD

**Issue by Ouskit** [A2Zadeh/CMU-MultimodalSDK#313]
Hi,  when I was using `mmdatasdk.mmdataset(mmdatasdk.cmu_mosei.highlevel, 'cmumosei/')` to download mosei high level data, finding that the url is wrong, and it should be http://immortal.multicomp.cs.cmu.edu/CMU-MOSEI/language/CMU_MOSEI_TimestampedWordVectors.csd

there is no url : http://immortal.multicomp.cs.cmu.edu/CMU-MOSEI/language/CMU_MOSEI_TimestampedGloveVectors.csd

![圖片](https://user-images.githubusercontent.com/17953466/135239144-bcf299e8-c010-457f-88ef-e4569d05bcd3.png)

**Comment by JeffreyHJF** [comment]
Hello, Do you solve this problem now? I faced the same issue, and I do appreciate it if you share the solution of it:)
