### ISSUE TITLE
Problem with video segments in MOSI dataset

### ISSUE THREAD

**Issue by Deanplayerljx** [A2Zadeh/CMU-MultimodalSDK#37]
Please check video segment 2WGyTLYerpo_44 in the MOSI dataset. It contains all the frames from video segment 2WGyTLYerpo_45 to video segment 2WGyTLYerpo_63. 

According to the corresponding transcript, the sentence for the segment 2WGyTLYerpo_44 should be "SHES BEAUTIFUL" and the sentence for the segment 2WGyTLYerpo_43 should be "AND ALSOUM OLIVIA WILD SHES PRETTY GOOD". However, in the video segments, the video 2WGyTLYerpo_43 contains both sentences for 2WGyTLYerpo_43 and 2WGyTLYerpo_44, i.e. "AND ALSOUM OLIVIA WILD SHES PRETTY GOOD SHES BEAUTIFUL", and video 2WGyTLYerpo_44 is messed up.

Also, the video segment 9qR7uwkblbs_32 contains the transcript for both 9qR7uwkblbs_32 and 9qR7uwkblbs_33, and video segment 9qR7uwkblbs_33 doesn't contain any word.

there are some mismatches between transcript and video for (BI97DNYfe5I_17, BI97DNYfe5I_18) and  (BI97DNYfe5I_19, BI97DNYfe5I_20, BI97DNYfe5I_21), especially for BI97DNYfe5I_18 and BI97DNYfe5I_20.

transcript for video segment VCslbP0mgZI_1 is wrong, the current transcript for VCslbP0mgZI_1 should be part of the transcript in VCslbP0mgZI_2.

The video segmentation between 8NXH0Djyww_1 and 8NXH0Djyww2 is a little bit inaccurate. The transcript for 8NXH0Djyww2 is "SURPRISED ME" but in the video segmentation word "surprised" was included in video 8NXH0Djyww_1 instead of 8NXH0Djyww2.

Side note: I found these problems by examining video segments that contain a very small number of frames or extremely large number of frames.

I really appreciate the effort that the author spent for this dataset, and I write down the problems I found here in case other people may find it useful.

**Comment by A2Zadeh** [comment]
@Deanplayerljx Hello! Thank you very much for raising this issue. We got aware of this problem about two weeks ago. It is essentially a bug in the pipeline as the raw data (will be disclosed publicly soon) does not have that issue. We are working to find out the source of this problem, and we will fix it with the next release of the SDK (version 1.0.0). This release will come out on June 15th. Thank you for reporting this bug and please check back soon for the fixed version.
