### ISSUE TITLE
Openface features and link for the dataset

### ISSUE THREAD

**Issue by Deanplayerljx** [A2Zadeh/CMU-MultimodalSDK#42]
Hi,

It seems the MOSI dataset in the new SDK does not include features extracted by Openface. Can I know how can I access them? Also, can I know the link that currently hosts the MOSI dataset(not csd files)? It was hosted at http://sorena.multicomp.cs.cmu.edu/downloads/MOSI but I cannot access it anymore. Thanks!

**Comment by A2Zadeh** [comment]
Hi @Deanplayerljx. We are working on OpenFace and OpenSmile features. They will be ready till end of weekend. Sorena is no longer the hsot of these datasets. In fact we no longer use links unless they are put in a correct protocol. You can see the following file for correct protocol: https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/mmsdk/mmdatasdk/dataset/standard_datasets/CMU_MOSI/cmu_mosi.py
