### ISSUE TITLE
Question for video segments and labels in MOSI

### ISSUE THREAD

**Issue by Deanplayerljx** [A2Zadeh/CMU-MultimodalSDK#43]
Hi,

I just checked the Openface features in MOSI and sentiment labels. Can I know if the segmented video features are still available(in the old version of sdk, I can access them via dataset.openface()['openface'][vid][sid])?  It seems currently there are only features for the full video. 

For the opinion labels in MOSI, it seems the labels for all videos are the same. I checked them via f1['Opinion Segment Labels']['data'][vid]['features'][:], where f1 refer to the computation sequence read in by h5py module. I'm not sure if I interpreted it wrong or it's a bug... 

Thanks!

**Comment by A2Zadeh** [comment]
Hello @Deanplayerljx 

Yes, in the new version of SDK there is no segment level timestamping. Everything is globally timestamped. We are currently testing a feature that will do what the previous sdk did, which is aligning based on start and end of segments.

For the labels, let me check that and get back to you. I see that they are different. Can you give me a vid id?

**Comment by Deanplayerljx** [comment]
Hi,

Below are the labels for two different segments. I use '03bSnISJMiM' and '0h-zjBukYpk' in the pictures
![image](https://user-images.githubusercontent.com/21377022/43099540-1b8b4d56-8e88-11e8-8602-5bb32df65d16.png)

![image](https://user-images.githubusercontent.com/21377022/43099554-24db4488-8e88-11e8-93b7-896bf682b5cb.png)

Actually the video labels looks like this on my side...

Thanks!

**Comment by A2Zadeh** [comment]
Ah I see. Good catch. Let me fix it.

**Comment by A2Zadeh** [comment]
It is now fixed.
