### ISSUE TITLE
MFN code

### ISSUE THREAD

**Issue by marcostx** [A2Zadeh/CMU-MultimodalSDK#46]
Hi Amir,

Do you have any plans to make the paper memory Fusion Network code available? I intend to replicate the results for research purposes and improve as well.

Best regards,

Marcos

**Comment by A2Zadeh** [comment]
Hello Marcos,

We do plan on releasing them. It will probably take us till August 15th to be able to do that. We will keep you posted. 

Best,

Amir

**Comment by A2Zadeh** [comment]
@marcostx following up, you can now find the MFN code in pytorch from the related_repos folder with the original training data we used (which belonged to an old version of the SDK)

**Comment by marcostx** [comment]
@A2Zadeh Thank you!

**Comment by A2Zadeh** [comment]
@marcostx you're welcome. The code should also have the trained models. Good luck!
