### ISSUE TITLE
Looking for Datasets

### ISSUE THREAD

**Issue by KuzmaNg** [A2Zadeh/CMU-MultimodalSDK#47]
Hi mmSDK crew,
Due to the new release of mmSDK, I have no idea on where to download the POM, IEMOCAP and some other datasets now. Would you like to share some ways? Thanks.

**Comment by A2Zadeh** [comment]
Hello @KuzmaNg! We are working hard to release all the datasets. I am willing to make a trade :). I will be able to release POM soon but I will need someone to double check if the data is correct. Like if the timestamps seem to be consistent and what not. Would you be willing to do that? Most likely it will be correct. 

P.S. We are not going to support IEMOCAP. Our emotion recognition benchmark will be CMU-MOSEI.

**Comment by KuzmaNg** [comment]
Hi **@A2Zadeh**!. Of course, I am willing to try. But I am not so sure about the details on double checking the data😂. 
Best regards.

**Comment by A2Zadeh** [comment]
@KuzmaNg: simply checking to see if there is any inconsistency with the timings I give you. Most likely there will be none. I will work on it next week. I could potentially do it this weekend too.

**Comment by A2Zadeh** [comment]
Yeah that would just include building a simple model on the data and seeing how it would work. I will keep you updated about the timeline of POM.

**Comment by KuzmaNg** [comment]
Thank you so much, @A2Zadeh

**Comment by A2Zadeh** [comment]
@KuzmaNg just to keep you in the loop I am extracting new FACET features for POM. So waiting on that before I put it online.

**Comment by KuzmaNg** [comment]
@A2Zadeh Thank you. POM is updated.

**Comment by KuzmaNg** [comment]
Hi @A2Zadeh . Is there standard fold for POM dataset just like in MOSI to split train/vallid/test set? 
It needs no alighment since POM is a video-level dateset? I am curious because I got a error when I did the alighment. Thanks.

**Comment by KuzmaNg** [comment]
@A2Zadeh Thank you so much. 👍

**Comment by KuzmaNg** [comment]
Hi @A2Zadeh , 
Since the POM is based on video-level, any necessity to do the alignment? Also, I found the 'inf' value in acousitc features, is that normal? or any way to deal with this situation? 
Thanks.

**Comment by A2Zadeh** [comment]
Hi @KuzmaNg, not necessary for POM to align, you are correct. However if you want to do word-level fusion then you need to see what context accompanies the words. Yes, we decided to leave nan and inf values as they are.

**Comment by KuzmaNg** [comment]
OK, got it. Thanks again. @A2Zadeh

**Comment by KuzmaNg** [comment]
Hi @A2Zadeh ,
Another exception encountered. ＞﹏＜
Without alignment, there are 1000 samples in POM label set and acoustic feature set which correctly matches the amount mentioned in the paper by Park. However, there are only 999 for textual and visual features. Also, keyerror '27888' is found. It seems like key '27888' is not included in standard-fold and label-set, but it shows up in texual, visual and acoustic feature set.
Thanks.

**Comment by KuzmaNg** [comment]
Hi @A2Zadeh , 
I am not sure if you notice this issue about POM.😂 Just stopby to mention it.
Thanks.

**Comment by A2Zadeh** [comment]
@KuzmaNg, quick question. Did this issue get resolved in the latest version of POM?

**Comment by KuzmaNg** [comment]
Hi @A2Zadeh ,
I am not so sure. I have not tried the latest released version of POM. Has it been updated recently? It said the _pom.py_ was still 3 months ago in the sdk.😵
Thanks.

**Comment by A2Zadeh** [comment]
@KuzmaNg Oh we actually just update the online files you download, not the ones on the SDK itself. That way we can just update the latest files directly on our server. If you are able to redownload and run your script, let me know if it fails.

**Comment by KuzmaNg** [comment]
Hi @A2Zadeh ,
I redownloaded the data by using the address provided in _pom.py_. The length of keys in textual and visual features remains 999, not 1000. Is it a right way to acquire the latest files from the server? 
Anyway, It's Okay. I can have 903 in total, matching the number mentioned in MFN and MARN.
Thanks.

**Comment by A2Zadeh** [comment]
@KuzmaNg yeah 1 video was giving us errors, so we had to just leave it out. Great! Do you know which 903 they are?

**Comment by KuzmaNg** [comment]
Hi @A2Zadeh ,
Of course, I could print them out.

**Comment by A2Zadeh** [comment]
@KuzmaNg Great!

**Comment by KuzmaNg** [comment]
Hi, @A2Zadeh 
I found that 17 categories are included in old_processed_data (_POM_). Besides 16 traits, would _persuasion_vec=[persuasive]_ or _sentiment_vec=[sentiment]_ be one of the 17? I wanna know if the trait order is consistent with POM data from SDK. Thanks.
