### ISSUE TITLE
Tensor Fusion Network Code

### ISSUE THREAD

**Issue by lan-qing** [A2Zadeh/CMU-MultimodalSDK#48]
Hi Amir,
From the previous code I find such paragraphs:
 ```truth_path = dataset_path + 'Meta_data/boundaries_sentimentint_avg.csv'

 # openface_path = dataset_path + "Features/Visual/OPEN_FACE/Segmented/"
 openface_path = dataset_path + "Features/Visual/OpenfaceRaw/"
 facet_path = dataset_path + "Features/Visual/FACET_GIOTA/"
 covarep_path = dataset_path + "Features/Audio/raw/"
 transcript_path = dataset_path + 'Transcript/SEGMENT_ALIGNED/'

 word2ix_path = data_path + 'glove_word_embedding/word2ix_300_mosi.pkl'
 word_embedding_path = data_path + "glove_word_embedding/glove_300_mosi.pkl"
```

But I can only download .csd files from mmsdk. So could you please tell me how to use them?

Thank you!

Best Wishes,
Lan-qing

**Comment by lan-qing** [comment]
The codes in [Justin-TFN](https://github.com/Justin1904/TensorFusionNetworks) use the old mmdata api, but it seems not be supported now. Could you please tell me how to run the TensorFusionNetwork with this api?

Thank you!

**Comment by A2Zadeh** [comment]
Hello @lan-qing. We are working on putting tutorials online. Currently busy time due to conference deadlines. We will update the website soon with MARN and MFN. It may take us some more time to do the TFN. We will keep you posted.

**Comment by lan-qing** [comment]
OK. Thank you.

**Comment by A2Zadeh** [comment]
@lan-qing following up, we just released a bunch of codes online. You may want to have a look at the modelsdk and also the related_repos folder in the root of the SDK.
