### ISSUE TITLE
raw video data

### ISSUE THREAD

**Issue by yding37** [A2Zadeh/CMU-MultimodalSDK#49]
Thank you for doing this and for the nice data you've gathered. I went through your paper and have to say the data collection was done very well. 

On that note, I'd really like to analyze the raw footage you have. I'm wondering if you will be releasing the raw video, audio and text data or if there was something that has changed in the repo that can let me download this beyond the highlevel features?

**Comment by A2Zadeh** [comment]
Hello @yding37. We are planning to release the raw data hopefully by the end of the month. Please stay tuned. Thanks.

**Comment by yding37** [comment]
Great thanks, I'll be tuning in.

**Comment by mishee90** [comment]
Hi Amir,

I have read with interest your paper along Soujnaya on Context-Dependent User-Generated Video Analysis and plan to use that in one of my capstones. 

I was wondering do you plan to release the raw data for MOSI soon? I read one of the comments where you mentioned it would be out by the end of Month of August do you have any updates?

Looking forward to connecting with you to know more about your experience in your research.

**Comment by A2Zadeh** [comment]
@mishee90 Sorry for the late response. The data has been released for a while. Let me know if you have any questions. Thanks for your interest in our work!
