### ISSUE TITLE
CMU-MOSEI acoustic features

### ISSUE THREAD

**Issue by zsun227** [A2Zadeh/CMU-MultimodalSDK#52]
Hi,  thanks for sharing the CMU-MOSEI dataset. However, I could not find acoustic features for the CMU-MOSEI dataset. I could download glove_vectors and Facet 4.2 features but I could not find the COVAREP features or any other acoustic features.....

Could you tell me where I can find those acoustic features? Or would you plan to upload those features in future? Thanks!

**Comment by A2Zadeh** [comment]
Hello. We are planning on releasing those features by end of this week. We re-ran COVAREP on them.

**Comment by zsun227** [comment]
Got it, thanks!
