### ISSUE TITLE
How to open .csd file

### ISSUE THREAD

**Issue by Hartej47** [A2Zadeh/CMU-MultimodalSDK#54]
Hi,
Thanks for sharing CMU-MOSEI dataset .csd files. Could you please tell me the way to open .csd files.

**Comment by A2Zadeh** [comment]
Hello, 

You can open a .csd file by creating a dataset and putting the local directory as file for computational sequence:

`mydict={'myfeatures':'myfile.csd'}`
`mydataset=mmsdk.dataset(mydict)`

This is the standard way of doing it.

**Comment by Hartej47** [comment]
Thanks Amir Zadeh

**Comment by XinyuLyu** [comment]
Hello,
I have the same problem. I try your method, but find there is no attribute named 'dataset' in mmsdk. Then I try to call mmdatasdk.dataset, and I find the object is not callable. Finally, I try to call mmdatasdk.mmdatatset, but it only check the interity of the dataset without opening .csd files.  Can you help me?

>>> import mmsdk
>>> from mmsdk import mmdatasdk
/Users/xinyu/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
>>> 
>>> mydict={'myfeatures':'CMU_MOSI_OpenSmile.csd'}
>>> mydataset=mmdatasdk.mmdataset(mydict)
<Success>: Computational sequence read from file CMU_MOSI_OpenSmile.csd ...
<Status>: Checking the integrity of the data in <OpenSmile-emobase2010> computational sequence ...
<Success>: <OpenSmile-emobase2010> computational sequence data in correct format.
<Status>: Checking the integrity of the metadata in <OpenSmile-emobase2010> computational sequence ...
<Success>: <OpenSmile-emobase2010> computational sequence metadata in correct format
>>>

**Comment by XinyuLyu** [comment]
Hello,
I have the same problem. I try your method, but find there is no attribute named 'dataset' in mmsdk. Then I try to call mmdatasdk.dataset, and I find the object is not callable. Finally, I try to call mmdatasdk.mmdatatset, but it only check the interity of the dataset without opening .csd files. Can you help me?
<code>
import mmsdk
</code>
<code>
from mmsdk import mmdatasdk
</code>
<code>
mydict={'myfeatures':'CMU_MOSI_OpenSmile.csd'}
</code>
<code>
mydataset=mmdatasdk.mmdataset(mydict)
</code>
#log
Success: Computational sequence read from file CMU_MOSI_OpenSmile.csd ...
Status: Checking the integrity of the data in <OpenSmile-emobase2010> computational sequence ...
Success: <OpenSmile-emobase2010> computational sequence data in correct format.
Status: Checking the integrity of the metadata in <OpenSmile-emobase2010> computational sequence ...
Success: <OpenSmile-emobase2010> computational sequence metadata in correct format

**Comment by XinyuLyu** [comment]
<code>
mydataset.computational_sequences
</code>

Thank you. And you mean the following results are the contents in the csd files?
#log
{'myfeatures': <mmsdk.mmdatasdk.computational_sequence.computational_sequence.computational_sequence object at 0x10b3165f8>}

**Comment by A2Zadeh** [comment]
Correct. Now simply use that as a dictionary to see the keys and then access each video contents.

**Comment by XinyuLyu** [comment]
Sorry, I am not pretty sure how to use the address to find the keys and the values. Can you explain more specifically or give me some codes about it?

**Comment by A2Zadeh** [comment]
Sure,

Here is a fast version for features and intervals of a video 'vid' in computational sequence 'compseq_id'
print(mydataset.computational_sequences['compseq_id'].data['vid']["features"].shape)
print(mydataset.computational_sequences['compseq_id'].data['vid']["intervals"].shape)
I will update the readme with the new one soon.

**Comment by XinyuLyu** [comment]
Thank you very much! By using your method, I found a list data like belows. 
<code>>>> mydataset.computational_sequences['myfeatures'].data</code>
<code>>>>{'03bSnISJMiM': <HDF5 group "/OpenSmile-emobase2010/data/03bSnISJMiM" (2 members)>, '0h-zjBukYpk': <HDF5 group "/OpenSmile-emobase2010/data/0h-zjBukYpk" (2 members)>, '1DmNV9C1hbY': <HDF5 group "/OpenSmile-emobase2010/data/1DmNV9C1hbY" (2 members)>,...}</code>

And with the code you have given, I also found the shape of each elements.
<code>>>>mydataset.computational_sequences['compseq_id'].data['vid']["features"]</code>
<code>>>>(13, 1585)</code>

<code> >>>mydataset.computational_sequences['myfeatures'].data['03bSnISJMiM']</code>
<code>>>><HDF5 group "/OpenSmile-emobase2010/data/03bSnISJMiM" (2 members)></code>
But how can I get access to the file and its content like "/OpenSmile-emobase2010/data/03bSnISJMiM"?

**Comment by XinyuLyu** [comment]
Hello,
After searching references online, I find the file may be stored as the NDF5 format. But I can't find the target dataset file with the address shown here <code><HDF5 group "/OpenSmile-emobase2010/data/03bSnISJMiM" (2 members)></code>. So, can you help me find the HDF5 file name or the reachable address? I want to open them with the contents. Can you help me with that? Thank you so much.

**Comment by A2Zadeh** [comment]
Hello,

/OpenSmile-emobase2010/data/03bSnISJMiM has two keys inside: "features and intervals". Both of them are numpy arrays which have the beginning and end of an intervals and the features associated with it. We are still developing the SDK so we will create detailed tutorials soon :)

**Comment by XinyuLyu** [comment]
Thank you so much!

**Comment by Thani011** [comment]
Hello 
Thanks a lot for the support .
I followed the same steps suggested by you above . I am able to print the data in form of sequences as follows :- {u'BioHAh1qJAQ': <HDF5 group "/Opinion Segment Labels/data/BioHAh1qJAQ" (2 members)>, u'iiK8YX8oH1E': <HDF5 group "/Opinion Segment Labels/data/iiK8YX8oH1E" (2 members)>

Can you please guide how to decide and select data for train,valid and test set .
I mean how decide and select to which [vid_id][seg_id] will be for training, testing etc.

I am using the CMU_MOSI data and created a MOSI class as follows:-
import mmsdk
from mmsdk import mmdatasdk

dirc={'embeddings':'CMU_MOSI_TimestampedBERT.csd','facet':'CMU_MOSI_VisualFacet_4.1.csd','covarep':'CMU_MOSI_COVAREP.csd','labels':'CMU_MOSI_Opinion_Labels.csd'}
mydataset=mmdatasdk.mmdataset(dirc)

class MOSI:
	def embeddings(self):
		return mydataset['embeddings'].data
	def facet(self):
		return mydataset['facet'].data
	def covarep(self):
		return mydataset['covarep'].data
	def sentiments(self):
		return mydataset['labels'].data
	def train(self):
		return 0
	def test(self):
		return 0
	def valid(self):
		return 0

Thanks
