### ISSUE TITLE
where is ICT-MMMO dataset...

### ISSUE THREAD

**Issue by Eurus-Holmes** [A2Zadeh/CMU-MultimodalSDK#55]
where is ICT-MMMO dataset...
how could I download it...

**Comment by Eurus-Holmes** [comment]
fine...thank you

**Comment by A2Zadeh** [comment]
@Eurus-Holmes, we made a decision to not include ICT-MMMO in the SDK since maintaining too many datasets is challenging. ICT-MMMO will only stay as part of old_processed_data. I can however share the zip file of the entire dataset in case you are interested in putting it in SDK format.

**Comment by Eurus-Holmes** [comment]
@A2Zadeh hi, thanks for your update, and if you could share the zip file of the entire ICT-MMMO dataset I will very appreciate it.

**Comment by A2Zadeh** [comment]
@Eurus-Holmes The raw files for ICT-MMMO as well as the processed features are available for download within the SDK readme. I am closing this issue, but feel free to open it again.

**Comment by Eurus-Holmes** [comment]
@A2Zadeh I see. Thanks for your work!
