### ISSUE TITLE
What does the first dimension of the dataset represent?

### ISSUE THREAD

**Issue by XinyuLyu** [A2Zadeh/CMU-MultimodalSDK#56]
Hello,
After I follow the codes for Word Level Alignment in Readme, I get the dataset contents of the CMU-MOSI shown as below. But I am not pretty sure about what the first dimension of the dataset stands for. 

For CMU_MOSI_OpenSmile.csd / For CMU_MOSI_OpenSmile.csd / CMU_MOSI_TimestampedWord Vectors.csd / CMU_MOSI_Opinion_Labels.csd: 

1.There is a lot of ID like' 03bSnISJMiM', and I want to know what the IDs stand for, different videos or something else?
<code>{'03bSnISJMiM': <HDF5 group "/glove_vectors/data/03bSnISJMiM" (2 members)>, '0h-zjBukYpk': <HDF5 group "/glove_vectors/data/0h-zjBukYpk" (2 members)>, '1DmNV9C1hbY': <HDF5 group "/glove_vectors/data/1DmNV9C1hbY" (2 members)>, '1iG0909rllw': <HDF5 group "/glove_vectors/data/1iG0909rllw" (2 members)>, '2WGyTLYerpo': <HDF5 group "/glove_vectors/data/2WGyTLYerpo" (2 members)>, ...</code>

2.For CMU_MOSI_OpenSmile.csd: 
I know the second dimention represents different kinds of features. But what does the first dimension means? I guess it stands for 13 sentences, 13 sections of vedio clips?
<code>>>>mydataset.computational_sequences['myfeatures'].data['03bSnISJMiM']["features"]	</code>	
<code>>>><HDF5 dataset "features": shape (13s/words, 1585), type "<f4"></code>	

3.CMU_MOSI_VisualFacet_4.1.csd:
What does the '5359' stands for? In other words, what is the basis of division for the dataset?
<code>mydataset.computational_sequences['myfeatures'].data['03bSnISJMiM']["features"]</code>	
<code>>>><HDF5 dataset "features": shape (5359, 47), type "<f4"></code>	

4.CMU_MOSI_TimestampedWordVectors.csd: 
What does the '491' represents? 
<code>>>>mydataset.computational_sequences['myfeatures'].data['03bSnISJMiM']["features"]  </code>   
<code>>>><HDF5 dataset "features": shape (491, 300), type "<f8"></code>

5.CMU_MOSI_Opinion_Labels.csd:
I find that the dataset of CMU_MOSI_Opinion_Labels.csd shares the same dimention with the CMU_MOSI_OpenSmile.csd. Is it means the opinion labels only match the acoustic datasets?
<code>>>>mydataset.computational_sequences['myfeatures'].data['03bSnISJMiM']["features"]  
<code>>>><HDF5 dataset "features": shape (13, 1), type "<f4"></code>

**Comment by A2Zadeh** [comment]
1. That is the unique id - it can be anything. In our case that is the youtube id. You can directly put that in youtube and watch the clip. 

2. I will have to look into that. It should be 1 x 1585 since OpenSmile in this case gives one feature vector per video. In short, first dimension means how many feature instances were extracted for each id. For example if the video has 300 frames, then Facet gives you 300 feature instances. 

3. 5359 frames. Each frame has 47 features extracted. Please look at the "intervals" as opposed to "features" to see when the frames happened.

4. 491 is the total number of words uttered in the video. Again if you look at intervals you will see the word utterance start and end times.

5. No, everything is the SDK is timestamped. So as many frames as fall in the intervals of a particular annotation, they belong to that annotation. So for example if annotation a1 starts from s1 and ends at e1, then whatever features from any modality falls in between, it belongs to a1. 

Happy to answer your questions, let me know what else I can help with.

**Comment by XinyuLyu** [comment]
So, you mean my OpenSmile dataset seems to be wrong? And the first dimension of it should be 1?  And can you provide the video name on Youtube, for I can't find them with the ids?  Thank you so much.

**Comment by XinyuLyu** [comment]
I am quite confused about  '1 x 1585' for 'OpenSmile' dataset, and I found the first dimension for both features and intervals of all ids are not 1. And if it comes as  '1 x 1585', it means for each video there is only one feature vector. In that case, there is only one interval data (1,1585) in 'OpenSmile' dataset per video. It does not make sense to me.  Could you help me with this?

**Comment by A2Zadeh** [comment]
So for OpenSmile there is one vector per video segment. Each timestamp extracts 1585 features. So for example, there is 2200 videos in CMU-MOSI and there is 2200 of such 1x1585 features. We plan to release OpenSmile features that are more like COVAREP (every 10 milliseconds there is features). Did that address your question?

**Comment by XinyuLyu** [comment]
Thank you so much!  I wonder why the first dimension of my OpenSmile dataset for all video clips are not 1?

**Comment by XinyuLyu** [comment]
Hello,
I have followed the codes for Word Level Alignment in Readme several times, but I found the dimension of cmumosi/CMU_MOSI_OpenSmile.csd('03bSnISJMiM') is (13,1585) and for cmumosi/CMU_MOSI_Opinion_Labels.csd('03bSnISJMiM')  (13,1). So, could you look into the datasets to find out the reasons? It is very important for us. Thank you so much!

**Comment by A2Zadeh** [comment]
Yeah that means there is 13 segments in that video that have annotations (1 dimensional) and 13 of them (in this case the same ones) that have OpenSmile (1585 dimensions). Does that answer the question?

**Comment by XinyuLyu** [comment]
Many thanks, by the way, are the video segments divides based on the sentences?

**Comment by A2Zadeh** [comment]
Of course. For MOSI it is opinion segments (please check original paper for annotation scheme), for MOSEI it is sentences, for POM it is entire videos.

**Comment by kushagrajain11** [comment]
@A2Zadeh I noticed that the opinion_labels intervals are not starting from 0 in some cases.
Example 
`>>>opinion_labels['03bSnISJMiM']['intervals'][0]`
`>>>array([52.732655, 56.045124], dtype=float32`
What about the labels for the initial 52 seconds of the video?

**Comment by A2Zadeh** [comment]
@kushagrajain11 CMU-MOSEI has annotations for random sentences in the videos. The first random sentence from this video happened to start at 52.732655.

**Comment by kushagrajain11** [comment]
@A2Zadeh Im still confused a little bit. For the same video ID the words start from 0 sec. These are the words and intervals for the video ID 03bSnISJMiM. But the opinion lables start from 52.732655. Is there no opinion label for the initial 52.732655 secs of the video?
`sp [0.00861328 1.76572266]`
`oh [1.76572266 2.15848828]`
`sp [2.15848828 5.22481641]`
`this [5.22481641 5.88631641]`
`sp [5.88631641 6.83033203]`
`quality [6.83033203 7.64342578]`
`is [7.64342578 7.80191016]`
`sp [7.80191016 7.88459766]`
`horrible [7.88459766 8.69080078]`
`sp [8.69080078 9.88287891]`
`ok [ 9.88287891 10.22051953]`
`well [10.22051953 10.69597266]`
