### ISSUE TITLE
Only half of the labels are found in MOSEI.

### ISSUE THREAD

**Issue by Desperado000** [A2Zadeh/CMU-MultimodalSDK#58]
I found that there are **11875** labels in MOSEI. However, the original paper mentions that there are about **20k** sentences in the dataset. Please tell me if I am wrong or where I can find the remaining labels. Thank you for you time.

**Comment by A2Zadeh** [comment]
@Desperado000 Hmmm interesting. Let me look deeper into this issue. There should be around 21k labels. Let me look into that tomorrow.

**Comment by Desperado000** [comment]
@A2Zadeh Do you check the label? Than you~~

**Comment by A2Zadeh** [comment]
@A2Zadeh I just solved the issue. Pull the sdk again and you will be able to see two sets of labels when you download the labels: one for sentiment and one for emotions. Let me know how it goes.
