### ISSUE TITLE
Features Difference Between Old Version and New Version SDK

### ISSUE THREAD

**Issue by Desperado000** [A2Zadeh/CMU-MultimodalSDK#61]
@A2Zadeh The features in old version SDK  seems different from the new version. Will you release the old version features in new version SDK format? Because  models trained on new features can not compare with the pervious models directly. Thanks.

**Comment by A2Zadeh** [comment]
@Desperado000 at this point in time features in previous version of SDK are officially discontinued. We do plan to release a version of old SDK, but we will no longer use them. Some of the features were from older version of feature extraction methods. We had some issues with consistency as well for some of the earlier datasets such as POM. The new version of SDK solves all of the issues. All of our models will be built on top of the new SDK, so there will be ample number of baselines in our papers from now on using the new SDK. Furthermore, for comparison to our older approaches, we will run those approaches again for the next upcoming papers on the standard folds. Of course you can implement the models yourself if you publish your work before us. 

As for the previous models and how those results were achieved, we plan to release the codes soon. The code may not be the cleanest but it will work given all the files that I will share. Please stay tuned for that. I just added it to the next_steps.md.

**Comment by A2Zadeh** [comment]
@Desperado000 let me know if any severe inconsistency happens between the too
