### ISSUE TITLE
inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by twoertwein** [A2Zadeh/CMU-MultimodalSDK#62]
Tabs and spaces are inconsistently used in `mmsdk/mmdatasdk/dataset/dataset.py`.
```python
  File "~/git/CMU-MultimodalSDK/mmsdk/mmdatasdk/dataset/dataset.py", line 172
    ref_copy=ref.copy()
                       ^
TabError: inconsistent use of tabs and spaces in indentation
```
If you prefer four spaces instead of a tab, I can create a pull request for that.

**Comment by A2Zadeh** [comment]
Thanks for raising this issue @twoertwein. At some point during development I was doing some mac checks and that is the byproduct. Thanks 👍 . Or you could run PEP on it :). If not I can do it later.
