### ISSUE TITLE
ACL 2018 multimodal challenge datasets

### ISSUE THREAD

**Issue by rosannamilner** [A2Zadeh/CMU-MultimodalSDK#65]
Hi @A2Zadeh, how can I find the official train/val/test clip IDs and segment numbers which were used in the ACL 2018 multimodal challenge? I'd like to compare my results to other people/papers - thank you!

**Comment by A2Zadeh** [comment]
Hi @rosannamilner, here is the link for the folds. https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/mmsdk/mmdatasdk/dataset/standard_datasets/CMU_MOSEI/cmu_mosei_std_folds.py

**Comment by rosannamilner** [comment]
Great, thank you very much!
