### ISSUE TITLE
data missing in MOSEI?

### ISSUE THREAD

**Issue by ntubertchen** [A2Zadeh/CMU-MultimodalSDK#67]
Some folds are not found in csd file

I download data from cmu_mosei.py and use folds name cmu_mosei_std_folds.py provided in standard_train_fold to track the training set to use.

However, some fold seems to be missing.

Following is the code I use to track the missing folds.

mydict={'emotions':'CMU_MOSEI_LabelsEmotions.csd', 'sentiment':'CMU_MOSEI_LabelsSentiment.csd','words':'CMU_MOSEI_TimestampedWords.csd'} 
mydataset=mmdatasdk.mmdataset(mydict)
standard_train_fold = [...]# provided in cmu_mosei_std_folds.py, too long that I didn't copy it
found = 0
not_found = 0
for fold in standard_train_fold:
	if (fold in mydataset.computational_sequences['emotions'].data):
		found += 1
	else:
		not_found += 1
print (found,not_found)

**Comment by A2Zadeh** [comment]
@ntubertchen thanks for raising this issue. This shouldn't have happened for labels. Can you send me the list of videos not being there? specifically how many found and not found. Thank you.  

For the timestamped words, there are missing videos due to maintenance. Around 530 videos are currently undergoing feature re-extraction. So that is normal, we are preparing for the second workshop on multimodal language.

**Comment by ntubertchen** [comment]
training data not found in emotion label

['hh04W3xXa5s', '81406', '72tXTrSXoMk', 'hSgKOKK3L8M', 'YVHJpAROBvQ', '127470', '-iRBcNs9oI8', 'sLaTZtL0ZIk', 'gZF-YNQHqwI', 'Z3fcd1wdzr0', '81538', 'CHh6hWo1AFE', 'sw-smuVRByI', 'UTNP1roJV3I', 'flGZteJUNYU', '57618', '3gA34VxBijI', '6TKaGMkO69E', 'Zr3psuFQoDY', '3f6xCzKx9CA', 'ogGweZUAVtU', 'LQnXVd-PR_Y', '254298', '70710', 'MmJD4KBT0nk', 'RadU51t1kL0', 'T1icdxz0TNs', 'iREkcXde5ds', '40181', 'k1ca_xbhohk', '41692', 'PHJ8eybXJdw', 'dqragS38hCk', 'FMif4HMBZjo', 'N188QSyfmeQ', 'PohW-isYMK0', '0vXaXWx7Rvo', 'kf3fZcx8nIo', 'lTfsqoo-jKg', 'Sir2QeCh4B0', 'UK_IXtJ2BqI', 'xsiHAO0gq74', 'wd-LTpCtAzw', 'mud6tEqFiEM', '34-ogj6rh6w', 'DGeBPk1op3E', '272375', 'C3lDRFu1ZcI', 'fhY2vbnjuWY', '210238', '-wny0OAz3g8', 'wVdoIjg3ZFQ', '72385', 'FWBCTZiijEM', 'bUFAN2TgPaU', 'S8yP6lBOdKo', 'bVhWpCvpSs4', 'Wo1RxRjXyYw', 'iWBx0CP9JqA', 'SMr2DprlLu4', '08d4NTXkSxw', '0SfejBuLgFo', 'pbFwuNCQlH8', 'IAmZ5iWHxw4', 'ytXVSpPfKwA', 'SH0wXyhsx9s', 'vM7m581tHn0', '4CKhrjuuofk', 'aNOuoSVlunM', 'jZTe5cbwwEE', 'HD17J-FvROQ', '81615', '9zWeMrfr-l0', 'HUOMbK1x7MI', 'w8TXP0iz29A', '5OLO6zEbrVw', 'ai7G98thPpk', '44780', 'olcPEN9x5VY', 'G8p4QMjLUXI', 'c7xUcM68IFE', '3u_Joh0WJdw', 'w1MxXu5D7ho', 'jlCFLG6rKKY', '257531', 'NDMAVMZyISM', 'JkHxzOWOLfs', '238889', 'RdOc70IrjJo', '5VKMctXBN9M', '44MVdpDEQJs', 'Va54WZgPTdY', 'kmAisuAFckw', 'YcyHQQXGXWA', 'OEMSGahoCmM', 'ipLoS44xfO4', '54CM1_GA-uw', 'eY64P27khzk', 'nHMHePX9WoU', '230252', 'OwYfPi9St0w', 'n2BuwHbdilY', 'p18PVgfxook', 'KF5wgQPp2yc', 'fI9KptYFZeg', 'fbHlBmq7Ipo', '298736', 'R0uRDh-engU', 'o4b7hjQwpv0', 'OAV6KKf60bQ', 'x5xF4yu9Bos', '238645', 'Gmhi58erY6k', 'GICVzJMDfv0', '129733', 'h7p5URoookk', 'frNJdG0GkYw', 'dYyg91d7zjY', '7EWOMjaKlus', 'N3QuD26DuCI', '8F1mj-XT6KA', '3aIQUQgawaI', 'jT3FSTBA8Us', '23YlZoucbyM', 'BZOB3r5AoKE', '7rMLN0KKE5k', 'nxksB2kDJ6o', '6rkV4QRcVnk', 'asWraTfIqq0', '270449', 'So3bPzg2bq0', 'UUukBV82P9A', '261902', 'qDIh6YNbIMU', 'QoIsjc4-GIg', 'Tiq67-bAV3M', '98442', 'iceSGs0MXaA', 'A8plGi4rbxM', 'Zo8jCDGMWjw', 'Wfn7XvSEwUA', '128752', 'gm4l099casQ', 'L382XZ6iZmM', 'X0jMZoxUL2A', 'z-bupzylxEc', '7hSWYI99-24', 'nmWplIQhvoA', 'UtuTyW9pUN8', '83859', '101851', 'qbIajpM7U3Y', 'AjgDuPEp9sI', 'kU6YY2z7z0I', 'X7-Gbk8gAD0', 'yuwvVTnsDjc', '4EEru3cZwXo', 'xomMHflvVDw', 'ahcAFnY6iAY', '216007', '3DOrdP4H8SA', 'AGM-hNupJik', 'vM3YB7LmMq4', 'Dws8ZrzF7xQ', '9zBj8VkRBpE', 'wj3ur4fsiN4', 'DbAppk7xT0Y', 'cnllFPRyBFs', 'EoC83JhkCAw', 'rv1gp0wEhI0', 'HByf7qiO-Kg', 'aFjMWlR1QAY', '424vOT3Nnyk', '38374', '266852', 'RKP6j28FCWE', 'PQYmOknHA4c', 'q4hP2j7oewo', 'XVSDfgstFUQ', 'W-ptEZFARVo', 'bMuoPr5-Yt4', 'gAMbkJk6gnE', 'hlYDicOj2m0', 'XPoY4LD-A1I', '9sAoeFTKILY', '220134', '1ESU5ONMMxs', '256935', 'GTGtVdAuyRc', 'JzydLJw6y6o', '69NtV79qgOg', 'q-0gu48ClF4', 'L8VjQM9HQfs', '4qVvLLFEYnk', 'zKNAu2CCeRs', 'fzuTEKwNS94', 'v45zoIrjoTo', '9K5mYSaoBL4', 'bCDfIJ12oqM', 'k8NgVOCDYKM', 'SaNXCez-9iQ', '261267', 'n-sgVVTE9Io', 'SGsiGz2fdpo', 'GJyzeK-Cn-0', 'QEG_hkJsaYc', 'JYdfUNjyYxo', 'wtCKzu8eVJ0', 'mxa4KXSz9rw', 'YJJoYkFPmds', 'wvMA0r3esw8', 'Zg9DKOHJdw8', '3paDwuRQP1w', '215259', '_26JmJnPKfM', 'RST6PgpsLws', '0BVed2nBq1g', 'dbpGH5iP0GE', '89951', '233366', 'ULkFbie8g-I', 'PbyI-sUzLZY', 'SCXp4l0CO4s', '216857', 'RdExUaEIWIk', 'damyXH7mBic', '238683', '22880', 'Cb8ay6WtJuM', 'uBgRo9tnv-I', '202810', 'Rugd2NMu4bA', '130426', 'kY64gXOapYk', 'MpuWcGn2Lcg', '119348', 'YRmjALBdTdE', 'FylhSeozvG8', 'cSrM5mHACmA', 'znNt--6itO4', 'RE-LIPOFnrE', 'RvIohowRPAk', '2-4autDbHVQ', 'VjAvqFXEmmk', '0WIwQgH4lKg', '140293', '7sgAWvbLtiM', 'B1PzCwfgXyU', '6ng8CZ0ULK4', 'JW2HHfQiGVs', 'uQds2dN1AiM', '_ZlF5Q9W1DM', '231025', 'HgDdU_RB9UA', '128949', '2vX-ZRQQDwo', '18QjfdhJEM4', '74870', 't4-ZulW5np4', 'wfLrS6CdFs4', '219310', 'L6pg3DQKoH4', 'oj7A8mpuBeQ', 'xNYsfeSgDCQ', 'afDJvn5nmtY', 'YY2yjEEoB3U', '1F0qH0EEBfo', 'UPghCarcnMc', 'DaXkixKFEvE', 'j7fRIGphgtk', '4VA4kqMnEqA', 'XCyngF93SmU', 'tdIZZ9v0IGA', 'erBIIKA6r5Y', 'VoETCD8fBLI', 'DQ7QKE3hzVg', 'pf6HYOOwfGE', '33439', '4hEWns7JBg0', 'qrI7XCKRFNk', '92tWNUhG9DY', '30162', 'RAiO_rChmdU', 'etPDgRjrnJ8', 'LZl9Sj1safM', 'wxxqXK9x-64', 'otna1VHHCow', 'wlrb0HyIs-Q', 'YF3mDOuF46M', '8ovb-GaZ3QE', 'OxyQSJMvWBo', 'W-pA0lOGLR0', 'fjE2EZKgQm8', 'F5SGdvSRJmo', '110766', 'JdFaSggG58c', 'Q2uHXKA8cq8', 'mRnEJOLkhp8', '225343', 'sPxoGNvnVzg', 'jPf0LjZAS14', '206606', 'Rse6laKf1i8', '50453', '8-Hi9NmF4rM', 'S_tGoxSEh5Y', 'dsob2MgUPpA', 'ta26Z2YEVMQ', '0FA32bEZ6xI', 'gzZ8NTeTzRs', 'XyBU_gZtU0M', 'UKVwc6I06x8', 'AVScVfLgNmw', 'MnFRVJtHAeo', 'x9E8yaFCX0Y', '282560', 'JCg26b8EO48', 'ATfnMuJJDkk', 'uea5xJZygsc', 'e0ltF8zpEcw', '6Vg10LxmWUY', '_iy7ftq27xE', '121358', 'WHUHTmtBJWU', '0nJrksJ7azM', 'Az3e1Opu0LE', '125708', 'REkPZ77s3Vc', '93821', 'khw3YCTFLfs', 'K_5u2Wh_wGk', 'cZVM4svwE90', 'g99kISQbyuI', 'ep3IasggD3k', '0rE8jEvQW_I', 'XEZ7e4pf1xE', 'rexJoy4RMdY', 'IW7IssCKgmI', 'sFLTjqVS7AE', '295793', 'WovurMxG2Aw', 'Sglx7douG_4', '984VkHzXl8w', 'XQxnAPleuCE', 'obnOnuzb-Xw', 'wI7DDCRh4Nw', '10223', '1JQ9UCBEmCU', 'VN1IPN1TL3Q', '40260', '80914', 'O8IJh_L0EfM', 'Cj7R36s4dbM', '38019', '4wuug3-5cWo', 'uYzZB4ccG1Q', 'xPhlDO-2Foc', 'kkaX3okuvjI', 'TJelZLbfT2A', 'krHZuqfXrPU', 'gRAmIaSlm80', 'cyu1HhakSaQ', '106514', '1tQOvm5eQOA', '218708', 'vXABB4tBBUU', 'mRPIse3OO74', 'HqtvFTa29L8', '6YNAmRjpxlA', 'LUKIYWa0UGA', 'TUzD45ghy4k', 'nDXKvarLEOM', 'a8WV5KEMKSw', '136215', 'JMzilFvwNXE', 'SSNrLu-eZiM', 'PUIsiLk8etk', 'ou6S6fbfBWU', 'wQkNqbrAlB4', 'bcns0Gu66D8', 'jNdvceZ4etc', 'gjEYmdWrBLM', '88245', 'BnWvk0YRgE4', 'o7vcTMAX9fQ', 'ieWQdiQAh4M', 'SLi2gT5H6m8', 'mHIvH6Nnrls', '7wiaDbpiAQ8', '4wdeBJ39Cuw', 'oGnKsroR0R0', '125845', 'tXxXhGD1aMo', 'jhb6SV2dQzg', 'KPeos6f4HuQ', 'm8tzdtrgFUA', 'XAazxiP6tP0', 'o2bNnLOEEC0', 'YLA7h1RTa9w', 'rwe-hBNpzH8', 'jbJF3aphcP0', 'OdKp0hYomgs', 'Zs8x712Y-CM', '80866', '94ULum9MYX0', 'veHYwR7ge6Y', 'nsLACXjD4KU', 'sqADHmnM164', 'RLHZ6xtIWSM', 'cMUS4nhcKCQ', '78577', 'po5jCjnxW1w', 'nM5S3xxNOlQ', '47472', 'ZQuGizjoCTY', 'xXIq7YPkdUQ', 'yt9GpittX4U', 'kddCewAsxfA', 'YjNYBBs1AZw', '108793', '264446', 'FmE9BtTmxnE', 'fSOVk2cS-sY', '53742', 'mMeGgB9-hSE', 'qFppeQvdfxI', '4Q7OkrJLzAc', 'BMhG11CXgww', 'QLEOYF7Mju0', '4iw1jTY-X3A', '78Ncka6CY70', '9bAgEmihzLs', 'ce1ObTPlI38', '8XODJwsvBa0', 'Rw2pzFGosmw', '43371', '2HmBM3GGTlg', '193291', '0EAAfLCQabY', 'MBDZbACupsc', 'rzsk_IvI7bQ', '241172', 'yrIXBklJ5YQ', '75938', 'wOjnqud5GBA', 'kx544gnOZB0', 'oK951Y2N_k0', '276217', 'mw_ZwML0SbY', 'Y6zyM1nDhN0', 'QkMTYY69JYQ', 'hjBQmIWiWgw', 'C2xNDBU2Z0s', 'C74-of1rjg4', 'kzmaKnujN64', 'lzVA--tIse0', 'z6E-ocntPo4', '106077', 'ADYia28RrFU', 'MroQfGehC84', '2LpVvLemgvw', 'cjgq9d8Zn9g', 'w4xIyGs-3wc', 'aI1tdJPHz2I', 'c5AJbOd794U', 'EOkdFMw0pmk', 'D-DqVICJXBU', 'dLmtsRyRH4s', '247382', 'Q7nhtfkIPN4', 'dZK01jhM27k', '251417', 'zx4W0Vuus-I', 'lKTeLK8nq8w', 'RTzDzj4NxIM', '7UlSX-syPeo', 'L5a2ijeWpUI', 'IDVbPEket6U', 'JW3OfSCZlhc', '25t8nrkUfRY', 'MJnc4GUhUuY', '5QXHyL3BMto', 'oDznO5w3v0U', '288766', 'pAclBdj20ZU', 'efLrpnuLwyU', 'C8Fhlk-eczU', 'pjWLxORDDP4', 'YVBsDJtAbk4', 'VcZffwwL0bw', '31197', 'xbl7bU5PGBs', 'l8LTcZJ-_8k', 'BBSVLGf7zPI', 'X3p50qqFW_w', 'jfSGWBfVNBI', 'MFrwi-RibUk', 'TBwetweXRb4', 'hCFV5VLgS0A', '1sJjdaXXuJg', 'wUf6AvCMHbQ', '1CjUHNYzW1E', 'FLyWn2DCci4', 'WaaSYRPwQBw', 'QbJiphIpzYc', 'TxRS6vJ9ak0', '251646', '_PKP676ez2c', 'NZtIGzAzJZM', 'gfHrSg3BwiQ', '4Z47qIrVil4', '45175', 'JlmpDdm1A1Y', 'soqnBdPOwoo', 'ge071m9bGeY', 'QWzIJuhLLrc', 'mN1Z5xEOy10', 'dbH51F5Zqi4', 'kRsA87VU6EQ', 'S6S2XL0-ZpM', 'gvrfI9e5xHQ', 'dXMAS2tIknw', 'K9U2TAF9DDY', '5qQs9Cfydo4', 'GRFXnnrQaB4', '260011', 'q3QUybiOYeU', 'FmIS69vB12I', 'd99mfGIenCo', 'kKkZihSbxF4', 'n5J1ZkGUGnU', 'W-q9bPlMIVI', 'EHbZ2EeVags', '32j1yMF37hA', '7eWclVCXOtk', 'GMHW6XEO1ms', '4BoE-woHtwA', '37117', 'fTKe7E_4OCQ', 'WYSomBHdl4c', 'YodtMIsjM0c', '89787', 'Itqbc2TBXWY', 'Vw4-ae-ucHE', '106941', 'EfQoSpEZa0o', 'zPskvGHHQtE', 'MNLG4-diuYM', 'xfP0bm6Z-7E', '5Tqu1IXJjGY', 'PMH4mdJeojE', 'WMzvDL7b4sM', '1A7dqFxx8wU', 'xBsrNFxnnuY', 'XbolrpSc0KU', '130149', 'H26MMmrHTlQ', 'bJI7-LnKPH4', 'Wh6sht7xwqQ', 'SxbTZjZD0vU', 'TWMFQED1Myk', 't80DGfWJ3fI', 'ZiM_gkdFGJk', '79934', 'VAr7gJydnys', 'CdB8QBhFccs', 'cM1Zuji24dI', 'caLWajc18Y4', 'ltA1VF_DUSc', 'lo0R1mvjDT8', 'FdTczBnXtYU', 'WTF9xgqLIvI', 'NCJTV5KaJJc', 'MyfRrTjglm8', 'fDYZINwIs_A', '184784', 'jUKH63mltLE', 'Cd0JH1AreDw', 'vrgwwihTxVQ', 'SrMN3rwvCsE', 'PJlDO21zl88', '1o8Gy4J6WSs', '222116', 'Wx9nThz5z_Y', 'Ctc23Icfzvg', '112631', 'uxHBEfIhY-E', 'xw-Blnej8EA', 'A0aE2Gzym-M', 'b_SffSbPVJM', 'ctMCSUT2LlQ', 'vlnKSMw5v1o', '290088', 'u94VPxEIJPg', 'fB816aeHRFk', '4Yxe1_ohz7Y', '29044', '3OMgvtWNHp4', 'xvnFF0FiyS4', 'vRhj2bLo1ho', '257771', '6xvVFYR5di0', 'ooGB4BLK9PM', '241638', 'esnOE1LefKA', 'wEs7pJH2mqQ', '6IUj6jyoTl0', 'xlNDpmKgSIc', 'UkqTwAuA8jI', 'TbZPa_keawc', 'SmftC-VAfYQ', 'tnhRxo-g3Xw', 'wXuBJvzeC1Q', '27798', 'S_ISgjJR1bc', '74184', 'o1cRmT9qnOc', 'GeSTiDe1hG0', 'YQanVofsHoE', '51224', '224869', 'A4dzxgHDhF0', '55156', '88119', '4Q95Lg3Icho', 'kj63uF0RhW8', '4kF0U8kIMp4', 'gr9YU-UTJzQ', '0EphpADwdPg', '134252', 'j6R1NTrosuM', '244623', 'vqBRkjHWjXM', '122439', 'PybuzkS31J4', 'vwUBtNvjrU4', 'JMb18N7lQ0A', 'EGA6iulTr00', 'jnG9zog4NCs', '112604', '202431', 'aE-X_QdDaqQ', 'aiUq5xksJy0', 'nw6Kf3AtCz4', 'rC7qKZMKa0U', 'ku-dtUqCm2o', 'HxyfY7hsjOg', '15Wu4U2VPLw', 'jlW4Iep4mmE', 'A6R6J8SJtBc', '6zjv1TLqfF0', 'gjGL6YY6oMs', 'mgovo8VYtvk', '72017', 'cHrOisasWLU', 'IsAtAzltJNM', '8qCNtqjygW8', 'UeOIb6s0pVM', '213619', 'ZtuTCuh9C1M', 'QOxIdbNwpx0', 'DhXBaBOB4E8', 'jjb1cWmkhI8', '92221', 'DXQGngge7vU', '6G8JJ69aN6o', 'gvjQ1XfMA_g', 'P0WaXnH37uI', 'wz3nVBPVgIA', 'TBCjKGYBNIo', '2-EJz4RG4g4', '255852', 'mjYeEikLR8I', '2qKajMu7Vhc', 'JHW3nD6flgU', 'LL02UFLfQKo', 'zg-ZIxVsBbQ', 'YWjTWl0oNLk', '-UuX1xuaiiE', 'yKdIZR5xfcc', '48BD8qjClfE', 'a5CSKvCAhbs', 'nQ7txb1MtG0', '1W38PnuWIkM', 'JcmqmLaL_MQ', 'mkkoJ2iVbGs', 'j9mRv472dq0', 'QP2CjKap818', '6MYUY5tC2Us', '49358', '5tV5rZZJDCE', 'KJyz9fCt7Is', 'JGEEA_JVriE', '56006', 'eJwZfdtlks8', 'MsjnLoTKAXo', 'oANUXY3xXKM', 'F59hwsm4Ld0', 'e0hYEr848TE', 'hASTLbFHrEs', 'dEXSb0CfodU', 'rB6WmWvvyxg', '34346', '76124', 'dZolFNqR-hA', '83310', '-mJ2ud6oKI8', 'U2Ydtq6qvL0', 'ELtbrO8FbuI', 'hlBOP5NskhM', 'pwj9YeMJC08', 'c6wuh0NRG1s', 'dOSyvhYsfFo', '-mqbVkbCndg', '0mXv97u2OCM', 'zR-kKDaSDmE', '201582', 'badtXoOJaf8', 'UfLMdSGGQVw', '244829', 'WygyVNL_qdE', '8f_lBxZgDb0', 'DtwbwyfajnI', 'zFTuwjr3xq0', '52068', 'k4T6GaDrcjs', 'XcHLB-qfv5M', 'bkP-BNW4oMg', 'dQ56b0bqmc8', 'aiJg0jtIHOM', 'O2CEvvYWWbU', '6qmReTSoz0E', 'QzdEjKQFisQ', '5RVF_3YBUVI', 'uWW1ejwFURI', 'c9jD33baJ60', 'ZZzdvUdOTww', '9dFEGb_RfwE', '8xfW_azeNPk', 'gU7McujYYPY', '0bsTzavb-AE', '48u68AzcWvE', '0DBfvvIVmqY', '139006', 'GxcOSmJAyYQ', 'snVkfJKvjwk', 'ixQbCXLUUj8', 'o63doZKEIds', 'LpbSYaPRTqI', 'E0g6nae4Ae4', 'P3QEOJWxXI8', 'WUeSV0Z23Kg', 'aE7sckIAWuw', 'YAYfMkxhRiQ', 'nD1R4UedEDo', 'nGah7qST1dI', 'TSDC7CCyeGY', '0OC3wf9x3zQ', 'XFJQJb0yaKY', '0YdYFtVdlWE', 'd0QNH2vcDgU', '194625', '4AQC7_uCuEE', '267255', '267252', 'zsRTbbKlsEg', 'kqXpf26EL-s', '39lcRCFvV-s', '120vnZnmhq4', '-WXXTNIJcVM', 'HfLVQZLvcH8', 'FMW6diQ9rMo', 'LHC7ZKJy4Zw', '250430', 'L1gXZVU6AE4', 'Gv0kKbfwPpI', '273171', '0Svu5BldR5A', '7ZzbemE4QEE', '96361', 'jFpRdhl3fgw', '94215', 'S9PDgK7fpJI', '-HwX2H8Z4hY', 'VCIe-4p0xoM', 'ExDLNkDVsxY', '1mHjMNZZvFo', 'ZJGzEeDXbyM', '0W4WsjhDgUI', '15ktF-6wutk', 'NOl0v54DaXo', 'RgubFcmvgDE', 'xqcqieV0Rn8', 'F4OhXQTMOEc', '-NFrJFQijFE', 'FcAgbLF6__s', '140317', 'J3JU1zBQ4RM', 'VWik5oKP6IU', 'OBaMn1-x7jQ', '294178', 'YRbtXb9fWmI', 'laxadgca3Fo', 'MTU_thei3-c', 'ihuGFUrzD30', 'qJZlp9uxoTU', 'R5a3TP-l_n4', '236399', 'bhFK-xy76U4', '0hCihQ5Kep0', 'kDyK9VGfLW8', '36o2cux9kfQ', 'WXKgBIiP8IA', '87400', '112148', 'aCwLQrJz4Bo', 'Zj_4YmbMWtg', '233389', 'YGeVGXXK3ao', 'xk4C4p5vHDk', 'WZVfvgTeFPo', '4jTUcNlxlYA', 'FsmNLTdE2p0', 's0PUurm1ONo', 'W53uRqITk2I', '24xayGF5yYA', 'wCtZdAdoIm8', '6qPjYvdZiLA', 'ePtlUYCdrNM', 'RRKez9BR-94', 'kk4gr5A6_Uw', 'J7UduuBfnrE', '131936', 'STeqtJLakQQ', 'C-UUQju3bXo', 'HuIKyKkEL0Q', '59333', 'pI5Kng_GuLE', '1pvK0_9SQns', 'CfWxp5bRt2A', '91276']

**Comment by A2Zadeh** [comment]
@ntubertchen Oh wow this is bad! One more question: this is before any alignment correct? Meaning you get the data and the folds and this is how the state of the data is?

@Justin1904 did you run into this when you were doing experiments? 
@twoertwein did you see the same thing? :)

Thanks again @ntubertchen for raising the issue. We will promptly resolve (or get to the bottom) of this.

**Comment by twoertwein** [comment]
@A2Zadeh I noticed that there are a lot of emotion labels missing (compared to the list of videos in the train/eval/test set). I think there were about ~2000 videos with at least one emotion label but there are more than 3000 videos in the combined in the train/eval/test set.

**Comment by A2Zadeh** [comment]
@twoertwein thanks for the update. You mean we are missing 3000 videos or video segments? For example, video id x is completely missing? Did the same happen in sentiment?

**Comment by Justin1904** [comment]
@A2Zadeh For MOSEI I didn't keep count of this. However, I think I previously talked to you about something similar in POM dataset where there're data points with no labels and labels with no corresponding data points. I wonder if they are due to the same bugs.

**Comment by A2Zadeh** [comment]
@Justin1904 Oh I though POM issue was solved, no? But this is not about data points this is discrepancy between folds and labels. It's not touching on data points yet. Hence discrepancy between MTurk files and our folds, which I am sure is not the case because we picked the folds based on MTurk files. Can you check what ended up happening here, whenever you had time? Maybe my code has a bug for generating labels. I will double check too.

**Comment by twoertwein** [comment]
@A2Zadeh I said MOSEI has in total more than 3000 videos (according to the train/eval/test split) but for only about 2000 videos we have at least one emotion annotation. We are definitely missing emotion annotations for about 1000 videos. I don't know the exact numbers but you can easily get the setdiff between the IDs in http://immortal.multicomp.cs.cmu.edu/CMU-MOSEI/labels/CMU_MOSEI_LabelsEmotions.csd and the IDs in `cmu_mosei_std_folds.py`

**Comment by ntubertchen** [comment]
> @ntubertchen Oh wow this is bad! One more question: this is before any alignment correct? Meaning you get the data and the folds and this is how the state of the data is?
> 
> @Justin1904 did you run into this when you were doing experiments?
> @twoertwein did you see the same thing? :)
> 
> Thanks again @ntubertchen for raising the issue. We will promptly resolve (or get to the bottom) of this.

@A2Zadeh 
Correct, I looked into Sentiment data and the missing folder are the same for both labels in train/val/test.

**Comment by ntubertchen** [comment]
Hi @A2Zadeh , how are things going.

Will the new version be released soon?

**Comment by A2Zadeh** [comment]
@ntubertchen yup working on it currently ;). It should be fully solved by end of this week or early next week.

**Comment by A2Zadeh** [comment]
@ntubertchen This should be solved by now. Please let me know if you find any other issues.
