### ISSUE TITLE
MOSEI raw data

### ISSUE THREAD

**Issue by songxujing** [A2Zadeh/CMU-MultimodalSDK#68]
Hello there:
     I have downloaded the raw data of CMU-MOSEI, but there is no audio Segment data and label for each segment. What is the reason?

**Comment by songxujing** [comment]
@A2Zadeh

**Comment by A2Zadeh** [comment]
@songxujing we took down part of the data for now due to maintenance. You can download the raw data after the next two weeks.

**Comment by songxujing** [comment]
> @songxujing we took down part of the data for now due to maintenance. You can download the raw data after the next two weeks.
OK,thank you very much! @A2Zadeh

**Comment by A2Zadeh** [comment]
@songxujing we will have the data ready in the next two-three weeks.

**Comment by songxujing** [comment]
When can I down all  CMU-MOSEI raw_data? 
Thank you very much! @A2Zadeh

**Comment by A2Zadeh** [comment]
@songxujing just a few more days till we get our COVAREP fully done on the newest videos. You should be able to download next week.

**Comment by songxujing** [comment]
Sorry to bother you again, I still can't download the raw-MOSEI data, what is the reason? @A2Zadeh

**Comment by A2Zadeh** [comment]
@songxujing That's strange. Like from here? http://immortal.multicomp.cs.cmu.edu/raw_datasets/

BTW let me quickly update with all the files before you download it. I wanna put the raw label files also in it.

**Comment by songxujing** [comment]
After I clicked on the link, I found that the update time of the file was still in October 2018. Is the file in this file updated? @A2Zadeh

**Comment by A2Zadeh** [comment]
@songxujing Just an update: the zipping is now being done. It will take another 3-4 hours.

**Comment by A2Zadeh** [comment]
@songxujing the file ended up being around 300GB. I removed a bunch of things and am using a different algorithm to compress. It should be done tonight. If you need the 300GB file, I can share that one for now. Otherwise I will update in 12 hours.

**Comment by songxujing** [comment]
please share the 300GB file to me, thank you very much.

**Comment by songxujing** [comment]
please share the 300GB file to me, thank you very much. @A2Zadeh

**Comment by A2Zadeh** [comment]
@songxujing I was able to shrink it to 120gb. You can download it from http://immortal.multicomp.cs.cmu.edu/raw_datasets/CMU_MOSEI.zip
