### ISSUE TITLE
about the training of POM dataset 

### ISSUE THREAD

**Issue by wangteacher** [A2Zadeh/CMU-MultimodalSDK#69]
Hi @A2Zadeh, I wonder whether 16 different speaker traits labels of POM dataset should be predicted simultaneously via multi-label prediction, or it can be predicted and measured distinctly in different training instances via single-label learning.  Which method has been adopted in practice?

**Comment by KuzmaNg** [comment]
Hi @wangteacher,
same problem encounted, but I try single-label learning since it is also a multi-class problem inside each label.😂

**Comment by A2Zadeh** [comment]
@wangteacher, @KuzmaNg is right. In POM you actually have a multilabel classification not a multiclass one. You can do multitask learning and learn all the labels together (which is what we do).

**Comment by KuzmaNg** [comment]
Hi @wangteacher ,
any idea on the order of the speaker personality traits on POM dataset? I am not pretty sure about it since it is a bit different from the order mentioned in paper MFN (Memory Fusion Network). Thanks.

**Comment by A2Zadeh** [comment]
@wangteacher @KuzmaNg I am working on adding a new field to the metadata which outlines the name of the fields ;). Will do my best to fix it this week. For now this will help

`			personality_vec=[confident,passionate,voice_pleasant, dominant,credible,vivid,expertise,entertaining,reserved,trusting,lazy,relaxed,outgoing,thorough,nervous,humerous]
			persuasion_vec=[persuasive]
			sentiment_vec=[sentiment]`

**Comment by A2Zadeh** [comment]
@KuzmaNg thanks for participating in the SDK form. Can you send me an email for follow up? I don't have your email :)

**Comment by KuzmaNg** [comment]
Hi @A2Zadeh . I just sent an email to you. 😄
