### ISSUE TITLE
segment question

### ISSUE THREAD

**Issue by rhoposit** [A2Zadeh/CMU-MultimodalSDK#70]
I want to associate the interval (segment?) of an emotion label with raw audio data.

For example 
```
ID: jICmfLeFymA, 
interval: [71.06 , 78.745]
emotions: [0.6666667, 0., 0., 0., 0., 0.]
```
Does the interval mean offset in seconds? For example, could I use this interval somehow for identifying the exact time slice where the emotion occurs in that video, and if so, what does the 71 and 78 represent? Sorry if this was covered already but I didn't find an issue for it.

**Comment by A2Zadeh** [comment]
Hello Jennifer (@rhoposit). Yes the interval means offset in seconds. That information tells you that between seconds 71.06 and 75.745 you have the above emotions in your segment.
