### ISSUE TITLE
MOSEI unique speakers

### ISSUE THREAD

**Issue by rhoposit** [A2Zadeh/CMU-MultimodalSDK#71]
Is there information for which videos, if any, have the same speaker? Or is it safe to say each unique video also is a unique speaker?

**Comment by A2Zadeh** [comment]
@rhoposit it is not safe to assume each video is from the same person. I believe we have that information somewhere and I can definitely share. It is however safe to assume that there is no person shared among train, test and validation folds.

**Comment by DimitrisKatsiros** [comment]
@A2Zadeh Hello there ! Is there any progress on the speaker id's retrieval? Can we use cmu_mosei for speaker verification?
