### ISSUE TITLE
incomplete BERT embeddings for MOSI dataset

### ISSUE THREAD

**Issue by dem123456789** [A2Zadeh/CMU-MultimodalSDK#72]
It seems like BERT only has 2187 samples and all others have 2198 samples.
After performing [word_level_align.py](https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/examples/word_level_align.py)

**Comment by A2Zadeh** [comment]
@dem123456789 Yup. I removed the ones with only 1 word (can you check if those are the ones from raw data in CMU-MOSI?). BERT seemed to crash for 1 word sequences. For example, the utterance of word OK! may convey sentiment in multimodal language (for example shout and smile accompanied). Unfortunately, we have to wait and see what happens. You can remove those 5 for now.

**Comment by dem123456789** [comment]
@A2Zadeh I also find there is a -inf in one sequence of COAVAREP, and shouldn't it be COVAREP?

**Comment by dem123456789** [comment]
What about multiple labels?

**Comment by A2Zadeh** [comment]
@dem123456789 I just realized there was a small bug in BERT. You should not have any problems if you run your code again (and download from our servers). Let me look into the multiple labels. Sequence length may be different, you need to look at intervals. In general everything is based on beginning and end. So it may be possible to get 10 facet samples and 100 COVAREP for the same duration.

**Comment by dem123456789** [comment]
@A2Zadeh I think if we perform word align using [word_level_align.py](https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/examples/word_level_align.py), we should end up with the same sequence lengths for any features we use right? Compared with covarep, 3 for facet and 1 for glove are having different lengths and they are just short by 1 time step.

**Comment by A2Zadeh** [comment]
@dem123456789 I am having a hard time understanding the problem :). Is it the case that for example videox [y] does not exist or the number intervals for that video segment are different across the computational sequences?

**Comment by A2Zadeh** [comment]
I see. Would you be able to give me the exact video id after alignment that has this issue? In general it's ok to have different number of entries in interval but the beginning of the first and end of the last element should match among all.

**Comment by dem123456789** [comment]
@A2Zadeh 
This is the [code](https://gist.github.com/dem123456789/a0ec567346e11c1c8329b202c8cc3384) I write for detecting anomlies in the data.

I deactivate the detection for BERT for the non-alignment detection, because there are too many. You can change line 28 to print them.

**Comment by A2Zadeh** [comment]
I do. I will update the zip file soon, with that information. Will let you know here. Thanks for sharing the code. I will have a look at it :)

**Comment by A2Zadeh** [comment]
@dem123456789 Just to give you a small update on how things are going. We are finishing up the feature extractions for the new videos. FACET is already done but we are waiting for COVAREP. The label files will also be updated. In the meantime, please download the labels from: 
http://immortal.multicomp.cs.cmu.edu/cache/Labels_for_dem123456789.zip

Please do note that some segments may have been removed or corrected (majority 99% are still the same). Also, for the paper we used a specific metric to convert from regression to classification. For regression, you can just average the labels between 3 annotators (some very rare videos may have 2 or 4).

**Comment by dem123456789** [comment]
@A2Zadeh Thanks for updating and sharing the label files.
It would be better if we can know how the classification labels are generated if it is not simple scaling and quantizing from regression labels.

**Comment by A2Zadeh** [comment]
@dem123456789 

This is what we use:

```
def cmumosei_round(a):
        if a < -2:
                res = -3
        if -2 <= a and a < -1:
                res = -2
        if -1 <= a and a < 0:
                res = -1
        if 0 <= a and a <= 0:
                res = 0
        if 0 < a and a <= 1:
                res = 1
        if 1 < a and a <= 2:
                res = 2
        if a > 2:
                res = 3
        return res
```

Please note that neither the round function or this form of round are psychologically studied, therefore I personally prefer MAE and correlation. The round function is just to make things more intuitively understandable.

**Comment by A2Zadeh** [comment]
@dem123456789 I am going to close this issue, but if you have any other questions please don't hesitate to post or email me.
