### ISSUE TITLE
Word Level Alignment: Key Error

### ISSUE THREAD

**Issue by sverma88** [A2Zadeh/CMU-MultimodalSDK#84]
Hi Amir,

I'm facing issue while performing word level alignment for CMU_MOSI and CMU_MOSEI datasets.
It is showing raising key error is both cases, I've downloaded the datasets again and tried to perform word level alignment but faced similar issue.

I'm attaching the screen shots of the issue
![mosei_error](https://user-images.githubusercontent.com/19421577/51517075-b21ca100-1e6d-11e9-8b99-8e93bbde6374.PNG)

**Comment by A2Zadeh** [comment]
@sverma88 just following up, is this still an issue?

**Comment by sverma88** [comment]
Hi Amir,

Many thanks for the prompt reply.
Now they are working, I'll close the issue this evening is everything goes fine.

However, please look at line no 221 in dataset.py.
I think there's an additional 's'.

**Comment by A2Zadeh** [comment]
@sverma88 noted! I fixed it, don't know how it got there :). The code seemed to be running, maybe it never went in that for loop for my test cases.
