### ISSUE TITLE
How is Acc-2 usually calculated?

### ISSUE THREAD

**Issue by ntubertchen** [A2Zadeh/CMU-MultimodalSDK#87]
Hi there,

I don't know if this answer is appropriate here. But how does the paper related to MOSI dataset calculate their Acc-2 accuracy. Do people usually ignore features with 0 label and calculate only values larger than zero of smaller than zero?

**Comment by A2Zadeh** [comment]
On MOSI we actually just gave zeros to the positive class. On MOSEI we removed the class 0 (remember that code I shared for 7-class). Again all of these are not as important as MAE and correlation. Does that answer your question?
