### ISSUE TITLE
MOSEI: videos without faces

### ISSUE THREAD

**Issue by twoertwein** [A2Zadeh/CMU-MultimodalSDK#88]
The following videos do not contain a person in the video (two of them have a tiny tiny tiny view of a face in the lower left-hand corner). OpenFace does also not find a face in these videos.

_HanACduNJk
XPoY4LD-A1I
dbpGH5iP0GE
s53UAEi7JEY
UPghCarcnMc
FvoZgWvc3gc
aI1tdJPHz2I
Ve-mmCM8TI0
pzUplbeH_fg
AB1PbMaW03s
faUvT7zfsyk
a4PHWxILDp0

It might still be legit to keep these videos as part as MOSEI because it might be possible to infer sentiment and emotions based on the text and audio. On the otherhand there is also compelling reason to remove them because MOSEI was designed to contain monologues were one face is visible.

**Comment by A2Zadeh** [comment]
Yes, that's a great idea. The newest version of MOSEI will come out probably around 6 months with multilingual data. We will remove these ids from them.
