### ISSUE TITLE
MOSEI: two testset videos without labels

### ISSUE THREAD

**Issue by twoertwein** [A2Zadeh/CMU-MultimodalSDK#89]
The video ids `7l3BNtSE0xc` and `dZFV0lyedX4` are both in the testset (`mmdatasdk.cmu_mosei.standard_folds.standard_test_fold`) but they have no labels (not in CMU_MOSEI_LabelsEmotions.csd and not in CMU_MOSEI_LabelsSentiment.csd).

Looking through the raw MOSEI data, I noticed that you have transcripts for both of them and annotations. Unfortunately, they have no overlap (interval were annotated for which no transcripts exist).

**Comment by A2Zadeh** [comment]
@twoertwein Thanks! I will look into that. We did remove some datapoints during MTurk annotation phase but never removed them from the preassigned folds. Then during experiments we just used videos from each fold as long as they had at least one segment annotated. I will look into this further. For now, it is safe to remove them from the folds. I will do it now.
