### ISSUE TITLE
Issue following README.md

### ISSUE THREAD

**Issue by max-sargent** [A2Zadeh/CMU-MultimodalSDK#92]
Hi there,

I am trying to to follow the steps in the usage section of the README.md file. However when I attempt to align the dataset using the opinion segment labels python throws a key error.

KeyError                                  Traceback (most recent call last)
<ipython-input-8-e1c1e4f55f0f> in <module>
----> 1 cmumosi_highlevel.align('Opinion Segment Labels')

~\Documents\Work\Dissertation\CMU-MultimodalSDK\mmsdk\mmdatasdk\dataset\dataset.py in align(self, reference, collapse_functions, replace)
    111                                 for otherseq_key in list(self.computational_sequences.keys()):
    112                                         if otherseq_key != reference:
--> 113                                                 intersects,intersects_features=self.__intersect_and_copy(ref_time,relevant_entries[otherseq_key][entry_key],epsilon)
    114                                         else:
    115                                                 intersects,intersects_features=refseq[entry_key]['intervals'][i,:][None,:],refseq[entry_key]['features'][i,:][None,:]

KeyError: '03bSnISJMiM'

I am not sure how to proceed but thought I would raise the issue here while I investigate myself.

Thanks,
Max Sargent

**Comment by A2Zadeh** [comment]
Hello @max-sargent that was a small issue with spaces and tabs (I developed code on two machines and somehow that happened). If you pull the sdk again it should be ok. Let me know if that solves it.

**Comment by max-sargent** [comment]
I have updated my fork with the most recent changes and it seems to have done the trick, thanks for the quick reply!
