### ISSUE TITLE
Validate Features in the SDK for CMU MOSI and CMU MOSEI datasets

### ISSUE THREAD

**Issue by sverma88** [A2Zadeh/CMU-MultimodalSDK#93]
Hi Amir,

Please confirm my findings on the features provided by the SDK.

1. Facet features: Features in column 3 and 4 are identical for all videos!
2. GloVe embeddings frequently contains few identical features. I've watched to the video segments and the transcripts are completely different (joining words are there such as  'the' and 'a'); am I missing something? 
Video id: 80tFthrtaJM[4-6] in CMU_MOSI dataset

Thanks

**Comment by A2Zadeh** [comment]
@sverma88 Thanks for raising these issue here. 

1. I have to look into that. What are their values exactly? Technically that shouldn't be the case since those columns are contempt and disgust.

`feature_ids={imageid, timestamp, Anger,Contempt,Disgust,Joy,Fear,Baseline,Sadness,Surprise,Confusion,Frustration,AU1,AU2,AU4,AU5,AU6,AU7,AU9,AU10,AU12,AU14,AU15,AU17,AU18,AU20,AU23,AU24,AU25,AU26,AU28,AU43,Has_Glasses,Is_Male,Pitch,Yaw,Roll}`

2. What are the identical features you are experiencing? Too many zero values? If so that is correct because alignment frequently outputs speech pause between words.

**Comment by A2Zadeh** [comment]
I just had another look at the code for both glove and FACET. I wasn't able to find a bug in them. They are relatively simple codes since I just put things into computational sequence format. 80tFthrtaJM[4-6] is based on word alignment?

**Comment by sverma88** [comment]
Hi Amir,
Okay, so let's break it down for FACET features for CMU-MOSI dataset.

1. Is the feature length 47? If no then it's a problem at my end and not yours.
2. If yes, then the third column and 4th column has identical values; i.e. identical real numbers.

**Comment by sverma88** [comment]
Hi AMir,

Yes, I've done word alignment by executing word_level_align.py scripts from the examples folders of the SDK. 

Please check the GloVe embeddings value for
80tFthrtaJM[4] Rows: 2, 10, 15, 17
80tFthrtaJM[5] Rows: 1,9, 11, 20, and 26
80tFthrtaJM[6] Rows: 1 and 6.
You can match their values across the video segments and they are identical.

Once again, word_level_align.py is executed on CMU MOSI dataset.

Also: The number of columns in feature_ids (from above) are 35 (excluding video_id and timestamp).
Can you please tell me why is the feature length 47 (or 46) in the SDK?

You can also suggest some sanity checks at my end to re-confirm your findings.

**Comment by sverma88** [comment]
Hi Amir,

By rows, I mean the features values in the GloVe vectors.
For 80tFthrtaJM[4] the feature matrix is of dimension 17*300 (300 is the dimensions of GloVe embeddings, yes?)

The speaker says "do not understand this movie".
I'm guessing the each GloVe vector must be unique (atleast for this sentence.) 
My assumption might be wrong as I'm not an expert in NLP.

**Comment by A2Zadeh** [comment]
Yes 300 is the glove dimensions. Hmm, let me dive into this issue. Thanks for raising it. I will look at it in the next few hours and let you know what happened.

**Comment by A2Zadeh** [comment]
I think I found where the problem is. You are currently comparing the 80tFthrtaJM[4] as the case that 4 is the same as the 4th segment in the video. SDK may decide to give you a different number for segment than the one in the raw data. The labels will not be wrong, it's just that sdk sees a different segment as 4th. This is something that I am working on right now since h5py does not have ordered dictionary. What you can do however, is to see where the beginning and end of the 80tFthrtaJM[4] is and then watching the video from that beginning and the end. You can simply look at the intervals and take the min and max value. Always helps to pull the sdk as well, just to be updated with all the changes I have made recently.

**Comment by sverma88** [comment]
Hi Amir,

I'll check as suggested by you and will confirm later this evening.
However, should I still assume duplicated column values in FACET features for CMU-MOSI?

**Comment by A2Zadeh** [comment]
@sverma88 Great. Let me know how it goes. If you find something that resembles a bug, please don't hesitate to share.

**Comment by sverma88** [comment]
Hi Amir,

I've pulled the SDK this morning and their are new issues now!

1. There is more than one Sentiment label for CMU-MOSEI dataset.
2. Many segments in CMU MOSI does not have any label. e.g. 'GdFP_p4eQX0'.

I'm still working on matching the segment on raw CMu MOSI datatset. However, i think it's not possible as the raw data contains short clips; they are not tagged with start and end time.

**Comment by A2Zadeh** [comment]
@sverma88 

1) Yes, the sentiment labels are based on video segment. Each video may have multiple labels for different segments.

2) CMU-MOSEI and CMU-MOSI are actually semi supervised datasets, so there will be segments or videos without any annotations. GdFP_p4eQX0 in your CMU-MOSI has no sentiment in it at all?

The segments from SDK and raw segments will not match in segment number but will match for beginning and the end. You can simply get that information from Labels directory in CMU-MOSI. Specifically, the file that contains sentiment labels has segment numbers also in it. 

Let me know if this helped.

**Comment by sverma88** [comment]
Hi Amir,

I'm need your help now to read the CMU-MOSI dataset from the SDK.
As you said, the dataset us semi-supervised and some of the segments might not have annotations.

Let's start with a simple case:
For Key --qXJuDtHPw in validation fold
sentiment value =  '1' with interval = [ 23.1990 : 30:3250]
I've over 180 Segments marked as --qXJuDtHPw[0-175] with some real feature value and interval values
in the COVAREP.csd.

How to interpret this? How to read the data and work?

Kindly suggest some policy for extracting data for supervised tasks in the SDK.

**Comment by A2Zadeh** [comment]
@sverma88 Yeah that basically means you have [0-175] words in that video. After doing word alignment, if you do alignment based on labels it will solve the issue. Please refer to this example for that: https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/examples/mmdatasdk_examples/word_level_align.py

After the code completes, you will have exactly as many segments as CMU-MOSI has annotations for.

**Comment by sverma88** [comment]
Hi Amir,

How to use word_align for CMU-MOSEI dataset?
Opinion Sentiment Labels are not present in the data. However,  when I load the csd file for Sentiment Labels they are read as Sentiment Labels.

I've did modified the code but it didn't worked.
Is there any other namespace?

**Comment by A2Zadeh** [comment]
Yeah for CMU-MOSEI, you can have a look at => https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/mmsdk/mmdatasdk/dataset/standard_datasets/CMU_MOSEI/cmu_mosei.py
to see what the name of the computational sequences are. You are referring to` "Sentiment Labels"`
