### ISSUE TITLE
Missing opinion segment label in MOSI

### ISSUE THREAD

**Issue by max-sargent** [A2Zadeh/CMU-MultimodalSDK#94]
Hi again,

I have been working on loading data from the cmumosi dataset, I've noticed a missing value in the opinion segment labels computational sequence.

'2WGyTLYerpo[43]' is missing, it goes from 42 to 44.

If this is something to be expected please let me know, or if not I have now brought the issue to your attention.

Thanks,
Max Sargent

**Comment by A2Zadeh** [comment]
@max-sargent yeah that is totally fine. We removed some weird segments but I just assigned length zero to them. So SDK will simply remove those.

**Comment by max-sargent** [comment]
This has cleared a lot up, thanks.
