### ISSUE TITLE
Were all extracted features used in DFG/MOSEI publication?

### ISSUE THREAD

**Issue by caseyfitz** [A2Zadeh/CMU-MultimodalSDK#96]
Hi Amir,

I'm wondering if all extracted features listed in Sec 3.3 were used as input to the DFG model described in [the original publication](http://aclweb.org/anthology/P18-1208). If not, which were?

Thanks!

**Comment by A2Zadeh** [comment]
For CMU-MOSI we did feature selection (refer to https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/related_repos/Memory_Fusion_Network/Memory_Fusion_Network.md) 

Except for CMU-MOSI, all the other datasets used all the features we provide in the SDK. 

For CMU-MOSEI, during publishing original paper, we had some bug in some videos for COVAREP. Therefore the paper results are actually worse than what you would get if you run on the correct data. I can share the old data if you want to recreate the exact results of the publication or you can look at the proceedings from our workshop at ACL which uses the corrected data (
http://www.aclweb.org/anthology/W18-3300). 

Hope this helps.

**Comment by caseyfitz** [comment]
Thanks Amir,

I'll check out the updated results. What caught my eye actually is the Sec. 3.3 visual feature `We also extract a set of six basic emotions purely from static faces using Emotient FACET`, which seemed strange as a feature since that is the target variable.

Am I understanding that right?

(new to affective and multimodal so please excuse any silly questions!)

**Comment by A2Zadeh** [comment]
@caseyfitz good question. We use FACET to extract emotion priors just coming form visual modality, since in computer vision this has bee studied based on facial images. It makes our visual modality more strong in general. 

No worries at all. Let me know if you had any other questions :)
