### ISSUE TITLE
IEMOCAP features and highlevel features from SDK

### ISSUE THREAD

**Issue by hemnf** [A2Zadeh/CMU-MultimodalSDK#97]
Dear @A2Zadeh,
Thank you for your grate work. I would like to know the better way to contact you for getting the password of IEMOCAP zip file in preprocessing link? I already sent you an email through your website.
Also I am kindly asking you what is the different between the feature from preprocessing link (h5 files) and highlevel features form SDK (csd files).

Also when I run this line `"cmumosi_highlevel.align('Opinion Segment Labels')"` for mosi will work well, but when I want to use it for mosei, it gave me this error:
`RuntimeError: <Error>: Computational sequence <Opinion Segment Labels> does not exist in dataset`

Thank you again

**Comment by A2Zadeh** [comment]
Hello @hemnf 

I did see your email, sorry it took me a while to get to it. I will respond to you soon with the password.

The difference between the old files and the csd is that csd is always kept up to date. The old files were used for our experiments prior to 2019. From now on we will only use SDK files to get our results. csd is the official format for the SDK and it allows you to do fast alignment and other operations in an efficient way. Rule of thumb: if you wanna just recreate results from our papers, you can use either - if you wanna experiment with new ways of alignment or take matters into your own hand, use csd and sdk. 

Yes, MOSEI has a different name for the labels. Please have a look here: https://github.com/A2Zadeh/CMU-MultimodalSDK/blob/master/mmsdk/mmdatasdk/dataset/standard_datasets/CMU_MOSEI/cmu_mosei.py

**Comment by hemnf** [comment]
Dear @A2Zadeh 
Thanks a lot for your kind reply. Appreciate it.
Regards
